### ISSUE TITLE
seata AT 与 XA 模式动态数据源切换功能

### ISSUE THREAD

**Issue by HelloSSM** [apache/incubator-seata#2695]
在某些业务场景下，可能要求全局事务的读提交，现在应该是可以通过select for update + AT模式来完成，在某些业务场景，为了性能，可能并不这么需要，AT模式就能完成。当然，这只是一个想法哈，这个需求和我们在项目里的读写数据源的动态切换类似，不知道seata是不是已经支持了，我看下来好像是不支持的。（ps：来自懒人的想法）

**Comment by slievrly** [comment]
@HelloSSM good idea.
