### ISSUE TITLE
[Summer 2021] Implement Seata SDK with C#

### ISSUE THREAD

**Issue by liushv0** [apache/incubator-seata#3748]
# Background
Seata currently supports Java, Golang, PHP,  and we expect Seata to support more programming languages. It is required to refer to the architecture design and implementation of Seata Java, and Implement a Seata client with C#,  which support  Seata's AT mode, and can run through the main process of Seata AT on MySQL.

The Seata community wants to open  the task to `Summer 2021`.

 
 # Target
 Implement Seata SDK with C#
 
 # Difficulty
 Hard
 
 # Mentor
@liush
[ls_871211@163.com](mailto:ls_871211@163.com)

 # Output Requirements
* Seata sdk implement by C#
* run through main process of Seata AT mode on MySQL
 

# Technical Requirements
 * Familiar with C# programming language.
 * Understand common design patterns
 * Ability to read source code 

———————————————————————— 

# 背景
 
目前Seata 支持了Java、Golang、PHP语言，期待 Seata 能够支持更多的编程语言。要求参考 Seata Java的架构设计实现，使用 C# 实现 Seata 的 AT 事务模式的 client，能够跑通 Seata AT MySQL的主流程。

Seata 社区想将这个任务开放给 `Summer 2021`。
 
 # 目标
Seata C# 多语言支持
 
 # 难度
 困难
 
 # 导师
 @liush
 [ls_871211@163.com](mailto:ls_871211@163.com)
 
 # 产出要求
 *  用C#实现一个seata client SDK
 *  能在MySQL上跑通Seata AT模式主流程
 
 # 能力要求
 * 熟悉C#开发语言。
 * 理解常见设计模式。
 * 具备一定的源码阅读能力

**Comment by tanher** [comment]
请问这个有人在做了吗？

**Comment by l81893521** [comment]
> 请问这个有人在做了吗？

Yes, it already applied by student from iscas summer code.

**Comment by tanher** [comment]
大概是什么时候会发布？ 有时间表吗？

**Comment by zivfuture** [comment]
any update?

**Comment by SpringHgui** [comment]
做了两年多了？

**Comment by slievrly** [comment]
This project has been abandoned.

**Comment by SpringHgui** [comment]
有没有相关对接的文档，给个实现的流程？ @slievrly

**Comment by l2999019** [comment]
为什么项目会被放弃了 是有什么困难么? 是否有Seata的接口文档  看看能不能实现?
