### ISSUE TITLE
[Summer2021] Integrate `RocketMQ` into `Seata`

### ISSUE THREAD

**Issue by wangliang181230** [apache/incubator-seata#3752]
# Background
  In a distributed transaction, there may be many types of transaction resources involved. In order to achieve the consistency of distributed transactions, all types of transaction resources must be managed.
  In this task, we expect to use TCC mode to integrate `RocketMQ` into `Seata`.

  The Seata community wants to open the task to `Summer 2021`.

# Target
  Use TCC mode to integrate `RocketMQ` into `Seata`.

# Difficulty
  Medium

# Mentor
  @wangliang181230
  [841369634@qq.com](mailto:841369634@qq.com)

# Output Requirements
  * Use the proxy mode to proxy the `RocketMQ` bean.
  * In the proxy, use TCC mode to integrate `RocketMQ` into `Seata`.

# Technical Requirements
  * Familiar with Java programming language.
  * Understand common design patterns
  * Ability to read source code 

———————————————————————— 

# 背景
  在一个分布式事务中，可能会有多种类型的事务资源参与进来，为了达到分布式事务一致性，必须将所有类型的事务资源都管理起来。
  此次任务，期望使用TCC模式，将`RocketMQ`整合到`Seata`中。

  Seata 社区想将这个任务开放给 `Summer 2021`。

# 目标
  使用TCC模式，将`RocketMQ`整合到`Seata`中。

# 难度
  中等

# 导师
  @wangliang181230
  [841369634@qq.com](mailto:841369634@qq.com)

# 产出要求
  * 使用代理模式，代理掉RocketMQ的Bean。
  * 在代理中，使用TCC模式，将`RocketMQ`整合到`Seata`中。

# 能力要求
  * 熟悉Java开发语言。
  * 理解常见设计模式。
  * 具备一定的源码阅读能力。

**Comment by wangliang181230** [comment]
#3741

**Comment by web1992** [comment]
不是学生可参加吗🙈

**Comment by wangliang181230** [comment]
不是学生不能参加。
你是想领任务么？

**Comment by web1992** [comment]
这里想问下，有具体的思路吗，我们内部最近也准备使用Seata的TCC，但是与RocketMQ 的整合好像怎么都不太适合。
还是在初步探究阶段。

**Comment by web1992** [comment]
> 这里想问下，有具体的思路吗，我们内部最近也准备使用Seata的TCC，但是与RocketMQ 的整合好像怎么都不太适合。
> 还是在初步探究阶段。
或者有哪些资料可以参考的吗？

**Comment by cm066** [comment]
我也想参加

**Comment by Bughue** [comment]
我这边下周会提交新pr
