### ISSUE TITLE
seata consul 配置中心，希望能够自定义目录

### ISSUE THREAD

**Issue by Amountsen** [apache/incubator-seata#3778]
## Why you need it?
 目前 1.4.2 版本 使用consul做配置中心时， 读取配置是从consul 根目录读取的，还不支持从自定义的目录读取配置，
这让配置中心的数据难以归类管理。

## How it could be?
希望能够支持自定义配置目录

**Comment by a364176773** [comment]
好主意,这样就能在一个consul上资源隔离多个client和server端的配置项了

**Comment by a364176773** [comment]
不过我突然想到,我们有一个pr,是支持一个配置key对应一堆的value的,也就是把script里的config.txt弄到了一个key中,你看看能否满足需求?如果满足,好像也可以资源隔离了https://github.com/seata/seata/pull/3311
