### ISSUE TITLE
请问将来会支持国产数据库，比如：人大金仓(kingbase)，达梦（Dameng）

### ISSUE THREAD

**Issue by algigka** [apache/incubator-seata#3837]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by caohdgege** [comment]
达梦：https://github.com/seata/seata/pull/3672

**Comment by funky-eyes** [comment]
dameng Database has now completed support
