### ISSUE TITLE
想请问一下seata回滚失败，一直在重试，我该如何及时获取到此时的状态并做出相应的处理.

### ISSUE THREAD

**Issue by 1254744129** [apache/incubator-seata#4058]
## How it could be?
           今天测试demo的时候发现（使用AT模式）  
一阶段   a服务添加一条记录成功   此时我手动去修改a服务的数据库   b服务添加一条记录失败     
二阶段  开始回滚  发现 a服务的数据库和undo_log的镜像数据不一致    java控制台一直打印 二阶段回滚重试的日志
请问一下，我该如何来查看哪些全局事务出问题了呢？

**Comment by 1254744129** [comment]
@a364176773  你好，我就是特想知道字段的含义，但是官网上并没有发现.    global_table , branch_table , lock_table 这三张表的sql我也是百度的，官网上 我只找到了undo_log的sql语句。能否给一个连接呢，谢谢啦

**Comment by 1254744129** [comment]
好的，我再看一遍。谢谢了

**Comment by a364176773** [comment]
官网的建表语句是在新人文档，那块有说建表语句放在了哪，有个超链接可以点击的
