### ISSUE TITLE
seata在yml文件中和baomidou配合使用时数据库切换失败

### ISSUE THREAD

**Issue by lihongjielive** [apache/incubator-seata#4072]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
seata在yml文件中和baomidou配合使用时数据库切换失败，导致持续性提示retrycallback

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
使用@DS注解切换数据源

**Comment by a364176773** [comment]
是否有资源重入，比如update 数据源1的某个记录，然后切换数据源，又切回来1，又进行了update？
如果有类似行为请检查tc branch table里的datetime字段精度是否设置为8，自己对比下最新seata仓库script文件夹里的tc建表语句，和本地undolog语句，进行校准
如果没有，就保证你所有写的入口被@globaltransational包裹进入，否者就可能出现被没有@globaltransational的地方改动，导致脏写
