### ISSUE TITLE
A调用B，A服务报错B feign超时，但是B的事务没有回滚

### ISSUE THREAD

**Issue by lehug** [apache/incubator-seata#4088]
## env
spring cloud + spring boot 2.2 + open feign + mybatis
seata-server 1.4.1, seata client 1.4.2, db store， at mode
## 代码结构
 入口服务为A服务，有@GlobalTransaction, @Transaction注解。先excel数据检查，然后调用B服务创建数据。
B服务有@Transaction，B服务有多次插入，3次1500数据量的插入，耗时较长。正常情况下，B执行完毕后，A服务再进行一些数据插入操作，整个调用链结束。

### A服务 
- 18:38:21 接收到请求， 
- 18:38:30  `unbind 10.40.0.6:8080:193434165151031296`  `rollback status: Rollbacked`  `Read timed out executing POST http://`
### B服务 
开始执行插入，3个插入，总共到18:38:44结束。
18:38:44 报错 `io.seata.core.rpc.netty.RmNettyRemotingClient@7853f920 msgId:16, body:MergeResultMessage BranchRegisterResponse: branchId=0,result code =Failed,getMsg =TransactionException[Could not found global transaction xid = 10.40.0.6:8080:193434165151031296, may be has finished.]`
### seataServer: 
- 18:38:19  Begin new global transaction applicationId
- 18:38:19 A服务注册成功 RM register success,message:RegisterRMRequest 
- 18:38:27 B服务注册成功 RM register success,message:RegisterRMRequest
- 18:38:35  Rollback global transaction successfully, xid = 10.40.0.6:8080:193434165151031296.
- 18:38:44   Catch TransactionException while do RPC, request: xid=10.40.0.6:8080:193434165151031296,branchType=AT

## 其他
- 数据库层面是先B，后A的。但是入口时在A服务，@GlobalTransaction加到B服务？

**Comment by lehug** [comment]
@a364176773  有一点新发现，全局事物开启后， B服务还有`RM register success,message:RegisterRMRequest{resourceIds=`的日志输出，重新注册了？导致不能回滚了？

**Comment by a364176773** [comment]
跟这个没关系，自己debug，注册上才能回滚

**Comment by lehug** [comment]
更新，抱歉，搞错了，回滚了。。。
目前只有一次  java.io.IOException: Broken pipe 后，事物没有回滚。具体原因待查明
