### ISSUE TITLE
seata1.2.0 nacos 2.0.3 unknown user!

### ISSUE THREAD

**Issue by xuweihao** [apache/incubator-seata#4091]
账号密码都正确的，也是有读写权限的，可以通过nacos-config.sh上传配置，但是通过docker启动的时候，就一直unknown user!

**Comment by a364176773** [comment]
升级到1.3及以上试试，老版本好像nacos用的client是1.1.4估计不支持鉴权

**Comment by xuweihao** [comment]
已处理好，1.3.0可以，不过只感觉全程都unkown user，serverAddr需要加端口，注册中心不能添加group
