### ISSUE TITLE
经常报 Could not found global transaction xid

### ISSUE THREAD

**Issue by djvip001** [apache/incubator-seata#4097]
部署的是3台seata 1.4.2,集成的是nacos ,但是又是报错，有时又不报，下面日志是同一时间打印的

节点1的日志：
![微信截图_20211025212205](https://user-images.githubusercontent.com/29300542/138703750-330ad7b0-6530-418d-b93d-11e876376190.png)

节点2的日志：
![微信截图_20211025212231](https://user-images.githubusercontent.com/29300542/138703751-0c841df7-ae69-437c-b767-c02b53ba2ea8.png)

节点3的日志：
![微信截图_20211025212604](https://user-images.githubusercontent.com/29300542/138704046-6e24f466-3bb5-4ec7-852d-7d002e6bc1a2.png)

**Comment by ddddddduan** [comment]
大佬，问题解决了么？什么原因造成的，怎么解决的能否指点下
