### ISSUE TITLE
事务回滚失败，mysql 使用 loadbalance 进行mysql 负载均衡，RM 调用发起回滚执行异常

### ISSUE THREAD

**Issue by ChenXueSong99** [apache/incubator-seata#4344]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

事务回滚失败，mysql 使用 loadbalance 进行mysql 负载均衡，RM 调用发起回滚执行异常
### Ⅱ. Describe what happened
微服务，基础框架：SpringCloud Alibaba 2021.1、数据连接池：Hikari（Druid 也不行），数据库mysql-cluster 8.0 版本，部署了 2个MYSQL 节点 2个 NDB节点，2个MGM管理节点，使用 Seata 作为分布式事务管理
数据库连接：jdbc:mysql:loadbalance://192.168.100.50:3306,192.168.100.51:3306/pinecone-cloud?roundRobinLoadBalance=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false

Bug发生经过：
客户端 -> 网关 -> A服务(事务发起者 TM) -> B服务（事务参与者 TC）抛出异常，A事务发起回滚，RM执行发起回滚，执行异常回滚
异常内容：io.seata.core.exception.TransactionException: java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql:loadbalance://192.168.100.50:3306,192.168.100.51:3306/pinecone-cloud,clientId:pinecone-system:192.168.100.221:58865
 
日志详见附件：
```
[seata-server.9200.all.log](https://github.com/seata/seata/files/7938831/seata-server.9200.all.log)

```

### Ⅲ. Describe what you expected to happen
正常应该回滚成功

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Seata 驱动：mysql-connector-java-8.0.19.jar
2. 微服务数据库驱动：com.mysql.cj.jdbc.Driver
3. 多MySQL节点，数据库连接使用 loadbalance 负载均衡

### Ⅴ. Anything else we need to know?
如果换成单mysql 连接就可以
例如：jdbc:mysql://192.168.100.50:3306/pinecone-cloud?rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false （已测试，执行正常）
数据库表引擎为 ndb：
![图片](https://user-images.githubusercontent.com/33630678/151103299-4d0e1763-7126-47bf-9fe2-6348b2ce82bb.png)
![图片](https://user-images.githubusercontent.com/33630678/151103337-49412afb-2bc2-4375-8db7-1d0b403e91e6.png)

### Ⅵ. Environment:

- JDK version : Jdk8 1.8.0_202
- Seata version:  Seata 1.4.2
- OS : Windows 10
- DataBase: mysql-cluster 8.0 ( Linux CentOS 7.6、Docker 部署)
- Others:  Nacos 2.0.3 作为注册、配置中心

**Comment by a364176773** [comment]
1.4.2不兼容mysql-cluster的连接串，后续修复一下
