### ISSUE TITLE
关于Fastjson反序列化漏洞风险通告

### ISSUE THREAD

**Issue by edifangyi** [apache/incubator-seata#4635]
我在1.4.2版本里找到一个fastjson.jar包
请问1.5.1里没有用吧

**Comment by a364176773** [comment]
只要你不启用fastjson作为seata的undolog序列化工具,就不会用到

**Comment by edifangyi** [comment]
> 你不启用jsonseata的undologfast作为序列化工具，就不会发生

请问可以用什么办法把seata-server.jar包里的fastjson-1.2.73.jar直接删了可否？
因为部署到公有云上后，安全系统会检测到这个fastjson.jar在使用
