### ISSUE TITLE
DistributedLock insert error with oracle

### ISSUE THREAD

**Issue by LGAKing** [apache/incubator-seata#4717]
When I use the latest version of seata in the project, the exception "not support value" is reported at startup. At the same time, looking at the source code, the insert into statement is not adapted for dbType. In addition, when I try to modify the statement and add the Oracle Driver, I cannot get a runnable Jar using the mvn package command in seata-server.

DB Version：
Oracle 19c

Error Sql with Code：
```java
protected static final String INSERT_DISTRIBUTED_LOCK_SQL = "INSERT INTO " + DISTRIBUTED_LOCK_TABLE_PLACE_HOLD + "("
            + ALL_COLUMNS + ") VALUE (?, ?, ?)";
```

**Comment by a364176773** [comment]
Can you send the stack？

**Comment by LGAKing** [comment]
> Can you send the stack？

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/30015398/174564529-f55a84ae-890b-42b7-b9b0-19dc4fc8763d.png">

this is the stack, and there are any way to package seata-server jar with myself?

**Comment by a364176773** [comment]
@caohdgege PTAL

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4696
