### ISSUE TITLE
TCC模式怎么通过纯api方式使用呢？

### ISSUE THREAD

**Issue by stevenniu9527** [apache/incubator-seata#4828]
不依赖与spring框架，该如何使用TCC模式？seata-samples-api中只介绍了AT模式，
TCC如何和TM事务绑定呢？

**Comment by a364176773** [comment]
目前无法支持，我们正有计划抽成api模式，变为module:tcc，tcc-spring 这样的做法，tcc-spring作为增强，自动调用tcc模块的api接口，如果你有想法也可在此讨论，也欢迎有相关同学认领该任务

**Comment by stevenniu9527** [comment]
邮件已经收到，我会尽快查看，谢谢

**Comment by stevenniu9527** [comment]
> 目前无法支持，我们正有计划抽成api模式，变为module:tcc，tcc-spring 这样的做法，tcc-spring作为增强，自动调用tcc模块的api接口，如果你有想法也可在此讨论，也欢迎有相关同学认领该任务

请问现在有进展了吗？

**Comment by funky-eyes** [comment]
> > 目前无法支持，我们正有计划抽成api模式，变为module:tcc，tcc-spring 这样的做法，tcc-spring作为增强，自动调用tcc模块的api接口，如果你有想法也可在此讨论，也欢迎有相关同学认领该任务
> 
> 请问现在有进展了吗？

2.0已完成该任务

**Comment by funky-eyes** [comment]
https://seata.apache.org/docs/user/api
