### ISSUE TITLE
seata 1.4.2版，nacos2.0版，集群配置遇到的问题

### ISSUE THREAD

**Issue by lbj812** [apache/incubator-seata#5062]
registry.conf 配置如下：
```config
config {
     type = "nacos"
}
```
nacos中的配置是 store.mode = db模式。
docker启动时，如果遇到网络问题，从nacos拉取不到配置，表现是：在 /root/nacos/ 下没有 config 文件夹。
在这种情况下，seata 会默认启用  type = "file" 配置，seata 进程启动成功。
这样给用户造成的疑惑是，服务确实启动成功了，但是  store.mode = db模式 却无效。
因为启用了  type = "file，docker多实例下做业务会报错如下：
```log
io.seata.core.exception.GlobalTransactionException: 
  Could not found global transaction xid = 192.168.0.82:8091:738914653720850446, may be has finished
```
建议：

既然 config { type = "nacos" } ，那么就必须从nacos拉取成功，才可以正常启动seata服务进程。而不是在拉取失败的时候，启用默认的 type ="file ",如果这样，就失去了 config { type = "nacos" } 的意义。
如果拉取失败，不应该打个日志，而应该抛异常出来阻止进程启动。

**Comment by slievrly** [comment]
@lbj812 look forward a pr to fix the issue.

**Comment by a364176773** [comment]
> @lbj812 look forward a pr to fix the issue.

This is not a simple problem, and requires a discussion of the refactoring of the configuration center logic

**Comment by wwg2017** [comment]
> > @lbj812 look forward a pr to fix the issue.
> 
> This is not a simple problem, and requires a discussion of the refactoring of the configuration center logic

最新版本有这些问题吗

**Comment by leizhiyuan** [comment]
in 2.x branch, Seems this problem no longer exists.

If nacos can not connected , start will fail

<img width="816" alt="image" src="https://github.com/seata/seata/assets/2684384/20729576-8b54-4a7c-9225-5c198191b40b">


<img width="1781" alt="image" src="https://github.com/seata/seata/assets/2684384/ec96c414-13b5-4f67-bb65-e40344dc5f7e">

**Comment by lbj812** [comment]
已解决

**Comment by lbj812** [comment]
已解决

**Comment by lbj812** [comment]
已解决

**Comment by lbj812** [comment]
已解决
