### ISSUE TITLE
seata的at模式，数据源为postgresql的问题

### ISSUE THREAD

**Issue by hualan77** [apache/incubator-seata#5359]
1.使用Seata的at模式开发，seata-server和client均设置数据源为postgresql，且为集群模式的，事物回滚时报错，提示rm client找不到，事物回滚失败，想问下是不支持postgresql的集群模式连接吗？
3.将server和client的数据源设置为postgresql的单机连接地址，日志提示事物回滚失败，但是查看数据库发现数据并未回滚，想问下是什么问题？

**Comment by a364176773** [comment]
详细日志贴上来,确认一下回滚的时候,rm的连接是否已经建立了,如果不是最新版seata,请先做升级

**Comment by hualan77** [comment]
> 详细日志贴上来,确认一下回滚的时候,rm的连接是否已经建立了,如果不是最新版seata,请先做升级

seata是支持postgresql的集群连接吗？我写的连接地址是这样的jdbc:postgresql://host1:port,host2:port,host3:port/链接的数据库名

**Comment by a364176773** [comment]
> > 详细日志贴上来,确认一下回滚的时候,rm的连接是否已经建立了,如果不是最新版seata,请先做升级
> 
> seata是支持postgresql的集群连接吗？我写的连接地址是这样的jdbc:postgresql://host1:port,host2:port,host3:port/链接的数据库名

把日志栈贴上来，映像中这么写在注册资源的时候会有问题，mysql之前有一个loadBalance也是类似你这种写法在1.4.2及之前存在问题，你方便把rm注册连接到tc的日志贴上来给我看一下吗？

**Comment by hualan77** [comment]
今天跟了下代码，发现register(图1）和get（图3）的时候的key不同，所以会回滚的时候会报找不到的错误（图4）；在register的时候对key指进行了处理，如图2进行了逗号分割，不知道这块处理的原因是出于什么考虑？
![9c933afd6e6f609b704975301bc0820](https://user-images.githubusercontent.com/42083346/222712711-0842841f-7291-4f12-88f2-b75ebb25fc97.jpg)
![8f898c690dd62256a4c8e8a3378522a](https://user-images.githubusercontent.com/42083346/222712712-e759f359-5bb9-4648-b0ef-4e5e1e49a49e.jpg)
![7774346fe12070186406bcbd514634b](https://user-images.githubusercontent.com/42083346/222712730-935e8b6d-8feb-49d2-aa9c-e37fce735d7a.jpg)
![28cde0efc1c85f5693a2c237cdb5f02](https://user-images.githubusercontent.com/42083346/222713349-ee4d8a11-0c47-4387-bd77-b59956b99223.jpg)

**Comment by a364176773** [comment]
暂时可以先配置成一个地址吗?会有什么问题不,这个是个bug我们看看如何处理,属于跟之前的mysql loadBalance 为一类问题
