### ISSUE TITLE
ConfigurationCache`s bug

### ISSUE THREAD

**Issue by liuqiufeng** [apache/incubator-seata#5360]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

当调用io.seata.config.ConfigurationCache#removeConfigListener删除listener时，删除所有listener后，还会剩余一个ConfigurationCache作为listener。
<img width="1055" alt="5ad589dc36dad537de4aae323013a9f1" src="https://user-images.githubusercontent.com/20177090/219942866-5633d898-41e1-4f6e-86a1-532d7569c635.png">

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅲ. Describe what you expected to happen

如果不再有其它listener，则应移除ConfigurationCache这个listener

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by a364176773** [comment]
我看了下代码,目前跟理想的发布订阅模式还不太接近建议一起做掉,目前注册的listener会直接注册到对应的配置中心实现中,应该切断耦合变成业务含义的配置listener-> cachelistener->配置中心,配置中心永远跟cache打交道,由cache转发给其它的listener

**Comment by liuqiufeng** [comment]
https://github.com/apache/incubator-seata/pull/6420
