### ISSUE TITLE
ZookeeperRegisterServiceImplTest buildZkTest UT failed

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#5366]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://user-images.githubusercontent.com/8758457/220247422-b7c99690-fbe4-4f95-93c8-5d1e19e18d06.png)
![image](https://user-images.githubusercontent.com/8758457/220247472-534c4d5d-a24d-4f87-a7a6-fb093c2d8bc6.png)
https://github.com/seata/seata/actions/runs/4229244833/jobs/7345446030

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 11
- Seata version:  
- OS :
- Others:

**Comment by Bughue** [comment]
plz assgin to me

**Comment by Bughue** [comment]
目前了解到的情况：

1. 关于NPE：这个看起来是zk源码里不完善导致的，问题发生在server关闭时，代码不严谨。但无论有没有这个异常server都会关掉了
2. 关于server自动关闭：是因为doIO()的时候遇到了IOException （在这里发现是server的state!=running），同样是zk内部的问题，应该是start的时候使用了异步线程，导致state状态更新不及时

关于解决方案

1. 提供足够的时间给server去启动：现在adBeforeClass()里面创建时start=true，后面又start了一下，其实是没有用的，因为CAS会马上返回
2. 用明确的机制去保证server启动没问题：目前没有看到方法可以直接调用以便等待。
3. client捕捉zkexception：遇到异常的时候sleep 1s再重试，降低单测失败率

建议是用方案3，看看大家有没有什么建议

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/pull/5960/files
