### ISSUE TITLE
全局事务成功后，发生回滚

### ISSUE THREAD

**Issue by lbj812** [apache/incubator-seata#5400]
就是 seata1.42版本的时候，外部SAP调用我的接口，我的接口调用一个方法，这个方法上面标注了全局事务。这个接口执行成功了，返回SAP当然也是成功，每次调用都是接口的报文记录，确认无误。
奇怪的是，随后几秒钟之内，整个全局事务回滚了。这种情况发生过几十次了。
SAP方找过我很多次了，我找不到原因
目前已经升级到 1.6.1，会不会发生这种情况，我正在跟踪。或者SAP方也会反馈问题

**Comment by slievrly** [comment]
Identify the problem caused by state consistency in storage computing separation mode.

**Comment by jyak-lang** [comment]
同样的版本，同样的问题。请问升级后问题有解决吗？

**Comment by lbj812** [comment]
> 同样的版本，同样的问题。请问升级后问题有解决吗？

没有解决。这两天真真切切地发生了一次。这是运维人员发现的，没有发现的不知道有没有

**Comment by rola0411** [comment]
+1，请速解决

**Comment by lxgwzx** [comment]
1.5.2发生好多次了，只执行一次查询sql，就进行回滚了，无任何错误
![image](https://user-images.githubusercontent.com/102020403/227867809-bd5882f5-2d19-441c-befe-fb94e4efb3bd.png)
其他sql也是这样，取其中一个

**Comment by lbj812** [comment]
新版本1.7.0以后
