### ISSUE TITLE
support active check of service availability at client startup

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#5484]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
类似dubbo的服务检查,如果没有发现该服务,或者无法与该服务的provider建立连接,将抛出异常阻止应用启动
<dubbo:reference interface="x.x.x.xxxx" check="true" />

![image](https://user-images.githubusercontent.com/19943636/229153660-bb408ae1-6dad-47f8-83c0-1bdd93e0f28f.png)
现在一启动连不上server,也只是打个error日志,无法中断一样启动,特别是rm的连接是异步10s后建立,如果在生产可能会由于配置等问题,造成故障

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

**Comment by sun1341283** [comment]
assign to me plz.
需要做成可配置的还是直接报错

**Comment by a364176773** [comment]
> assign to me plz. 需要做成可配置的还是直接报错

应该是做成一个配置项，如果未true就检查，false就不检查，true的话检查出问题要直接抛异常
