### ISSUE TITLE
Seata1.3版本at模式下 报Oracle数据库无主键

### ISSUE THREAD

**Issue by yili001** [apache/incubator-seata#5626]
seata-spring-boot-starter 版本1.3.0
spring-cloud-starter-alibaba-seata 版本2021.1
异常
io.seata.common.exception.NotSupportYetException xxx-table needs to
contain the primary key.
我看了一下其他人提的issue，不是说在1.2.0版本已经解决了这个问题吗？
而且我检查了一下：id主键存在，id对应的唯一索引也有。
调试源码时发现该索引是唯一索引，但是代码中显示必须为IndexType.PRIMARY才会认为是主键。
麻烦各位给一个排查的思路

**Comment by a364176773** [comment]
先升级看看

**Comment by yili001** [comment]
升级到manven中央仓库里比较新的1.6还是一样的问题，然后调试代码，l.6里判断主键的代码逻辑看起来是一样的

**Comment by a364176773** [comment]
可能是你的driver有问题,尝试升级一下

**Comment by yili001** [comment]
在升级到最新的oracle jdbc，seata-spring-boot-starter，spring-cloud-starter-alibaba-seata后，主键找不到的问题已经解决了
