### ISSUE TITLE
Added docker image dependency installation extension

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#5654]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

Added docker image dependency installation extension

At present, docker image uses a very simple jdk basic image, which lacks basic operation and maintenance tools. I would like to see extensions like yum/brew/apt-get install supported when the image is packaged with jib to build your own image based on the source code.

---

增加docker镜像的依赖扩展
目前docker镜像采用了极其简单的jdk基础镜像，在镜像中缺乏基本的运维工具。我希望镜像通过jib打包时支持安装的扩展类似yum/brew/apt-get install 方便基于源码构建适合自己的镜像。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by xingfudeshi** [comment]
All of our current images are built based on the Eclipse Temurin JDK. Eclipse Temurin is implemented on the basis of Ubuntu. Therefore, the apt command is already supported.
<img width="671" alt="image" src="https://github.com/user-attachments/assets/a57e8f91-899f-43d9-b9d3-d5b4bd0eb488" />
