### ISSUE TITLE
The JVM parameter -Dapp.pid is displayed incorrectly

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#5692]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

The JVM parameter -Dap.pid is displayed incorrectly

![image](https://github.com/seata/seata/assets/8758457/cc7dba3e-76ad-4c67-a66d-2e0d201d93b9)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

```
sh seata-server.sh
```

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by jonasHanhan** [comment]
Whether the pid value needs to be dynamically specified in the startup script？
