### ISSUE TITLE
Suggest: DB acquireLock optimize

### ISSUE THREAD

**Issue by wt-better** [apache/incubator-seata#5992]
## Why you need it?

`io.seata.server.storage.db.lock.DataBaseDistributedLocker#acquireLock` 需要兼容dupKey异常。

![image](https://github.com/seata/seata/assets/26296600/0c2c3d4d-dc89-4958-91dc-1449a96ccdb2)

线程1和线程2，select key都没查到记录，执行了insert，顺序如上，线程2 insert会报dupKey异常，需要兼容该异常，此种情况下直接返回获取锁失败。

###II. Environment:

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:  2.x

**Comment by funky-eyes** [comment]
本地锁没有释放，不可能出现并发竞争同一个锁
The local lock is not released. It is impossible to compete with the global lock concurrently.

**Comment by wt-better** [comment]
`io.seata.server.session.SessionHolder#distributedLockAndExecute` TC多节点部署的时候，init启动时获取xxx key的分布式锁时会产生这种情况。

**Comment by funky-eyes** [comment]
I misunderstood, but these 4 locks should be inserted when the table is built, not at startup. And it's not a feature, it's an optimization

**Comment by funky-eyes** [comment]
https://github.com/seata/seata/blob/2.x/script/server/db/mysql.sql

**Comment by wt-better** [comment]
assign to me

**Comment by wt-better** [comment]
this was catch `SQLException`, has no problem
