### ISSUE TITLE
protobuf add support for BatchResultMessage

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6000]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
https://github.com/seata/seata/blob/2.x/core/src/main/java/io/seata/core/protocol/BatchResultMessage.java  This request class has been added since 1.5, and so far there is no support for it on protobuf

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by ggbocoder** [comment]
Assign to me please.
