### ISSUE TITLE
seata undo_log没有数据 global_table是有数据(求救帖🆘)

### ISSUE THREAD

**Issue by guanfu1213dad** [apache/incubator-seata#6008]
版本：
		<dependency>
			<groupId>io.seata</groupId>
			<artifactId>seata-spring-boot-starter</artifactId>
			<version>1.5.1</version>
		</dependency>

spring boot 1.5.8
JDK 8

服务a
<img width="1137" alt="image" src="https://github.com/seata/seata/assets/149680891/3b93cc77-6c8c-4222-b8de-18b794b5025d">

服务b
<img width="1180" alt="image" src="https://github.com/seata/seata/assets/149680891/8ed53e32-5013-42b5-b1cc-2bb424a48e08">

server端日志
<img width="1426" alt="image" src="https://github.com/seata/seata/assets/149680891/a8f27737-c459-49d1-b2a1-d353c2b6d4ca">

enable-auto-data-source-proxy: 设置true和false都不好使

**Comment by guanfu1213dad** [comment]
@funky-eyes 老哥，有时间帮帮忙吗

**Comment by leizhiyuan** [comment]
see https://github.com/seata/seata/issues/5989#issuecomment-1791962030

**Comment by guanfu1213dad** [comment]
服务a的配置：
# seata的配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: common-seata-service-group # 保持一致
  enable-auto-data-source-proxy: true
  service:
    vgroupMapping:
      common-seata-service-group: seata-server # 保持一致
  registry:
    type: eureka
    eureka:
      weight: 1
      service-url: http://localhost:8761/eureka
------------------------------------------------------------------------------
服务b的配置：
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: common-seata-service-group # 保持一致
  enable-auto-data-source-proxy: true
  service:
    vgroupMapping:
      common-seata-service-group: seata-server # 保持一致
  registry:
    type: eureka
    eureka:
      weight: 1
      service-url: http://localhost:8761/eureka

**Comment by funky-eyes** [comment]
根据你的日志来看，你的数据源没有正确被代理，或者说被代理后没有被你的事务框架所使用，导致无法加入全局事务，请检查你的代码，使datasourceproxy正确被事务管理器所使用
According to your logs, your datasource is not being proxied correctly, or it is not being used by your transaction framework after being proxied, resulting in the inability to join a global transaction, please check your code so that the datasourceproxy is being used correctly by the transaction manager

**Comment by funky-eyes** [comment]
你的回滚日志中只有全局事务，而没有分支事务，很明显是数据源代理出现了问题或错误的使用
Your rollback log has only global transactions and no branching transactions, so it's obvious that there's a problem with the data source agent or a misuse of the

**Comment by guanfu1213dad** [comment]
> 你的回滚日志中只有全局事务，而没有分支事务，很明显是数据源代理出现了问题或错误的使用 Your rollback log has only global transactions and no branching transactions, so it's obvious that there's a problem with the data source agent or a misuse of the

谢谢老哥，我看下

**Comment by guanfu1213dad** [comment]
> 你的回滚日志中只有全局事务，而没有分支事务，很明显是数据源代理出现了问题或错误的使用 Your rollback log has only global transactions and no branching transactions, so it's obvious that there's a problem with the data source agent or a misuse of the

<img width="1424" alt="image" src="https://github.com/seata/seata/assets/149680891/cc72c6e4-cbd2-4597-8742-6c3331e45583">
大佬，我看这个日志，两个服务seata都已经代理了，使用的是自己配置的方式
<img width="749" alt="image" src="https://github.com/seata/seata/assets/149680891/d91d4114-29c2-4161-b156-09f6543a78bb">
undo_log 还是没有数据

**Comment by funky-eyes** [comment]
不要怀疑，你那个只是数据源代理的注册一个通信用的channel，而不是分支注册测试。你这个bean自行debug到底有没有被其他的事务管理器，sessionfactory之类的地方用到
Don't doubt that you're just registering a channel for communication with the data source broker, not a branch for the test. Is your bean debugging used by other transaction manager, sessionfactory?

**Comment by guanfu1213dad** [comment]
> 不要怀疑，你那个只是数据源代理的注册一个通信用的channel，而不是分支注册测试。你这个bean自行debug到底有没有被其他的事务管理器，sessionfactory之类的地方用到 Don't doubt that you're just registering a channel for communication with the data source broker, not a branch for the test. Is your bean debugging used by other transaction manager, sessionfactory?

谢谢大佬，是项目框架数据源代理的问题，现在使用TCC模式了，再次感谢大佬
