### ISSUE TITLE
Add secure authentication to interfaces in ClusterController

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6012]
## Why you need it?

将`seata.security.ignore`中的`/metadata/v1/**`去除，并且将`seata-discovery-raft`模块增加权限认证能力，使获取raft元数据时先认证后再请求相关接口，如果客户端没有配置相关`username`，`password`，视为用户自行去除了该接口的认证，可直接请求相关接口，如果再此之后出现401，要提示用户配置相关的用户名密码参数

Remove `/metadata/v1/** `from `seata.security.ignore`, and increase the privilege authentication capability of `seata-discovery-raft module`, so that when obtaining the raft metadata, first authenticate before requesting the relevant interface, if the client is not configured with the relevant username and password, it is considered that the user has removed the authentication of the interface by himself. If the client does not configure the username and password, it will be regarded as the user removing the authentication of the interface, and can directly request the relevant interface. If there is a 401 after this, the user should be prompted to configure the relevant `username` and `password` parameters.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by ggbocoder** [comment]
assign  to me plz

**Comment by Bughue** [comment]
关注一下~ 有没有raft相关的任务来一个~
