### ISSUE TITLE
can't integrated dubbo with spring in new seata version

### ISSUE THREAD

**Issue by xxxcrel** [apache/incubator-seata#6014]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://github.com/seata/seata/assets/37683647/58588773-37d5-42ef-b539-16e98110de93)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:  2.0.0-SNAPSHOT
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by xxxcrel** [comment]
it works in version 1.x.x

**Comment by xxxcrel** [comment]
I noticed version 2. x seems to be decoupling from spring, but it seems there's a bug in processing FactoryBean
<img width="810" alt="image" src="https://github.com/seata/seata/assets/37683647/fdd83b8e-12a8-43ba-897e-eba8fb87e02c">
The RemotingFactoryBeanParser is loaded by ExtensionLoader, but applicationContext not initialized properly

**Comment by funky-eyes** [comment]
Hi @xxxcrel I sent an email to your gamil welcoming you to the seata community, looking forward to hearing from you!
