### ISSUE TITLE
[Optimize] add a check for the existence of the undolog table

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6022]
## Why you need it?
When proxying the datasourceProxy, a check is performed to see if the undolog table exists. If it doesn't exist, an exception is thrown as a prompt. Remember to add a check switch, as it's possible that a user may only use the TCC mode but inadvertently enable the check switch.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by laywin** [comment]
i can have a try, thanks!

**Comment by leizhiyuan** [comment]
> i can have a try, thanks!

assign this issue to you , have fun

**Comment by laywin** [comment]
i had looked at the case, may be there needn't a switch, because AT mode should fast fail if the table not exist and other model don't do the check.   Additionally, in RMHandlerAT, when receive UndoLogDelete Request, there is a operation about check undolog table exist, may be it can be removed. @funky-eyes

**Comment by funky-eyes** [comment]
> i had looked at the case, may be there needn't a switch, because AT mode should fast fail if the table not exist and other model don't do the check. Additionally, in RMHandlerAT, when receive UndoLogDelete Request, there is a operation about check undolog table exist, may be it can be removed. @funky-eyes

You can submit a pr and we will communicate further about your implementation code.

**Comment by funky-eyes** [comment]
@laywin I have sent you my contact information to your email address laywin@yeah.net. Please check your email.
