### ISSUE TITLE
Cannot gracefully shut down the server

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6039]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
虽然我们有了注册中心，server下线时会先从注册中心摘除自己，但是client侧自己对注册中心的列表做了10s一次的探活，导致10s后，这个列表中下线的地址才被摘除，加上server 摘除后只等待了3秒就开始关闭各种资源，客户端很有可能再这个时候连接还可用，进行请求，导致失败。
Although we have a registry center and the server is removed from it before going offline, the client side independently probes the registry center's list every 10 seconds. As a result, it takes 10 seconds for the address of the offline server to be removed from the list. Additionally, after the server is removed, it only waits for 3 seconds before starting to shut down various resources. It is highly likely that at this time the client's connection is still available, resulting in a failure of the request.
![image](https://github.com/seata/seata/assets/19943636/beee7a5c-57c6-4265-82e6-92643008a916)
![image](https://github.com/seata/seata/assets/19943636/4e4c42db-44d4-4432-809a-69b0ed541b3b)
![image](https://github.com/seata/seata/assets/19943636/c87140b0-977d-4964-9657-3729ce85aa6d)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by Bughue** [comment]
plz assgin to me

**Comment by funky-eyes** [comment]
我有2个想法
1.是在具体的注册中心扩展实现中，拿到CURRENT_ADDRESS_MAP中对应的事务分组缓存的可用列表，去进行对该list匹配到下线的节点进行摘除
2.将server默认的sleep时间扩大到13及以上，保证client已经通过10s一次的可用列表探活，去除已经在注册中心下线的节点

I have 2 ideas:
In the specific extension implementation of the registry center, retrieve the available list of transaction group caches corresponding to CURRENT_ADDRESS_MAP and remove the nodes identified as offline from that list.
Increase the default sleep time of the server to 13 seconds or more to ensure that clients have already probed the available list every 10 seconds, removing nodes that have already been taken offline from the registry center.

**Comment by laywin** [comment]
我觉得主要是两方面
1. TM/RM 不能请求到正在下线的 TC
2. 正在下线的 TC 需要处理完在途请求

这方面seata处理的确实简陋一点，似乎利用注册中心的watcher机制在TM/RM端下线TC更优雅一点?

**Comment by funky-eyes** [comment]
> 我觉得主要是两方面
> 
> 1. TM/RM 不能请求到正在下线的 TC
> 2. 正在下线的 TC 需要处理完在途请求
> 
> 这方面seata处理的确实简陋一点，似乎利用注册中心的watcher机制在TM/RM端下线TC更优雅一点?

在1.5.2之前是通过注册中心的watch机制下线的,但是在之后考虑到注册中心的地址不一定可信(比如server与注册中心网络通,但是跟client不通),所以在注册中心的地址之上做了一层探活,这个探活是每10秒从缓存中读取最新的地址(这个地址通过watch其实实时保存在内存中了),进行再次探测,所以导致了tc下线的时候无法被实时删除.
Before version 1.5.2, services were taken offline through the watch mechanism in the registry. However, later on, it was realized that the address of the registry might not always be reliable (for example, the server is connected to the registry but not to the client). To address this issue, an additional layer of health checking was implemented above the registry address. This health checking involves retrieving the latest address from the cache every 10 seconds (which is actually saved in memory in real time through watching) and performing a secondary check. As a result, when the service goes offline, it cannot be immediately deleted because of this secondary check.

**Comment by xingfudeshi** [comment]
> plz assgin to me

I have already assigned it to you. Looking forward to your PR.

**Comment by xingfudeshi** [comment]
@Bughue

**Comment by Bughue** [comment]
想先讨论下：感觉有必要在服务端感知到关闭命令后主动通知一下客户端？
其他思路梳理中（完整后再发出
