### ISSUE TITLE
Does the client support yml configuration and no longer use file. conf or registry. conf

### ISSUE THREAD

**Issue by pdxgg** [apache/incubator-seata#6040]
Does the client support yml configuration and no longer use file. conf or registry. conf？
Because the account password for entering the Pro environment db database for the project cannot be provided in clear text, there is currently no configuration center available ？

客户端是否支持yml配置，不再使用file.conf或 registry.conf ?

因为项目进入Pro环境 db数据库的账号密码不能明文提供，暂时没配置中心

**Comment by funky-eyes** [comment]
https://github.com/seata/seata/tree/2.x/script/client
https://github.com/seata/seata/pull/2667
