### ISSUE TITLE
BranchSessionExecuteTest UT failed

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#6046]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://github.com/seata/seata/assets/8758457/154d5fcd-0611-4c7b-8bea-9498e1662894)
https://github.com/seata/seata/actions/runs/6901645188/job/18776821804?pr=6045

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by ptyin** [comment]
Seems this error is raised by RocksDB when the test tried to set up raft server:

<img width="757" alt="image" src="https://github.com/seata/seata/assets/32592585/8d223da8-8f85-4ed9-bcf0-dea1fc23e42a">

I will dig into ther reason of it.

**Comment by ptyin** [comment]
It occurs because the shutdown procedure of `RaftServer` calls `RaftGroupService::shutdown`. However, `RaftGroupService::shutdown` is an asynchronized procedure, which causes all test cases related to raft fault-prone.
