### ISSUE TITLE
使用k8s运行1.8.0版本的配置文件无法生效，哪怕通过覆盖镜像中的配置也无法生效。

### ISSUE THREAD

**Issue by goudai** [apache/incubator-seata#6065]
使用k8s运行1.8.0版本的配置文件无法生效，哪怕通过覆盖镜像中的配置也无法生效。

比较费劲一个简单的springboot项目，为什么标准配置文件不能正常生效。我下载源码修改application.yml 文件然后使用jib插件打包为docker镜像，然后发布到k8s中，神奇的问题来了，nacos配置就是不生效，why？

**Comment by funky-eyes** [comment]
自己进容器看一下到底配置有没有打进去,是否真的在对应的目录,如果你确定有,请截图证明
You go into the container to see if the configuration has been typed in, whether it is really in the corresponding directory, if you are sure, please take a screenshot to prove that
