### ISSUE TITLE
seata 2.0.0 docker部署集群，store.mode选择为redis的时候，页面全局事务锁出现异常

### ISSUE THREAD

**Issue by xigexb** [apache/incubator-seata#6073]
点击ui中的全局事务锁
only three parameters of tableName,pk,resourceId or Xid are supported

**Comment by funky-eyes** [comment]
only three parameters of tableName,pk,resourceId or Xid are supported
只支持tableName、pk、resourceId或Xid三个参数，redis模式受数据结构不同，无法支持那么全面的参数

**Comment by xigexb** [comment]
好的
