### ISSUE TITLE
求助，按照demo测试，发现使用seata性能降低很多

### ISSUE THREAD

**Issue by qiaolun2019** [apache/incubator-seata#6093]
![1129-3](https://github.com/seata/seata/assets/46710158/16fda0d5-00c8-426b-8e0b-e3377dec1698)
按照网上的这个demo，用jmeter测试了一下。
有GlobalTransactional注解的吞吐量只能没有注解的20%
![1129](https://github.com/seata/seata/assets/46710158/d97a87b6-2625-4f43-82e2-d227b1bd688b)
![1129-2](https://github.com/seata/seata/assets/46710158/b281fe3a-5c9a-40cf-afa4-567df5f5bac7)
这个正常么？

**Comment by funky-eyes** [comment]
What is your cluster build mode? What is the latency of your client to the seata-server and what is the latency of the seata-server to its storage?
你的集群搭建模式是什么？你的client与seata-server的延迟是多少？seata-server与它的存储器的延迟是多少？

**Comment by qiaolun2019** [comment]
> What is your cluster build mode? What is the latency of your client to the seata-server and what is the latency of the seata-server to its storage? 你的集群搭建模式是什么？你的client与seata-server的延迟是多少？seata-server与它的存储器的延迟是多少？

我发现我慢的地方了，我查询了stock，然后减去扣除的count后set进去。如果我去掉这一步，那么他的性能几乎是没有影响
![1130](https://github.com/seata/seata/assets/46710158/31e7ffaa-520b-4af6-8100-2ed71e73e2a5)

**Comment by funky-eyes** [comment]
What if you wrote my sql below, instead of querying first and then updating?
`update stock set count=count-2 where id=? and count>=?`
I suspect that thinking that your content didn't change, the number of lines affected was 0 and was ignored by seata. One version of seata is handled as shown in the following code, please let me know the version of seata you are using
```
    protected T executeAutoCommitFalse(Object[] args) throws Exception {
        if (!JdbcConstants.MYSQL.equalsIgnoreCase(getDbType()) && isMultiPk()) {
            throw new NotSupportYetException("multi pk only support mysql!");
        }
        TableRecords beforeImage = beforeImage();
        T result = statementCallback.execute(statementProxy.getTargetStatement(), args);
        int updateCount = statementProxy.getUpdateCount();
        if (updateCount > 0) {
            TableRecords afterImage = afterImage(beforeImage);
            prepareUndoLog(beforeImage, afterImage);
        }
        return result;
    }
```

**Comment by slievrly** [comment]
> > What is your cluster build mode? What is the latency of your client to the seata-server and what is the latency of the seata-server to its storage? 你的集群搭建模式是什么？你的client与seata-server的延迟是多少？seata-server与它的存储器的延迟是多少？
> 
> 我发现我慢的地方了，我查询了stock，然后减去扣除的count后set进去。如果我去掉这一步，那么他的性能几乎是没有影响 ![1130](https://private-user-images.githubusercontent.com/46710158/286841928-31e7ffaa-520b-4af6-8100-2ed71e73e2a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTcyMTAsIm5iZiI6MTcwMTM5NjkxMCwicGF0aCI6Ii80NjcxMDE1OC8yODY4NDE5MjgtMzFlN2ZmYWEtNTIwYi00YWY2LTgxMDAtMmVkNzFlNzNlMmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAyMTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YmE2YWU2ZWIzN2FkZjhkMGYyM2U4NWM2Nzk2NGYxNzZmOWUyMDJjODAxMDUwOTJlMTliOGYyYTBlYzY5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WihQPDNU9qfuHA0SgKpFaowhduqAkVQ_y-yjOhe12l0)

Just changing the `SetCount` operation? I understand that this is just a memory operation.

**Comment by qiaolun2019** [comment]
> What if you wrote my sql below, instead of querying first and then updating? `update stock set count=count-2 where id=? and count>=?` I suspect that thinking that your content didn't change, the number of lines affected was 0 and was ignored by seata. One version of seata is handled as shown in the following code, please let me know the version of seata you are using
> 
> ```
>     protected T executeAutoCommitFalse(Object[] args) throws Exception {
>         if (!JdbcConstants.MYSQL.equalsIgnoreCase(getDbType()) && isMultiPk()) {
>             throw new NotSupportYetException("multi pk only support mysql!");
>         }
>         TableRecords beforeImage = beforeImage();
>         T result = statementCallback.execute(statementProxy.getTargetStatement(), args);
>         int updateCount = statementProxy.getUpdateCount();
>         if (updateCount > 0) {
>             TableRecords afterImage = afterImage(beforeImage);
>             prepareUndoLog(beforeImage, afterImage);
>         }
>         return result;
>     }
> ```

You are right, I found no data recorded in the undo log.The sql was ignored by seata.The version of seata I use is 2.0.0.

My seata-server configuration is the default,the storage mode,config type and registry mode of my seata-server is file.
Data source proxy mode is AT.In fact, I only start the example of spring-jpa-seata, and a seata-server, and did not change.....
How do I check the latency between my client and seata-server?

**Comment by a870368162** [comment]
> > 您的集群构建模式是什么？您的客户端到seata-server的延迟是多少，seata-server到其存储的延迟是多少？你的集群搭建模式是什么？你的client与seata-server的延迟是多少？seata-server与它的存储器的延迟是多少？
> 
> 我发现我慢的地方了，我查询了stock，然后减去扣除的count后set进去。如果我去掉这一步，那么他的性能几乎是没有影响 ![1130](https://private-user-images.githubusercontent.com/46710158/286841928-31e7ffaa-520b-4af6-8100-2ed71e73e2a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzA0MjksIm5iZiI6MTcwMTc3MDEyOSwicGF0aCI6Ii80NjcxMDE1OC8yODY4NDE5MjgtMzFlN2ZmYWEtNTIwYi00YWY2LTgxMDAtMmVkNzFlNzNlMmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5NTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmN2Q1YjJjMTY2ZjU0M2U1YzkwMzJlMjA3OWJjNjZkZWFmNGE4MTczNDE3NzM1OWM0ZDNlNTgzY2VkNThmNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R1FzzIcIGDNli7VedmKhUw70XS_PjxSiVSM2MyYseZ8)

The slow part should not be here, as this is just a memory operation and theoretically should not have any performance overhead. It would be helpful if you could upload your demo to git, as it will be easier to analyze the reasons.

**Comment by funky-eyes** [comment]
> > What if you wrote my sql below, instead of querying first and then updating? `update stock set count=count-2 where id=? and count>=?` I suspect that thinking that your content didn't change, the number of lines affected was 0 and was ignored by seata. One version of seata is handled as shown in the following code, please let me know the version of seata you are using
> > ```
> >     protected T executeAutoCommitFalse(Object[] args) throws Exception {
> >         if (!JdbcConstants.MYSQL.equalsIgnoreCase(getDbType()) && isMultiPk()) {
> >             throw new NotSupportYetException("multi pk only support mysql!");
> >         }
> >         TableRecords beforeImage = beforeImage();
> >         T result = statementCallback.execute(statementProxy.getTargetStatement(), args);
> >         int updateCount = statementProxy.getUpdateCount();
> >         if (updateCount > 0) {
> >             TableRecords afterImage = afterImage(beforeImage);
> >             prepareUndoLog(beforeImage, afterImage);
> >         }
> >         return result;
> >     }
> > ```
> 
> You are right, I found no data recorded in the undo log.The sql was ignored by seata.The version of seata I use is 2.0.0.
> 
> My seata-server configuration is the default,the storage mode,config type and registry mode of my seata-server is file. Data source proxy mode is AT.In fact, I only start the example of spring-jpa-seata, and a seata-server, and did not change..... How do I check the latency between my client and seata-server?

https://seata.io/zh-cn/docs/overview/faq#42 This troubleshooting will also help you solve the problem

**Comment by qiaolun2019** [comment]
> > > What if you wrote my sql below, instead of querying first and then updating? `update stock set count=count-2 where id=? and count>=?` I suspect that thinking that your content didn't change, the number of lines affected was 0 and was ignored by seata. One version of seata is handled as shown in the following code, please let me know the version of seata you are using
> > > ```
> > >     protected T executeAutoCommitFalse(Object[] args) throws Exception {
> > >         if (!JdbcConstants.MYSQL.equalsIgnoreCase(getDbType()) && isMultiPk()) {
> > >             throw new NotSupportYetException("multi pk only support mysql!");
> > >         }
> > >         TableRecords beforeImage = beforeImage();
> > >         T result = statementCallback.execute(statementProxy.getTargetStatement(), args);
> > >         int updateCount = statementProxy.getUpdateCount();
> > >         if (updateCount > 0) {
> > >             TableRecords afterImage = afterImage(beforeImage);
> > >             prepareUndoLog(beforeImage, afterImage);
> > >         }
> > >         return result;
> > >     }
> > > ```
> > 
> > 
> > You are right, I found no data recorded in the undo log.The sql was ignored by seata.The version of seata I use is 2.0.0.
> > My seata-server configuration is the default,the storage mode,config type and registry mode of my seata-server is file. Data source proxy mode is AT.In fact, I only start the example of spring-jpa-seata, and a seata-server, and did not change..... How do I check the latency between my client and seata-server?
> 
> https://seata.io/zh-cn/docs/overview/faq#42 This troubleshooting will also help you solve the problem

That doesn't solve my problem,I tested according to the examples in the seata-sample and got such results
![127-1](https://github.com/seata/seata/assets/46710158/b3a203a5-683d-4f26-8d7e-3bbbc58a214e)
![127-2](https://github.com/seata/seata/assets/46710158/7ed4f0c2-8b58-4450-9507-8b6ab2421fd7)
![127-3](https://github.com/seata/seata/assets/46710158/7b6b11e5-062f-48f1-862f-6700c20654b8)
![127-4](https://github.com/seata/seata/assets/46710158/c3d39242-d13e-4aec-b704-3336652e3383)


The throughput without globaltransaction annotation is 12 times higher than with annotations.There are also some errors when adding annotation.
![127-5](https://github.com/seata/seata/assets/46710158/8d8f97cf-bc88-4737-bd64-edb301cce558)


I used the following code for the test.
https://github.com/seata/seata-samples/tree/master/seata-spring-boot-starter-samples
