### ISSUE TITLE
When all Raft nodes are offline, it will retry indefinitely after the maximum metadata delay is reached.

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6097]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://github.com/seata/seata/assets/19943636/d6e81af2-1c8b-4032-9d46-a39563964e44)
![image](https://github.com/seata/seata/assets/19943636/ef3acfb7-fdb6-4c3d-ae47-8c697f271974)
metadataMaxAgeMs默认为30s，当所有节点不可用超过30s后，会因为metadataMaxAgeMs超时，导致无限重试获取元数据，而不会进行sleep 一秒来等待。要求统一watch和acquireClusterMetaData，统一在while(true)中进行对可重试的异常进行等待重试
The default value of metadataMaxAgeMs is 30 seconds. When all nodes become unavailable for over 30 seconds, an infinite retry loop will be triggered for metadata retrieval due to the metadataMaxAgeMs timeout, without waiting for a one-second sleep. It is required to unify the handling of retryable exceptions for both watch and acquireClusterMetaData within a while(true) loop for waiting and retrying.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by ggbocoder** [comment]
assign to me plz
