### ISSUE TITLE
Help: How to register seata into nacos

### ISSUE THREAD

**Issue by yuluo-yx** [apache/incubator-seata#6106]
Hello, community member, please tell me how to start the latest version of seata with nacos as the registration center. I referred to the method on the Internet, but it was not successful.

Any Idea?

**Comment by yuluo-yx** [comment]
https://seata.io/zh-cn/blog/seata-nacos-analysis.html
I found this article, but it is out of date. After following the instructions, seata failed to start.

**Comment by ptyin** [comment]
Seata Server with version greater than 1.5 uses application.yml to replace [registry, config].conf file. If you are looking for nacos registry configuration example in application.yml, you can refer to this document [使用 docker-compose 部署 Seata Server](https://seata.io/zh-cn/docs/ops/deploy-by-docker-compose/#nacos-db).

**Comment by yuluo-yx** [comment]
> Seata Server with version greater than 1.5 uses application.yml to replace [registry, config].conf file. If you are looking for nacos registry configuration example in application.yml, you can refer to this document [使用 docker-compose 部署 Seata Server](https://seata.io/zh-cn/docs/ops/deploy-by-docker-compose/#nacos-db).

tks, it solved my problem.
