### ISSUE TITLE
kubectl logs -f 该命令能够查到seata启动日志，这样才能快速定位问题

### ISSUE THREAD

**Issue by PeppaO** [apache/incubator-seata#6117]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

kubectl logs -f 该命令能够查到seata启动日志，这样快速定位问题

目前方案：
1. daemon参数控制台后台还是前台
2. 控制台只输出启动日志，业务日志不输出

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by PeppaO** [comment]
optimize

**Comment by leizhiyuan** [comment]
closed as completed https://github.com/apache/incubator-seata/pull/6154
