### ISSUE TITLE
seata 1.6.1环境下 二阶段回滚失败为什么lock _table ,branch_table 和global_table数据没有清除

### ISSUE THREAD

**Issue by 1094585378** [apache/incubator-seata#6141]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
失败了当然不会清空,清空了你数据如何回溯,如何人工介入或者靠重试恢复?
Failure of course not empty, empty your data how to go back, how to manually intervene or by retrying to recover?
