### ISSUE TITLE
seata2.0.0疑似SEATA_IP环境变量失效

### ISSUE THREAD

**Issue by faruzanCN** [apache/incubator-seata#6150]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

使用docker部署seata-server2.0.0注册到nacos（2.2.3）时，为了注册到nacos的地址不是docker地址，所以使用SEATA_IP作为环境变量，但是在使用时无效（seata-server1.7.2有效）
### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
以下分别是seata-server2.0所在docker环境变量和nacos的截图

![QQ截图20231214091114](https://github.com/seata/seata/assets/46319425/71cd49e7-5dd3-43be-b33f-a7df1260115d)
![image](https://github.com/seata/seata/assets/46319425/d2e33e6c-49a9-4006-9c6b-6997e4bf8d76)

**Comment by faruzanCN** [comment]
SEATA_PORT是有效的

**Comment by xingfudeshi** [comment]
Which image tag are you using?
https://hub.docker.com/r/seataio/seata-server/tags

**Comment by xingfudeshi** [comment]
I used the 2.0.0 image for testing, but both the IP and port can be registered to Nacos as expect.
<img width="709" alt="image" src="https://github.com/seata/seata/assets/24457941/2148f33b-7794-4f6e-8320-ff96674680cc">
<img width="1392" alt="image" src="https://github.com/seata/seata/assets/24457941/ce620769-5487-4e31-add5-cdcaacf87793">

**Comment by faruzanCN** [comment]
> Which image tag are you using? https://hub.docker.com/r/seataio/seata-server/tags

sorry,my problem. Mirror agent error. Thank you for your correction
