### ISSUE TITLE
issue of registry offline server address

### ISSUE THREAD

**Issue by laywin** [apache/incubator-seata#6161]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

之前在看注册中心服务下线的时候，发现了  consul, eureka, nacos 在收到服务下线通知后，并不会在应用侧把节点摘除掉， 确认一下哈.
consul, eureka, nacos did not remove nodes on the application side after receiving the service offline notification

nacos:
<img width="1040" alt="image" src="https://github.com/seata/seata/assets/22276474/282a408d-e259-4a66-9d34-e20bf2b36140">

eureka:
<img width="1014" alt="image" src="https://github.com/seata/seata/assets/22276474/3ccae54a-245e-458b-b192-cbed02867c54">

consul:
<img width="1062" alt="image" src="https://github.com/seata/seata/assets/22276474/3ff720ea-54ff-45a4-9891-8540c8d92625">

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
This is the push-empty protection mechanism for the service. You need to understand why this is done. If the list of services pushed is empty or the list of services remains unchanged but the services are offline, there is no functional distinction. However, the push-empty protection is to prevent service disruptions in the event of network jitter, temporary disconnection of the service list, and other abnormal conditions. Push-empty protection falls under the category of service governance.

**Comment by laywin** [comment]
> This is the push-empty protection mechanism for the service. You need to understand why this is done. If the list of services pushed is empty or the list of services remains unchanged but the services are offline, there is no functional distinction. However, the push-empty protection is to prevent service disruptions in the event of network jitter, temporary disconnection of the service list, and other abnormal conditions. Push-empty protection falls under the category of service governance.

thanks, get it, i think this is the point : "If the list of services pushed is empty or the list of services remains unchanged but the services are offline, there is no functional distinction".  at the same time,  it can  prevent service disruptions in the event of network jitter
