### ISSUE TITLE
seata注册到nacos上，怎么将注册的IP改成127.0.0.1呢，docker下尝试多次也不行，本机运行seata-server.bat -h 127.0.0.1 也不行，修改机器的IP后非得手动重启服务嘛？

### ISSUE THREAD

**Issue by baiguoz** [apache/incubator-seata#6170]
![image](https://github.com/seata/seata/assets/26618272/41413c4b-7bae-4e85-a872-c12c70176ad0)

**Comment by funky-eyes** [comment]
https://seata.io/zh-cn/docs/ops/deploy-by-docker

**Comment by slievrly** [comment]
@baiguoz 127.0.0.1 and 0.0.0.0 are not valid address.

**Comment by baiguoz** [comment]
> https://seata.io/zh-cn/docs/ops/deploy-by-docker

官网我找了也没有，SEATA_IP 参数也不生效

**Comment by baiguoz** [comment]
> @baiguoz 127.0.0.1 and 0.0.0.0 are not valid address.
如果不支持127.0.0.1，那我每次变更服务器IP，还需要手动重启seata，就不考虑多个微服务部署在同一台服务器的场景吗？
