### ISSUE TITLE
seata 2.0.0 oracle 19C XA mode  always rollback

### ISSUE THREAD

**Issue by lyon-liang** [apache/incubator-seata#6171]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://github.com/seata/seata/assets/35824397/f99b2f05-4275-4edf-af68-daf2db81f76e)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:  2.0.0
- Database version: oracle 19c
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
事务回滚不回滚，取决于你的tm侧有没有发生异常，或者事务有没有达到超时时间，如果有异常请附上详细的异常信息
Transaction rollback does not rollback, depending on whether there is an exception on your tm side, or whether the transaction has reached the timeout time. If there is an exception, please attach detailed exception information.
