### ISSUE TITLE
Are there plans to offer rust client

### ISSUE THREAD

**Issue by nowethan** [apache/incubator-seata#6172]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
请问针对这个需求，你们有实际的应用场景吗？
Do you have any practical application scenarios for this requirement?

**Comment by nowethan** [comment]
我们正使用axum+sea-orm 进行Web开发，正在寻找分布式事务中间件，之前使用springcloud+dubbo+seata 进行过分布式事务的处理，现在想在rust上寻找相同的解决方案，nacos 和dubbo 已提供了相应的rust client端，seata官方sdk列表中并为提供关于rust语言的client,不知是否有计划。
We are using axum+sea-orm for Web development, looking for distributed transaction middleware, having previously used springcloud+dubbo+seata for distributed transaction processing, and now looking for the same solution in rust. nacos and dubbo have provided corresponding rust client, and seata's official sdk list does not provide a client for rust language, I do not know if there are plans.

**Comment by slievrly** [comment]
Currently, there is a shortage of Rust developers in the community.
