### ISSUE TITLE
Modify the runtime memory size of Seata？

### ISSUE THREAD

**Issue by jhx1024** [apache/incubator-seata#6175]
seata1.7 使用sh seata-server.sh脚本启动时，启动失败，根据日志信息得出原因时因为运行内存不足？默认时2048，如何将运行内存调小？

When using the sh seata server.sh script to start seata1.7, the startup failed. Based on the log information, it can be concluded that the reason is due to insufficient running memory? By default, 2048. How can I reduce the running memory?

**Comment by leizhiyuan** [comment]
When starting, first set the environment variables.
启动的时候，先设置一下环境变量。

```
JVM_XMX=1024m
JVM_XMS=512m
```

default is 2048
```
JAVA_OPT="${JAVA_OPT} -Dlog.home=${LOG_HOME} -server -Dloader.path=${LOADER_PATH:="$BASEDIR/lib"} -Xmx${JVM_XMX:="2048m"} -Xms${JVM_XMS:="2048m"} -Xss${JVM_XSS:="640k"} -XX:SurvivorRatio=10 -XX:MetaspaceSize=${JVM_MetaspaceSize:="128m"} -XX:MaxMetaspaceSize=${JVM_MaxMetaspaceSize:="256m"} -XX:MaxDirectMemorySize=${JVM_MaxDirectMemorySize:=1024m} -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy"

```
