### ISSUE TITLE
global session size exceeded, size : 550 maxBranchSessionSize : 512

### ISSUE THREAD

**Issue by xiaoyuwang1987** [apache/incubator-seata#6187]
用的是1.7.0的版本：
![image](https://github.com/apache/incubator-seata/assets/24749103/3b377426-1dd2-4d9d-a20f-71651cadc679)
确认用的是mysql模式
![image](https://github.com/apache/incubator-seata/assets/24749103/cd09d932-acfd-474a-9389-4437e7daefb7)

**Comment by funky-eyes** [comment]
启动时的日志发出来
The log at startup is sent out.

**Comment by funky-eyes** [comment]
![image](https://github.com/apache/incubator-seata/assets/19943636/5a9151a7-b0cf-48fa-ad91-18d06967709f)
已经确认你使用的是file模式了，请检查你自己的配置是否生效，比如application.yml中压根没使用nacos拉取对应的配置
It has been confirmed that you are using file mode. Please check whether your own configuration takes effect. For example, nacos is not used to pull the corresponding configuration in application.yml at all.

**Comment by xiaoyuwang1987** [comment]
> 启动时的日志发出来 The log at startup is sent out.

很诡异 我配置的是mysql 但是从阿里云上面看 没有找到seata用户的连接数，正常是要5个 我备用实例 有5个连接数，之前好像也出现过一次这种情况，就是能正常用但是数据库不生效，最后重启完有可以 跟docker有没有关系

**Comment by funky-eyes** [comment]
请检查自己配置映射关系，seata都有日志输出的
Please check your own configuration mapping relationship, seata has log output

**Comment by xiaoyuwang1987** [comment]
> The log at startup is sent out.

如果是存file,数据的读写存放路径在哪里，我去看一下

**Comment by funky-eyes** [comment]
sessionStore

**Comment by funky-eyes** [comment]
![image](https://github.com/apache/incubator-seata/assets/19943636/652254bd-1532-4445-9b64-23edff4fa6c1)
先调整这两项配置，让程序启动吧
Adjust these two configurations first and let the program start
