### ISSUE TITLE
MaxGlobalSessionSize not MaxBranchSessionSize

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6189]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1.MaxGlobalSessionSize和MaxBranchSessionSize的含义不清，我建议启用新的配置项，比如MaxBranchSessionBytes来取代
2.在代码上，明明是globalsession过大，却提示成了branchsession，这非常不对
基于以上几个问题，我希望社区可以提出一个良好的解决方案来优化此问题

1 The meaning of MaxGlobalSessionSize and MaxBranchSessionSize is unclear, I suggest enabling new configuration items, such as MaxBranchSessionBytes to replace
2 In the code, obviously the globalsession is too large, but it prompts that it becomes a branchsession, which is very wrong
Based on the above problems, I hope the community can come up with a good solution to optimize this problem
![image](https://github.com/apache/incubator-seata/assets/19943636/0c32c4ec-de71-41f5-84bf-ff5c09d7f3a7)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by laywin** [comment]
我看了一下这个命名，存在一些其他xx_SIZE,我认为这一个默认的约定，如果没有特殊指明，就是bytes，你的建议了？

I took a look at this naming, and there are some other xx_SIZE. I think this default convention, if not specified, is bytes. Do you have any suggestions?

**Comment by Jamesmahaitao** [comment]
我觉得size这个变量名称没必要改,因为
1. 具有通用性,后续如果变了单位,难道要再次兼容吗? 
2. 项目中很多地方都用这个size,要改的话需要全部改,风险比较大
建议在注释中写清楚这个单位是什么,然后改一下log打印的内容就可以了

**Comment by funky-eyes** [comment]
> 我觉得size这个变量名称没必要改,因为
> 
> 1. 具有通用性,后续如果变了单位,难道要再次兼容吗?
> 2. 项目中很多地方都用这个size,要改的话需要全部改,风险比较大
>    建议在注释中写清楚这个单位是什么,然后改一下log打印的内容就可以了

你说的也是一种方式，先把错误的提示改了，再从日志中增加单位提示
What you said is also a way. Change the wrong prompt first, and then add the unit prompt from the log.
