### ISSUE TITLE
metrics API cannot be enabled in k8s

### ISSUE THREAD

**Issue by Accelerator96** [apache/incubator-seata#6202]
使用官方的镜像没办法开启metrics

创建configmap 并开启metrics
`
server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: /logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata
seata:
  metrics:
    enabled: true
    registry-type: compact
    exporter-list: prometheus
    exporter-prometheus-port: 9898
  config:
    type: file
  registry:
    type: file
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login
`

然后将这个config map挂载进/seata-server/resources/application.yml下面

`
    spec:
      volumes:
        - name: seata-config
          configMap:
            name: seata-cm
            defaultMode: 420
      containers:
        - name: seata
          image: seataio/seata-server:1.7.1
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: seata-config
              mountPath: /seata-server/resources/application.yml
              subPath: application.yml
`

但是启动之后metrics 接口还是不能访问

请问各位大佬这个需要怎么开启呢？

**Comment by funky-eyes** [comment]
检查文件挂载，看样子是文件挂载有问题，配置无法读到。
Check the file mounting, it seems that there is a problem with the file mounting, and the configuration cannot be read.

**Comment by Accelerator96** [comment]
文件挂载的没有问题 在容器里面看到resource文件夹下面的application.yml是加了metrics的

**Comment by Accelerator96** [comment]
> 检查文件挂载，看样子是文件挂载有问题，配置无法读到。 Check the file mounting, it seems that there is a problem with the file mounting, and the configuration cannot be read.

文件挂载的没有问题 在容器里面看到resource文件夹下面的application.yml是加了metrics的 但是启动之后metrics端口并没有打开

**Comment by funky-eyes** [comment]
你试试不挂载，自己进去修改，重启
You can try not to mount it, go in and modify it yourself, and restart it.

**Comment by Accelerator96** [comment]
> 你试试不挂载，自己进去修改，重启 You can try not to mount it, go in and modify it yourself, and restart it.

配置了例如注册中心地址之类的配置都生效了 联动nacos都能看到注册的服务 但就是metrics的配置像失效了一样

**Comment by Accelerator96** [comment]
关闭了 发现如果启用配置中心的话 配置应该写在配置中心的配置文件里才行
