### ISSUE TITLE
The incorrect configuration needs to be fixed.

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6203]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
需要删除application.example.yml中如下的配置
You need to delete the following configuration in application.example.yml
![image](https://github.com/apache/incubator-seata/assets/19943636/37f0788c-7d4d-4e02-90f3-c998dbcc1981)
将config.txt中的错误配置名修改正确
Modify the wrong configuration name in config.txt to correct
![image](https://github.com/apache/incubator-seata/assets/19943636/b2530cb1-e25f-42b4-853a-ef5ffd2e5b53)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by dreamskyvision** [comment]
Please assign me
