### ISSUE TITLE
server端的lock_table的pk字段长度太短

### ISSUE THREAD

**Issue by markr512** [apache/incubator-seata#6216]
mysql8.0.32在at模式下提示
msg=Data truncation: Data too long for column 'pk'
 seata版本是1.8.0,
使用了camunda,主键超过了36

**Comment by leizhiyuan** [comment]
Can you please provide the complete error message? I need to see how the length is concatenated.

**Comment by funky-eyes** [comment]
可以自己加长，这个没有要求必须是多少长度
You can lengthen it yourself. There is no requirement for how long it must be.

**Comment by markr512** [comment]
> Can you please provide the complete error message? I need to see how the length is concatenated.

就是pk字段超长了,我改成了80,怕50不够
