### ISSUE TITLE
feign集成seata后服务发现负载均衡失效

### ISSUE THREAD

**Issue by zhangchaoyanggit** [apache/incubator-seata#6220]
seata 使用的是 `1.4.2` 版本, `SpringBoot 2.3.2`, `spring-cloud-alibaba-2.2.6.RELEASE`, `SpringCloud Hoxton.SR9`

我业务中为了代码统一,使用了feign url的调用方式调用其他集群服务,在seata事务中,启动类去除了`SeataFeignClientAutoConfiguration` 的配置,导致了负载均衡失效,如果我不去除这个类 通过feign url请求 就会报以下错误:

```java
com.netflix.client.ClientException: Load balancer does not have available server for client: 127.0.0.1
	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:90) ~[spring-cloud-openfeign-core-2.2.6.RELEASE.jar:2.2.6.RELEASE]
```

`@FeignClient(url = "http://127.0.0.1:30905",name = BaseConstant.TARGET_THIRD_FEIGN_API + "adsp")` //这个是我的feign url 服务

**Comment by funky-eyes** [comment]
Please give feedback to spring-cloud-alibaba community

**Comment by zhangchaoyanggit** [comment]
没有明白您的意思, SeataFeignClientAutoConfiguration 不属于seata的问题嘛?

**Comment by funky-eyes** [comment]
spring-data-redis属于redis还是属于spring？
Spring-data-redis belongs to redis or spring?

**Comment by zhangchaoyanggit** [comment]
好的大哥
