### ISSUE TITLE
Typo on the Chinese official website

### ISSUE THREAD

**Issue by tttcb** [apache/incubator-seata#6222]
(https://seata.io/zh-cn/docs/dev/domain/overviewDomainModel)
本文为您介绍 Seata(Simpe Extensible Autonomous **Transcaction** Architecture) 的领域模型。
Transaction

**Comment by funky-eyes** [comment]
Can you commit a pr to fix it?

**Comment by xingfudeshi** [comment]
> (https://seata.io/zh-cn/docs/dev/domain/overviewDomainModel) 本文为您介绍 Seata(Simpe Extensible Autonomous **Transcaction** Architecture) 的领域模型。 Transaction

It would be great if you can commit  a PR to fix it.

**Comment by xingfudeshi** [comment]
<img width="1442" alt="image" src="https://github.com/apache/incubator-seata/assets/24457941/bee86ba0-540f-4b87-ab39-4859dcd1416d">
<img width="1344" alt="image" src="https://github.com/apache/incubator-seata/assets/24457941/521efe18-d4f7-4b71-9172-ead14e7a5037">

**Comment by funky-eyes** [comment]
感谢你的pr，已经进行了合并。
Thank you for your PR, it has been merged.
