### ISSUE TITLE
Database read-write separation, RM registration reads are not from the main database

### ISSUE THREAD

**Issue by Python-IBM** [apache/incubator-seata#6236]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Implement MySQL read-write separation using shardingsphere-jdbc application configuration. When starting the application server, the registration of RM resources in seata is from the slave database, which causes the main database to be unable to roll back normally.

### Ⅱ. Describe what happened
RM registers slave MySQL, but when rolling back a main MySQL transaction, it is not possible to compare the data in the "undo_log" table.

### Ⅲ. Describe what you expected to happen
I expect to see the RM registration main database resource of seata when the application service starts.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Start application service
2. Register TM and RM resources
3. Calling Dubbo interface methods
4. The interface transaction of microservice B calling microservice A was not rolled back.
![image](https://github.com/apache/incubator-seata/assets/33851767/2fb761d3-68f1-460b-9c84-04acdfb07741)

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 17
- Seata client/server version:  2.0
- Database version: MySQL 8.0.27
- OS(e.g. `uname -a`): Windows
- Others: 
 shardingsphere-jdbc version: 5.4.0
 spring boot version: 3.2.1
dubbo version: 3.2.10

**Comment by funky-eyes** [comment]
使用sharding-jdbc请不要开启seata的数据源代理，具体使用方式参见他们的文档
Please do not open seata's data source proxy when using sharding-jdbc. For details, please refer to their documentation

**Comment by Python-IBM** [comment]
> 使用sharding-jdbc请不要开启seata的数据源代理，具体使用方式参见他们的文档 Please do not open seata's data source proxy when using sharding-jdbc. For details, please refer to their documentation

I did not integrate seata using shardingsphere jdbc, I used it independently of each other. Just using shardingsphere jdbc to achieve read-write separation, and directly using seata data source proxy

**Comment by Python-IBM** [comment]
I have a question, why does seata rm register resources to read the jdbc URL of slave mysql?
