### ISSUE TITLE
AT模式内部异步请求如何进行二阶段回滚？

### ISSUE THREAD

**Issue by lin1005q** [apache/incubator-seata#6255]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

```mermaid
sequenceDiagram
    autonumber
    participant A as A(use seata at)
    participant B as B(use seata at)
    participant C as C(use seata at)
    participant D as D(not use seata)
    Note over A: global begin
    A->>A: Mysql JDBC
    A->>B: openfeign
    B->>B: Mysql JDBC
    B->>B: Kafka send
    B->>D: async httpclient(not use seata)
    B->>C: openfeign
    C->>C: Mysql JDBC
    C-->>B: openfeign
    B-->>A: openfeign
    Note over A: global commit
```

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

如果7失败了，4和5怎么做回滚？ 使用localTcc注解的方式可以解决么？如果使用localTcc注解的方式，rollbackMethod执行中异常了会重试回滚么？

https://seata.io/zh-cn/blog/integrate-seata-tcc-mode-with-spring-cloud.html

**Comment by lin1005q** [comment]
@slievrly Thanks.

**Comment by funky-eyes** [comment]
可以使用在kafka时，一阶段的消息通过localtcc注解，将一阶段要发kafka的消息变成注册tcc分支存储在server侧，二阶段下发confirm的时候做发送
can be used in kafka, the first stage of the message through the localtcc annotation, the first stage of the message to be sent to kafka into a registered tcc branch stored on the server side, the second stage of the next confirm when doing send

**Comment by funky-eyes** [comment]
Asynchronous http calls can also utilize tcc by placing them into a two-stage confirm for the call

**Comment by lin1005q** [comment]
👌
