### ISSUE TITLE
saga mode replay context lost start, issue 5682 reopen !!

### ISSUE THREAD

**Issue by gou60** [apache/incubator-seata#6257]
### Ⅰ. Issue Description

- [[#5682](https://github.com/seata/seata/pull/5682)] 修复saga模式下replay context丢失startParams问题
reopen!  

### Ⅱ. Describe what happened
https://github.com/apache/incubator-seata/blob/2.x/saga/seata-saga-engine/src/main/java/io/seata/saga/engine/impl/ProcessCtrlStateMachineEngine.java

    protected Map<String, Object> replayContextVariables(StateMachineInstance stateMachineInstance) {
        Map<String, Object> contextVariables = new HashMap<>();
        **if (stateMachineInstance.getStartParams() == null) {**
            contextVariables.putAll(stateMachineInstance.getStartParams());
        }

### Ⅲ. Describe what you expected to happen
https://github.com/apache/incubator-seata/blob/1.8.0/saga/seata-saga-engine/src/main/java/io/seata/saga/engine/impl/ProcessCtrlStateMachineEngine.java

    protected Map<String, Object> replayContextVariables(StateMachineInstance stateMachineInstance) {
        Map<String, Object> contextVariables = new HashMap<>();
        **if (stateMachineInstance.getStartParams() != null) {**
            contextVariables.putAll(stateMachineInstance.getStartParams());
        }

**Comment by funky-eyes** [comment]
@wt-better Please help with this question

**Comment by funky-eyes** [comment]
What version of seata-client are you using?

**Comment by wt-better** [comment]
this issue have fixed on 1.8,  but not 2.x, I will fixed it on 2.x later.

**Comment by slievrly** [comment]
@wt-better I suggest including it in the milestone for version 2.1.0.

**Comment by slievrly** [comment]
@wt-better Is there any progress information here ？
