### ISSUE TITLE
seata 控制台查询事务列表接口 时间筛选无效

### ISSUE THREAD

**Issue by Accelerator96** [apache/incubator-seata#6272]
无时间筛选
<img width="1059" alt="image" src="https://github.com/apache/incubator-seata/assets/13599846/e1d64244-5294-488f-900e-eaeedfa898f0">
gmtcreate 为 1705557870000 

选择的了时间筛选
<img width="1335" alt="image" src="https://github.com/apache/incubator-seata/assets/13599846/89fd1d56-c21f-4cd2-b9eb-82c7d59d05f9">

查询不出数据

版本 seata1.7.1

**Comment by xingfudeshi** [comment]
I will check it

**Comment by xingfudeshi** [comment]
I've submitted a PR to fix this bug,you can review it. @Accelerator96
