### ISSUE TITLE
v2.0.0部署K8s registry.conf 配置不生效

### ISSUE THREAD

**Issue by gebizhangdaye** [apache/incubator-seata#6273]
{
	"registry.conf": "registry {
		  type = \"nacos\"
		  nacos {
		    application = \"seata-server\"
		    serverAddr = \"nacos-headless.nacos.svc.cluster.local:8848\"
		    namespace = \"\"
		    group = \"SEATA_GROUP\"
		    cluster = \"default\"
		  } 
		}
		config {
		  type = \"nacos\"
		  nacos {
		    serverAddr = \"nacos-headless.nacos.svc.cluster.local:8848\"
		    namespaces = \"\"
		    group = \"SEATA_GROUP\"
		    contextPath = \"\"
		    dataId = \"seataServer.properties\"      
		  }
		}
}

确定serverAddr 可以访问到，并且访问正常
但是启动server后 无法注册服务，并且配置也没有拉取到

**Comment by leizhiyuan** [comment]
Please provide a complete startup log.
