### ISSUE TITLE
seata1.8+nacos，store.mode=db不生效，实际还是file模式

### ISSUE THREAD

**Issue by afabama** [apache/incubator-seata#6282]
![image](https://github.com/apache/incubator-seata/assets/33012974/0e5ae223-b7be-4264-acbe-47176709e07f)
seata:  
  store:
    # support: file 、 db 、 redis
    mode: db
    session:
      mode: db
    lock:
      mode: db
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.20.111:3306/seata?useSSL=false&useUnicode=true&rewriteBatchedStatements=true
      user: root
      password: root
      、、、

启动后，提示
use session store mode: file
use lock store mode: file

能正常启动，但数据库lock_table、branch_table等几张表无数据。
1.8源码调试，配置已经正常加载为db
private static StoreMode getStoreMode() 方法返回值依旧是db

**Comment by funky-eyes** [comment]
Please write to nacos and the configuration should not have the `seata.` prefix as this prefix is used in conjunction with springboot.

**Comment by xingfudeshi** [comment]
This issue will be closed. If you have any further questions, please feel free to reply.
