### ISSUE TITLE
1.4版本，AT模式下同一global事务，insert一个数据 然后update，回滚失败

### ISSUE THREAD

**Issue by 13333713052** [apache/incubator-seata#6288]
我在一个service中使用，先insert，后update对同一条数据操作，会回滚失败，查看日志发现先回滚的是insert，这是bug吗？我该怎么做才能正常回滚？

**Comment by funky-eyes** [comment]
Check the precision of datetime in your database branchtable
检查你的数据库branchtable中的datetime的精度

**Comment by slievrly** [comment]
1.4.x refers to which version, the client SDK version or the Seata-Server version? This needs to be specified.

**Comment by 13333713052** [comment]
> 1.4.x refers to which version, the client SDK version or the Seata-Server version? This needs to be specified.

我server是2.0最新的，SDK是1.4.0

**Comment by 13333713052** [comment]
> Check the precision of datetime in your database branchtable 检查你的数据库branchtable中的datetime的精度

采用的官网sql语句，AT模式 发现只有全局锁lock_table表有数据，这个表时间没有精度，branchtable是有精度的，但是这个表一直没数据进入

**Comment by funky-eyes** [comment]
> > Check the precision of datetime in your database branchtable 检查你的数据库branchtable中的datetime的精度
> 
> 采用的官网sql语句，AT模式 发现只有全局锁lock_table表有数据，这个表时间没有精度，branchtable是有精度的，但是这个表一直没数据进入

This bug exists in server 2.0, and if there are duplicate updates to the same resource in the same global transaction (the same local transaction is unaffected) it will result in an incorrect rollback sequence

**Comment by 13333713052** [comment]
> > > Check the precision of datetime in your database branchtable 检查你的数据库branchtable中的datetime的精度
> > 
> > 
> > 采用的官网sql语句，AT模式 发现只有全局锁lock_table表有数据，这个表时间没有精度，branchtable是有精度的，但是这个表一直没数据进入
> 
> This bug exists in server 2.0, and if there are duplicate updates to the same resource in the same global transaction (the same local transaction is unaffected) it will result in an incorrect rollback sequence

我尝试把SDK升级为2.0，发现lock_table没有数据了，但是seata会正常回滚，没有出现上面那个错误了
