### ISSUE TITLE
Compatible with lower versions of SPI

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#6307]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

When the user upgrades from io.seata to org.apache.seata and the user implements a lower version of the io.seata.xxx interface, the user's SPI implementation needs to be compatible without the user having to change any code.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
This issue has been discussed in https://github.com/apache/incubator-seata/discussions/6059
