### ISSUE TITLE
请问怎么代理直接执行的sql事务

### ISSUE THREAD

**Issue by yuhai5237** [apache/incubator-seata#6316]
例如我在项目里直接获取DataSource对象，创建Sqlsession直接执行sql，这种事务可以交给seata代理吗，怎么代理，有没有参考文档

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata-samples/tree/master/api

**Comment by yuhai5237** [comment]
> https://github.com/apache/incubator-seata-samples/tree/master/api
这个和我的需求不太一样，我的项目框架是基于springcold+mybatis-plus多数据源的，已经集成seata了，正常通过mybatis-plus执行的业务的事务可以正常提交回滚，但是其中有一部分业务是直接获取SqlSession直接执行sql语句 ：        
            pst = seataConnectionProxy.prepareStatement(sql);
            row = pst.executeUpdate();
但是这部分的事务没有被seata管理，没办法进行事务的提交和回滚，我想知道seata有没有对这种事务进行集成，怎么进行提交和回滚，mybatis-plus的事务+创建出来的SqlSession的事务进行统一管理

**Comment by yuhai5237** [comment]
> https://github.com/apache/incubator-seata-samples/tree/master/api

这个和我的需求不太一样，我的项目框架是基于springcold+mybatis-plus多数据源的，已经集成seata了，正常通过mybatis-plus执行的业务的事务可以正常提交回滚，但是其中有一部分业务是直接获取SqlSession直接执行sql语句：
pst = SeataConnectionProxy.prepareStatement(sql);
row = pst.executeUpdate();
但是这部分的事务没有被seata管理，没办法进行事务的提交和回滚，我想知道seata有没有对这个事务进行集成，怎么进行提交和回滚，mybatis- plus的事务+创建出来的SqlSession的事务进行统一管理

**Comment by funky-eyes** [comment]
一样的，自行变通一下，只要你拿被seata代理的datasource去创建的connection，并且xid被绑定，是一定被seata所管理
The same, with a twist, as long as you take the datasource that is proxied by seata to create the connection, and the xid is bound, it must be managed by seata.

**Comment by yuhai5237** [comment]
> 同样的，自行变通一下，只要你拿被seata代理的数据源去创建连接，并且xid被绑定，是一定被seata所管理的， 同样的，有一点不同，只要你拿被代理的数据源Seata创建连接，并且绑定了xid，必须由seata管理。

我也是这么想的，但是一直没成功，应该是获取的代理对象有问题，我这边再试试看，谢谢大佬

**Comment by yuhai5237** [comment]
> 一样的，自行变通一下，只要你拿被seata代理的datasource去创建的connection，并且xid被绑定，是一定被seata所管理 The same, with a twist, as long as you take the datasource that is proxied by seata to create the connection, and the xid is bound, it must be managed by seata.

           
 //            Connection connection = session.getConnection();
//            connection.setAutoCommit(false);
//            pst = connection.prepareStatement(sql);
//            row = pst.executeUpdate();

            pst = getSeataConnectionProxy().prepareStatement(sql);
            row = pst.executeUpdate();

//            DataSourceProxy seataDataSourceProxy = getSeataDataSourceProxy();
//            Db.use(seataDataSourceProxy).execute(sql);DefaultResourceManager defaultResourceManager = DefaultResourceManager.get();
 Map<String, io.seata.core.model.Resource> managedResources = defaultResourceManager.getManagedResources();
return (DataSourceProxy) managedResources.get("jdbc:mysql://www.dmkj.com:3306/ruoyi-vue-pro");  
这是我获取代理对象的代码，但是这样还是不行，我是执行一条创建建表sql的语句，最后所有事务都回滚了，就是建的表的没有回滚
