### ISSUE TITLE
springcloud中seata分布式事务,feign被调用方没有绑定xid

### ISSUE THREAD

**Issue by hyyyyy77** [apache/incubator-seata#6321]
seata版本 1.6.1
A服务是调用方,分别调用了B服务与C服务,都是通过feign调用,但是在调用B服务的时候,在B服务的方法中使用RootContext.getXID()无法获取A服务传递过来的XID,但是在B服务的feign请求头中查看到了A服务传递过来的xid;
调用C服务时,C服务是会绑定XID的,也就是seata的TransactionPropagationInterceptor中的preHandle方法,但是在调用B服务的时候,没有进入这个方法;
有尝试过自定义拦截器,然后将xid获取然后放入到请求头中,但是没有作用,在拦截器中能获取到xid,但是依然无法进入到seata的preHandle方法,如果在B服务的方法上也贴seata 的@GlobalTransactional注解,那么他就会生成一个新的xid,而不是A服务传递过来的xid,

如果A服务调用B服务时,B服务里面又调用了C服务(并且B服务也贴了@GlobalTransactional),结果就是A服务的xid没有绑定到B服务,然后B服务会生成新的xid,B服务调用C服务后,会将B服务生成的XID传递过C服务;如果B服务不贴@GlobalTransactional,那么就不会有xid,
求助大佬,不知道怎么解决

**Comment by hyyyyy77** [comment]
![QQ图片20240203151005](https://github.com/apache/incubator-seata/assets/154746345/879ffbfb-9af9-4feb-8b88-2cde74bf1754)
这是B服务与C服务引入的关于事务的依赖

**Comment by funky-eyes** [comment]
https://seata.apache.org/zh-cn/docs/overview/faq#24

**Comment by hyyyyy77** [comment]
> https://seata.apache.org/zh-cn/docs/overview/faq#24

大佬,我这个情况属于xid没有传递过去吗,因为我看到feign被调用方的请求头中是有对应的xid的,只是他不会进入seata 的绑定xid方法,不知道为什么

**Comment by hyyyyy77** [comment]
后续debug发现是那个服务少了seata的拦截器,不知道为什么

**Comment by hyyyyy77** [comment]
已解决

**Comment by basketballboy** [comment]
怎么解决的
