### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: store.db.dbType should not be blank

### ISSUE THREAD

**Issue by swf1711410916** [apache/incubator-seata#6323]
docker下使用nacos做seata注册和配置中心，nacos和seata都是最新版
store.db.dbType都有配置如下图：
![1706971798039](https://github.com/apache/incubator-seata/assets/27270701/634333d4-254f-463a-9ac5-10e9cec35107)
![1706972074837](https://github.com/apache/incubator-seata/assets/27270701/beca496f-c148-4498-aa30-c639175b33a6)

**Comment by VardenZ** [comment]
最后怎么解决的？ 我也遇到同样的问题，感谢感谢

**Comment by 453189692** [comment]
？？？？

**Comment by shuxiade** [comment]
给mysql加两冒号 "mysql"

**Comment by huang-jianfeng** [comment]
> 给mysql加两冒号 "mysql"

没效果啊

**Comment by DragonZru** [comment]
nacos配置server-addr 这里是docker 容器ip,你要是配置localhost 是连不上的，换成公网ip或者内网ip.
错误信息 BranchSessionDBServiceImpl line 65 :         if (StringUtils.isBlank(dbType)) {
            throw new IllegalArgumentException(ConfigurationKeys.STORE_DB_TYPE + " should not be blank");
        },所以这里就是从nacos 读取store.db.dbType 失败了
