### ISSUE TITLE
 TCC interceptor will not work when using @Bean (factorybean).

### ISSUE THREAD

**Issue by Bughue** [apache/incubator-seata#6341]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
![image](https://github.com/apache/incubator-seata/assets/3788653/fb453d37-a01f-4d13-86d2-7e484ec7656f)
![image](https://github.com/apache/incubator-seata/assets/3788653/615ba7f9-3bb2-4fcd-bd42-e9b4437cddf1)
![image](https://github.com/apache/incubator-seata/assets/3788653/a7daa3ad-104f-4164-9972-60bcf16f14c1)
The proxy of TCC will not work when using @Bean (factorybean), which means that currently, it is not permitted for users to create a @localtcc RM (Resource Manager) using the @Bean method. If it is indeed created in this way, it will just be a bean that is not proxied, and the branch will not be registered. Has this been discussed before? Are there any plans to support it in the future?

TCC 的代理会在使用 @Bean（factorybean） 的情况下不起作用，也就是说目前是不允许用户把一个@localtcc的rm用@bean的方式去创建的。如果他真的这样创建了，那也只是个未被代理的bean，分支不会注册。这个是已经讨论过的吗？后面有没有计划支持？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
From the code you provided above, I don't see any connection to the factoryBean.getObject creation bean.
