### ISSUE TITLE
favicon.ico return 401

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#6355]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

When not login Seata console, visit http://localhost:7091/favicon.ico return error code 401
![image](https://github.com/apache/incubator-seata/assets/8758457/3f751eb4-f0de-4f48-a443-a109b0d36378)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by liuqiufeng** [comment]
此问题是由于/favicon.ico不存在，自动跳转到了一个需要授权的链接/error所导致。目前最新版seata console中指定了favicon.ico的路径，不应该访问此地址。

This issue is caused by /favicon.ico not existing and automatically jumping to a link that requires authorization /error. The path to favicon.ico is currently specified in the latest version of the seata console and should not access this address.

**Comment by slievrly** [comment]
> 此问题是由于/favicon.ico不存在，自动跳转到了一个需要授权的链接/error所导致。目前最新版seata console中指定了favicon.ico的路径，不应该访问此地址。
> 
> This issue is caused by /favicon.ico not existing and automatically jumping to a link that requires authorization /error. The path to favicon.ico is currently specified in the latest version of the seata console and should not access this address.

I am using the seataio/seata-server:latest image, are you sure the new version fixes this?

**Comment by liuqiufeng** [comment]
> > 此问题是由于/favicon.ico不存在，自动跳转到了一个需要授权的链接/error所导致。目前最新版seata console中指定了favicon.ico的路径，不应该访问此地址。
> > This issue is caused by /favicon.ico not existing and automatically jumping to a link that requires authorization /error. The path to favicon.ico is currently specified in the latest version of the seata console and should not access this address.
> 
> I am using the seataio/seata-server:latest image, are you sure the new version fixes this?

I have not reproduced the problem using the seataio/seata-server:latest image. Is there any other information you can provide?

**Comment by slievrly** [comment]
> > > 此问题是由于/favicon.ico不存在，自动跳转到了一个需要授权的链接/error所导致。目前最新版seata console中指定了favicon.ico的路径，不应该访问此地址。
> > > This issue is caused by /favicon.ico not existing and automatically jumping to a link that requires authorization /error. The path to favicon.ico is currently specified in the latest version of the seata console and should not access this address.
> > 
> > 
> > I am using the seataio/seata-server:latest image, are you sure the new version fixes this?
> 
> I have not reproduced the problem using the seataio/seata-server:latest image. Is there any other information you can provide?

1. Add,/health at the end of security.ignow.urls, which takes effect when mounted with -v or modified directly by restart
2. visit http://localhost:7091/health

**Comment by liuqiufeng** [comment]
ok. I'll fix it.
