### ISSUE TITLE
XA模式异步提交模式探讨

### ISSUE THREAD

**Issue by wuchaococo** [apache/incubator-seata#6377]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
没有的设计XA模式下，全局事务提交的时候TC是异步同步RM进行提交的，这个时候，如果RM的异步提交慢，业务的主线程已经返回了，就会出现业务已经结束了，这个时候事务还没有提交完成。
这种场景应该如何处理？

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
`没有的设计XA模式下`  是什么意思？
如果你启用了tc侧的异步提交，本身代表你自己允许异步提交，最终一致的情况，又为什么会有这个疑问呢？这不应该由业务属性决定的吗？再者你的xa分支的本地锁是会被锁定的，如果你用当前读非快照读本身就会被阻塞等待二阶段提交完成后才可见，实际上没有什么影响，用快照读也就是读取到前面的数据，就跟你有个本地事务没有提交，起了另一个连接去查询这个数据的结果一样。
What does `in design XA mode without` mean? If you enable asynchronous commits on the tc side, which in itself means you allow asynchronous commits on your own, and ultimately consistency, then why is this questionable? Shouldn't this be determined by business properties? Furthermore the local locks on your xa branch are locked, if you read with current read non-snapshot read itself will be blocked waiting for the second stage commit to complete before it is visible, it doesn't really have any effect, with snapshot read it is just reading into the previous data, same as if you had a local transaction that didn't commit and started another connection to query the results of that data.

**Comment by wuchaococo** [comment]
> `没有的设计XA模式下` 是什么意思？ 如果你启用了tc侧的异步提交，本身代表你自己允许异步提交，最终一致的情况，又为什么会有这个疑问呢？这不应该由业务属性决定的吗？再者你的xa分支的本地锁是会被锁定的，如果你用当前读非快照读本身就会被阻塞等待二阶段提交完成后才可见，实际上没有什么影响，用快照读也就是读取到前面的数据，就跟你有个本地事务没有提交，起了另一个连接去查询这个数据的结果一样。 What does `in design XA mode without` mean? If you enable asynchronous commits on the tc side, which in itself means you allow asynchronous commits on your own, and ultimately consistency, then why is this questionable? Shouldn't this be determined by business properties? Furthermore the local locks on your xa branch are locked, if you read with current read non-snapshot read itself will be blocked waiting for the second stage commit to complete before it is visible, it doesn't really have any effect, with snapshot read it is just reading into the previous data, same as if you had a local transaction that didn't commit and started another connection to query the results of that data.

如何关闭TC的异步提交，即RM和TC之间的提交不是异步的，采用同步提交

**Comment by funky-eyes** [comment]
tc defaults to synchronous commits

**Comment by wuchaococo** [comment]
> tc defaults to synchronous commits

那是不是认为TM通知TC提交，以及TC开始触发RM分支提交，这是同步柱塞的，再没有完成之前，业务是不会返回的，是吗？

**Comment by wuchaococo** [comment]
> tc defaults to synchronous commits

是否可以这样理解

**Comment by funky-eyes** [comment]
> > tc defaults to synchronous commits
> 
> 那是不是认为TM通知TC提交，以及TC开始触发RM分支提交，这是同步柱塞的，再没有完成之前，业务是不会返回的，是吗？

Yes, unless tm has an rpc timeout
