### ISSUE TITLE
2.0.0 Role.Participant不执行hook但会清理，导致hook无法执行

### ISSUE THREAD

**Issue by yezhongji** [apache/incubator-seata#6384]
### Ⅰ. Issue Description
![image](https://github.com/apache/incubator-seata/assets/29244379/cca80e98-951d-47ce-bc0f-775940a84afa)
如题
https://github.com/apache/incubator-seata/issues/5595 这个修复引起的

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  2.0.0
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
It's not the pr that's causing this, it's the fact that the participant itself shouldn't support hooks, this is a tm hook not an rm hook

**Comment by yezhongji** [comment]
hook是在Launcher注册的，但还是被participant清掉了，Launcher和participant是同一线程

**Comment by yezhongji** [comment]
> It's not the pr that's causing this, it's the fact that the participant itself shouldn't support hooks, this is a tm hook not an rm hook

hook是在Launcher注册的，但还是被participant清掉了，Launcher和participant是同一线程

**Comment by yezhongji** [comment]
> > It's not the pr that's causing this, it's the fact that the participant itself shouldn't support hooks, this is a tm hook not an rm hook
> 
> hook是在Launcher注册的，但还是被participant清掉了，Launcher和participant是同一线程

建议
![image](https://github.com/apache/incubator-seata/assets/29244379/ce6bae8d-880a-4792-ab5f-4e3b7610d0a9)
既然Participant不执行hook，也不应该执行cleanUp的操作

**Comment by funky-eyes** [comment]
> > > It's not the pr that's causing this, it's the fact that the participant itself shouldn't support hooks, this is a tm hook not an rm hook
> > 
> > 
> > hook是在Launcher注册的，但还是被participant清掉了，Launcher和participant是同一线程
> 
> 建议 ![image](https://private-user-images.githubusercontent.com/29244379/309160728-ce6bae8d-880a-4792-ab5f-4e3b7610d0a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzMxNzUsIm5iZiI6MTcwOTI3Mjg3NSwicGF0aCI6Ii8yOTI0NDM3OS8zMDkxNjA3MjgtY2U2YmFlOGQtODgwYS00NzkyLWFiNWYtNGUzYjc2MTBkMGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA2MDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZTRlNmM1NjI3M2VhMmNkZjNhYzAwYTgyMDUwZmQ5ZmZkZDQ4NjYwMTg1OGQxMGE2NGQwMjMwN2VmYzA4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5qqIVJWmYOCBe0T3WUndpCtu0QYH5p0Vmhpb4g_51TE) 既然Participant不执行hook，也不应该执行cleanUp的操作

Yes, it should be as you describe, the participant shouldn't be able to perform cleanup actions since they don't support hooks, can you submit a pr for restricting the participant's behavior?
