### ISSUE TITLE
Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by ysnnuan** [apache/incubator-seata#6397]
jdk17,mysql8.0.33,seata2.0.0 springcloud2023 springcloudalibaba2023-RC1

![image](https://github.com/apache/incubator-seata/assets/19728710/e153d7a4-bb8d-44e0-9708-0b57b6d4fed6)
 

![image](https://github.com/apache/incubator-seata/assets/19728710/88c36d50-6747-49a6-99db-d4269f3b9d0a)

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/issues/6389

**Comment by ysnnuan** [comment]
![image](https://github.com/apache/incubator-seata/assets/19728710/326182db-807e-4d3f-8fc4-375ea1f52ecd) 选哪个版本比较合适，最新的master是不是可以直接用？
