### ISSUE TITLE
AT模式的分支事务在全局事务提交或回滚时，RM如何添加逻辑？

### ISSUE THREAD

**Issue by wanghongzhou** [apache/incubator-seata#6401]
使用AT模式，在每个分支事务都有对缓存的数据的处理，请问下如何在全局事务结束后维护缓存？

**Comment by funky-eyes** [comment]
You can add a tcc branch transaction for the cache to handle the

**Comment by slievrly** [comment]
The cache is weakly consistent and not suitable for synchronization processing.
