### ISSUE TITLE
Mac启动报错了，感觉像是获取当前目录有问题，是我系统版本不兼容吗

### ISSUE THREAD

**Issue by MrZhang424** [apache/incubator-seata#6406]
sh seata-server.sh -p 8091 -h 127.0.0.1 -m file
Error: Unable to access jarfile /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar

**Comment by funky-eyes** [comment]
Look at what your user directory is in your environment variables.

**Comment by leizhiyuan** [comment]
First, check if this file exists. Then, check if this file is open or in use.

**Comment by 1040968536** [comment]
我也遇到了同样的问题
`/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java  -server -Dloader.path=../lib -Xmx2048m -Xms2048m -Xmn1024m -Xss512k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/min.ji/Git/github/seata/distribution/logs/java_heapdump.hprof -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -Xloggc:/Users/min.ji/Git/github/seata/distribution/logs/seata_gc.log -verbose:gc -XX:+PrintGCDetails  -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=68288 -Dapp.home=/Users/min.ji/Git/github/seata/distribution -Dbasedir=/Users/min.ji/Git/github/seata/distribution -Dspring.config.location=/Users/min.ji/Git/github/seata/distribution/conf/application.yml -Dlogging.config=/Users/min.ji/Git/github/seata/distribution/conf/logback-spring.xml -jar /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar 
Error: Unable to access jarfile /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar
` 
报错里面涉及的JDK和jar包地址都是错误的，与我本地环境不符合。

**Comment by ptyin** [comment]
Which seata version are you using?

**Comment by 1040968536** [comment]
> Which seata version are you using?

Seata version 2.0.0 JDK 21

**Comment by leizhiyuan** [comment]
这个只是因为打包的项目里面，有一个logs/start.out文件，里面有这个信息。可以删除这个文件再看看

<img width="1867" alt="image" src="https://github.com/apache/incubator-seata/assets/2684384/1b8bb2a9-5768-4828-b7fe-a28f59c73413">


直接启动本地mac我验证没有问题

<img width="1215" alt="image" src="https://github.com/apache/incubator-seata/assets/2684384/2a245ad6-5208-4b44-9607-fc9da12a812b">

**Comment by funky-eyes** [comment]
> 我也遇到了同样的问题 `/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java -server -Dloader.path=../lib -Xmx2048m -Xms2048m -Xmn1024m -Xss512k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/min.ji/Git/github/seata/distribution/logs/java_heapdump.hprof -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -Xloggc:/Users/min.ji/Git/github/seata/distribution/logs/seata_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=68288 -Dapp.home=/Users/min.ji/Git/github/seata/distribution -Dbasedir=/Users/min.ji/Git/github/seata/distribution -Dspring.config.location=/Users/min.ji/Git/github/seata/distribution/conf/application.yml -Dlogging.config=/Users/min.ji/Git/github/seata/distribution/conf/logback-spring.xml -jar /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar Error: Unable to access jarfile /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar ` 报错里面涉及的JDK和jar包地址都是错误的，与我本地环境不符合。

经过确认，这只是被打包进去的一个日志内容而已，并不影响使用，请自行使用jps，和去logs中查看seata-server-8091xxxx相关的日志
After confirming, this is just a log content is packed in, does not affect the use, please use jps, and go to logs to check seata-server-8091xxxx related logs
