### ISSUE TITLE
升级2.0.0版本启动后一直报错

### ISSUE THREAD

**Issue by zsp419** [apache/incubator-seata#6410]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
升级2.0.0版本后，启动后一直报错

### Ⅱ. Describe what happened

![lQLPJwJt8VKCgHnNAZTNBouwKcipDOl4pdQF3MCQ4wtSAA_1675_404](https://github.com/apache/incubator-seata/assets/27196467/438c568c-b823-420e-b0f2-d40c753a8d37)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
Please try to check if there is a network problem at this address

**Comment by zsp419** [comment]
> Please try to check if there is a network problem at this address

内网服务之间都是通的，client端都能注册到server端，而且好像也不影响使用，这个错是个warn级别的，您说的网络问题是指该机器能否访问外网吗

**Comment by funky-eyes** [comment]
`ping -s 128 -i 0.2 ip `
类似这样在seata-server侧去ping一下网络状况，还有这个异常在你的client如果出现非优雅下线时也是会出现的，异常信息就是字面意思
Similar to this on the seata-server side to ping the network status, there is also this exception in your client if there is a non-graceful downtime will also appear, the exception information is literally
