### ISSUE TITLE
M1 mac JDK 17 无法启动seata 2.0.0 

### ISSUE THREAD

**Issue by 1040968536** [apache/incubator-seata#6414]
`seven@deMacBook-Pro bin % java -version
java version "17.0.10" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.10+11-LTS-240, mixed mode, sharing)
seven@deMacBook-Pro bin % ls
seata-server.bat	seata-setup.sh
seata-server.sh		startup.sh
seven@deMacBook-Pro bin % sh seata-server.sh -p 8091 -h 127.0.0.1 -m file
apm-skywalking not enabled
JMX disabled
/Users/seven/Java/jdk-17.0.10.jdk//Contents/Home/bin/java  -Dlog.home=/Users/seven/logs/seata -server -Dloader.path=/Users/seven/Downloads/seata/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/seven/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xlog:gc*:file=/Users/seven/logs/seata/seata_gc.log:time,tags:filecount=10,filesize=102400 -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=1198 -Dapp.home=/Users/seven/Downloads/seata -Dbasedir=/Users/seven/Downloads/seata  -Dspring.config.additional-location=/Users/seven/Downloads/seata/conf/ -Dspring.config.location=/Users/seven/Downloads/seata/conf/application.yml -Dlogging.config=/Users/seven/Downloads/seata/conf/logback-spring.xml -jar /Users/seven/Downloads/seata/target/seata-server.jar -p 8091 -h 127.0.0.1 -m file >> /dev/null 2>&1 &
seata-server is starting, you can check the /Users/seven/logs/seata/ *.log
seven@deMacBook-Pro bin % cd /Users/seven/logs/
seven@deMacBook-Pro logs % ls
csp		eagleeye
seven@deMacBook-Pro logs % 

`

java version "17.0.10"
seata-server-2.0.0
mysql-8.3.0
macOS Sonoma 14.4

**Comment by leizhiyuan** [comment]
How do you determine if the start-up has failed?

I used JDK 17 and M1, and it ran okay.

<img width="1218" alt="image" src="https://github.com/apache/incubator-seata/assets/2684384/9d1402b7-ad08-4e00-9718-2abcc4e6096a">



<img width="643" alt="image" src="https://github.com/apache/incubator-seata/assets/2684384/741d38fe-2604-44d5-a244-56349f1fe2b2">

**Comment by 1040968536** [comment]
> 如何判断启动是否失败？
> 
> 我使用了 JDK 17 和 M1，运行良好。
> 
> <img alt="图像" width="1218" src="https://private-user-images.githubusercontent.com/2684384/311900538-9d1402b7-ad08-4e00-9718-2abcc4e6096a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDcxNjUsIm5iZiI6MTcxMDIwNjg2NSwicGF0aCI6Ii8yNjg0Mzg0LzMxMTkwMDUzOC05ZDE0MDJiNy1hZDA4LTRlMDAtOTcxOC0yYWJjYzRlNjA5NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDEyNzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E4OTc1ZWNjOWQ4YzY2OTIwMjQyYTZlMjI2NmViNmNhODQ3MmRkMDdjMWU2MzQxYmY0OTExNTY4MDg0ZjJjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jOoPCPxybwNQWUxUukpW1eACL8pbruK1qEAIUoi6sOE"> <img alt="图像" width="643" src="https://private-user-images.githubusercontent.com/2684384/311900514-741d38fe-2604-44d5-a244-56349f1fe2b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDcxNjUsIm5iZiI6MTcxMDIwNjg2NSwicGF0aCI6Ii8yNjg0Mzg0LzMxMTkwMDUxNC03NDFkMzhmZS0yNjA0LTQ0ZDUtYTI0NC01NjM0OWYxZmUyYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDEyNzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU0MmM4OWZjYmY3MmU3MTc2YmNjZjYzYWZkYWZhYTliYjEwYTViYjVhNGMyMTY0M2U5YTJmZGViY2IzYTc5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fe8Mno_OIgNxrTPU0H5qv7tOlnUaCzvZJRGwuF_fRF0">
使用命令查询端口未被占用 同时我无法访问 http://localhost:8091/
seven@deMacBook-Pro logs % lsof -i :8091
seven@deMacBook-Pro logs % netstat -anp tcp -v | grep 8091
seven@deMacBook-Pro logs %

**Comment by 1040968536** [comment]
> How do you determine if the start-up has failed?
> 
> I used JDK 17 and M1, and it ran okay.
> 
> <img alt="image" width="1218" src="https://private-user-images.githubusercontent.com/2684384/311900538-9d1402b7-ad08-4e00-9718-2abcc4e6096a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDc1ODIsIm5iZiI6MTcxMDIwNzI4MiwicGF0aCI6Ii8yNjg0Mzg0LzMxMTkwMDUzOC05ZDE0MDJiNy1hZDA4LTRlMDAtOTcxOC0yYWJjYzRlNjA5NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDEzNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVkMDliNzc4NDJlMGQ2ZTJlMWU5NWMyYzA0MGViNjRjODdiYzBmY2IyN2YxZGQ1Mzk3MTIxYTczM2VjY2RkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IaO_v1KplsKZHIRpZZ0WMEjkj4XZklJ8hU6xhtjqS7Q"> <img alt="image" width="643" src="https://private-user-images.githubusercontent.com/2684384/311900514-741d38fe-2604-44d5-a244-56349f1fe2b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDc1ODIsIm5iZiI6MTcxMDIwNzI4MiwicGF0aCI6Ii8yNjg0Mzg0LzMxMTkwMDUxNC03NDFkMzhmZS0yNjA0LTQ0ZDUtYTI0NC01NjM0OWYxZmUyYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDEzNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTk2OTQ5N2EzMmI4NjhiNzE4MDJmZGUzZDc3MTYyMzg0ZWFjOWUxMGVlMzVjZTFjZjMyMWRmNDAyMDFiYjc2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vo2E9z471wBcIz3erxK-RCps4jaYm964wq6Gzr_XPsU">

我使用命令查询了 相应的端口状态 同时我无法访问 http://localhost:8091/
seven@deMacBook-Pro logs % netstat -anp tcp -v | grep 8091
seven@deMacBook-Pro logs % lsof -i :8091                  
seven@deMacBook-Pro logs %

**Comment by slievrly** [comment]
Are there any error logs in the log directory? /Users/seven/logs/seata/ *.log

**Comment by 1040968536** [comment]
> Are there any error logs in the log directory? /Users/seven/logs/seata/ *.log

并没有产生日志文件

**Comment by slievrly** [comment]
You can try deploying Seata using the Docker image they have published, which is based on Java 17.

**Comment by cnsponmas** [comment]
> > Are there any error logs in the log directory? /Users/seven/logs/seata/ *.log
> 
> 并没有产生日志文件

你可以看看/Users/seven/logs/目录下是否有seata文件夹，如果没有，可以手动新建一个，再尝试启动

**Comment by Yuanyulin2331** [comment]
@1040968536 ，请问解决了吗，我也有这个问题，能教教我吗，谢谢🙏

**Comment by by22Jy** [comment]
> @1040968536 ，请问解决了吗，我也有这个问题，能教教我吗，谢谢🙏



> > > Are there any error logs in the log directory? /Users/seven/logs/seata/ *.log
> > 
> > 
> > 并没有产生日志文件
> 
> 你可以看看/Users/seven/logs/目录下是否有seata文件夹，如果没有，可以手动新建一个，再尝试启动

这个可以解决
