### ISSUE TITLE
web控制台-->Saga状态机设计器页面乱码

### ISSUE THREAD

**Issue by yearnxiao** [apache/incubator-seata#6422]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
web控制台-->Saga状态机设计器页面静态资源没有配置为信任资源，导致请求相应的静态资源时被鉴权拦截返回401

### Ⅱ. Describe what happened

  
![20240315105314](https://github.com/apache/incubator-seata/assets/12027882/7cdae717-c804-4711-9915-dc9bf8b8676c)
![20240315105414](https://github.com/apache/incubator-seata/assets/12027882/3458e806-7c3d-43f0-a75c-9492c5a1ecd7)

10:58:24.143  INFO --- [                     main] [rpc.netty.NettyServerBootstrap] [               start]  [] : Server started, service listen port: 8091
10:58:24.162  INFO --- [                     main] [io.seata.server.ServerRunner  ] [                 run]  [] : 
 you can visit seata console UI on http://127.0.0.1:7091. 
 log path: /root/logs/seata.
10:58:24.163  INFO --- [                     main] [io.seata.server.ServerRunner  ] [                 run]  [] : seata server started in 645 millSeconds
10:58:28.712  INFO --- [     http-nio-7091-exec-1] [rBase.[Tomcat].[localhost].[/]] [                 log]  [] : Initializing Spring DispatcherServlet 'dispatcherServlet'
10:58:28.713  INFO --- [     http-nio-7091-exec-1] [.web.servlet.DispatcherServlet] [     initServletBean]  [] : Initializing Servlet 'dispatcherServlet'
10:58:28.714  INFO --- [     http-nio-7091-exec-1] [.web.servlet.DispatcherServlet] [     initServletBean]  [] : Completed initialization in 1 ms
10:58:29.104 ERROR --- [     http-nio-7091-exec-2] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource
10:58:29.176 ERROR --- [     http-nio-7091-exec-3] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource
10:58:29.197 ERROR --- [     http-nio-7091-exec-4] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource
10:58:29.283 ERROR --- [     http-nio-7091-exec-5] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource
10:58:29.329 ERROR --- [     http-nio-7091-exec-6] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource
10:58:33.999 ERROR --- [     http-nio-7091-exec-5] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource
10:58:44.478 ERROR --- [     http-nio-7091-exec-2] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource
10:58:47.623 ERROR --- [     http-nio-7091-exec-7] [ty.JwtAuthenticationEntryPoint] [            commence]  [] : Responding with unauthorized error. Message - Full authentication is required to access this resource

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 访问http://seata-server-IP:7091打开web console
2. 登陆系统，切换到【Saga状态机设计器页面】页面，即可发现页面内容无法正常加载

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  2.0.0
- Database version:
- OS(e.g. `uname -a`):
- Others: 镜像信息：seataio/seata-server:2.0.0

**Comment by liuqiufeng** [comment]
Currently, the token refresh function is not implemented, it may be that the token has expired, please refresh the page or log in again and try again.

**Comment by nobdy** [comment]
按文档 https://seata.apache.org/zh-cn/docs/ops/deploy-by-docker-compose/ 部署 v2.1.0 版本也可以重现。
通过以下方式可以解决此问题：
在 `application.yml` 的
```yml
  security:
    ignore:
      urls: ...
```
的 `urls` 中增加
```
,/**/*.json,/**/*.jpeg,/**/*.ttf,/**/*.woff*
```
然后重启容器即可。
