### ISSUE TITLE
关于 1.8.1 与 2.1.0 发布计划

### ISSUE THREAD

**Issue by ChinaJeckXu** [apache/incubator-seata#6425]
关于 1.8.1 与 2.1.0 版本发布计划目前有吗?

**Comment by funky-eyes** [comment]
Version 2.1 is expected to be released this month if it goes well

**Comment by ChinaJeckXu** [comment]
> Version 2.1 is expected to be released this month if it goes well

I'm surprised that I'm still working hard in the early morning. I'm looking forward to the upcoming version, including but not limited to 1.8.1 and 2.1.0.
