### ISSUE TITLE
seata事务回滚成功了,但是undo_log表中无数据

### ISSUE THREAD

**Issue by junliudr** [apache/incubator-seata#6434]
seata-server 1.5.1   seata客户端 1.8.0  事务回滚成功,undo_log表中无数据

**Comment by funky-eyes** [comment]
After a successful rollback, the undolog table itself will not have data

**Comment by junliudr** [comment]
这个是正常得么  但我想让他有记录 这个可以么

**Comment by junliudr** [comment]
09:26:48.813 [HSFBizProcessor-DEFAULT-6-thread-49] INFO  [ea1ae6960117108116087975286d02cb] i.s.tm.api.DefaultGlobalTransaction Line:117 - Begin new global transaction [15.8.9.0:8091:27521562253023775]
09:26:48.814 [HSFBizProcessor-DEFAULT-6-thread-49] INFO  [ea1ae6960117108116087975286d02cb] c.e.c.m.i.s.i.IntegralRewardRuleService Line:76  - 当前的XID:15.8.9.0:8091:27521562253023775
09:26:48.859 [HSFBizProcessor-DEFAULT-6-thread-49] INFO  [ea1ae6960117108116087975286d02cb] io.seata.rm.AbstractResourceManager Line:73  - branch register success, xid:15.8.9.0:8091:27521562253023775, branchId:27521562253023777, lockKeys:liujun_test:68
09:26:48.874 [HSFBizProcessor-DEFAULT-6-thread-49] INFO  [ea1ae6960117108116087975286d02cb] i.s.tm.api.DefaultGlobalTransaction Line:171 - transaction 15.8.9.0:8091:27521562253023775 will be rollback
09:26:48.896 [rpcDispatch_RMROLE_1_3_4] INFO  [] i.s.c.r.p.c.RmBranchRollbackProcessor Line:56  - rm handle branch rollback process:BranchRollbackRequest{xid='15.8.9.0:8091:27521562253023775', branchId=27521562253023777, branchType=AT, resourceId='jdbc:mysql://11/member_pressure', applicationData='{"skipCheckLock":true}'}
09:26:48.896 [rpcDispatch_RMROLE_1_3_4] INFO  [] io.seata.rm.AbstractRMHandler Line:123 - Branch Rollbacking: 15.8.9.0:8091:27521562253023775 27521562253023777 jdbc:mysql://11/member_pressure
09:26:48.938 [rpcDispatch_RMROLE_1_3_4] INFO  [] i.s.r.d.undo.AbstractUndoLogManager Line:338 - xid 15.8.9.0:8091:27521562253023775 branch 27521562253023777, undo_log deleted with GlobalFinished
09:26:48.941 [rpcDispatch_RMROLE_1_3_4] INFO  [] i.s.rm.datasource.DataSourceManager Line:124 - branch rollback success, xid:15.8.9.0:8091:27521562253023775, branchId:27521562253023777
09:26:48.941 [rpcDispatch_RMROLE_1_3_4] INFO  [] io.seata.rm.AbstractRMHandler Line:131 - Branch Rollbacked result: PhaseTwo_Rollbacked
09:26:48.957 [HSFBizProcessor-DEFAULT-6-thread-49] INFO  [ea1ae6960117108116087975286d02cb] i.s.tm.api.DefaultGlobalTransaction Line:209 - transaction end, xid = 15.8.9.0:8091:27521562253023775
09:26:48.958 [HSFBizProcessor-DEFAULT-6-thread-49] INFO  [ea1ae6960117108116087975286d02cb] i.s.tm.api.DefaultGlobalTransaction Line:193 - [15.8.9.0:8091:27521562253023775] rollback status: Rollbacked

**Comment by funky-eyes** [comment]
You can keep it from being deleted by modifying the source code
