### ISSUE TITLE
seata博客文档部分图片不显示

### ISSUE THREAD

**Issue by lincan2017** [apache/incubator-seata#6443]
文档地址：https://seata.apache.org/zh-cn/blog/seata-raft-detailed-explanation/
![image](https://github.com/apache/incubator-seata/assets/26345280/0537ed16-df03-4c60-9d43-8b3a7490aff7)
![image](https://github.com/apache/incubator-seata/assets/26345280/f84374cb-57ee-4050-a52b-6d50520e4744)

**Comment by lincan2017** [comment]
![image](https://github.com/apache/incubator-seata/assets/26345280/f917e314-22de-456c-ad09-f2dddfbe942c)

**Comment by funky-eyes** [comment]
I'll deal with it in a while.
