### ISSUE TITLE
Undolog Packet for query is too large when table longblob field more than 40MB

### ISSUE THREAD

**Issue by jsbxyyx** [apache/incubator-seata#6451]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Packet for query is too large (83,886,137 > 67,108,864). You can change this value on the server by setting the 'max_allowed_packet' variable.

```
create table test (
id int primary key,
name varchar(45),
file longblob
)
```

```
insert into test(id, name file) values(1, 'name', '<binary 40MB>');
```

```
update test set file = '<binary 40MB>', name = 'name2' where id = 1;
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
From what I see, the issue described is a solution. The default value for max_allowed_packet is 64M, yet you're describing storage of 40M, which seems to have some gap. Additionally, is the oversized transaction mentioned in the issue something encountered in a real-world scenario?

**Comment by jsbxyyx** [comment]
场景：通过数据库来保存附件。
Scenes：Save attachments through database. 

更新语句时，前置镜像 + 后置镜像 > 64MB
before image + after image  > 64MB, when update

**Comment by leizhiyuan** [comment]
Storing attachments in a database is not a good practice. It is recommended to use object storage instead. The database stores the address of the storage location.
数据库保存附件不是一个好的实践，建议自己走对象存储。数据库存储地址
