### ISSUE TITLE
seata2.0如何使用@BusinessActionContextParameter传入对象实体并使用BusinessActionContext进行获取？

### ISSUE THREAD

**Issue by hhf19906** [apache/incubator-seata#6454]
@TwoPhaseBusinessAction(name = "decrease", commitMethod = "confirm", rollbackMethod = "cancel",useTCCFence = false)
String decrease( @BusinessActionContextParameter("inventoryDTO") InventoryDTO inventoryDTO);

 InventoryDTO inventoryDTO = (InventoryDTO) ctx.getActionContext("inventoryDTO");  
这样子获取到为空

**Comment by slievrly** [comment]
Is the annotation mentioned above on the interface class or the implementation class?

**Comment by hhf19906** [comment]
在接口上标注的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月6日(星期六) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/incubator-seata] ***@***.***传入对象实体并使用BusinessActionContext进行获取？ (Issue #6454)















上面提到的注释是在接口类上还是在实现类上？

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
您收到此消息是因为您创建了线程。消息ID:<阿帕奇/英库巴·赛塔/问题/ 6454 / ***@***.***和&gt;

**Comment by funky-eyes** [comment]
Please use it in the implementation class
