### ISSUE TITLE
适配kingbase数据库

### ISSUE THREAD

**Issue by zerowindy** [apache/incubator-seata#6455]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
系统建设需要，要使用kingbase数据库，并在AT模式下，实现分布式事务管理

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
Thank you very much for your feedback. We have collected your requirements.

**Comment by z6135** [comment]
需求相同，系统建设需要，要使用kingbase数据库，并在AT模式下，实现分布式事务管理。

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/pull/6876
