### ISSUE TITLE
是否可以出一个AT模式推荐的性能约束要求。

### ISSUE THREAD

**Issue by lin1005q** [apache/incubator-seata#6457]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

如果不考虑tc tm 的资源配置，仅在默认的60s全局事务超时下，一般的分支事务推荐在多大量级？
比如分支应在20个以内？ 单个分支的锁表数不超过10？整个链路涉及的上下游不超过10？  超过这些就推荐使用tcc或者异步。 

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by slievrly** [comment]
From a business perspective, it is quite challenging to provide suggested values here, but it may be feasible to add the potential performance loss incurred by the Seata framework itself in future considerations. As you mentioned, the 60 seconds here encompasses the time taken for the execution of business operations, which is contingent upon the execution times of the business logic and SQL executions.

**Comment by lin1005q** [comment]
OK
