### ISSUE TITLE
请问最新版本可以不依赖spring框架独立使用seata吗？

### ISSUE THREAD

**Issue by stevenniu9527** [apache/incubator-seata#6461]
请问最新版本可以不依赖spring框架独立使用seata吗？
比如使用的IOC框架是dropwizard如何使用seata？有没有类似的使用样例

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata-samples/tree/master/at-sample/at-api

**Comment by stevenniu9527** [comment]
邮件已经收到，我会尽快查看，谢谢

**Comment by stevenniu9527** [comment]
这个只是AT模式吧？其他模式怎么使用，比如tcc模式如何通过api方式使用？
