### ISSUE TITLE
seata2.0.0 在[lock_table]数据表适配sqlserver数据库的插入操作sql中存在错误

### ISSUE THREAD

**Issue by deung** [apache/incubator-seata#6468]
seata2.0.0 在[lock_table]数据表适配sqlserver数据库的 INSERT_LOCK_SQL_SQLSERVER 插入操作sql代码中缺少了[status]字段对应的占位符[?]，如下图所示：
![seata代码异常](https://github.com/apache/incubator-seata/assets/46589534/8982ec59-22fb-4b97-8965-f99cffca8e40)

**Comment by funky-eyes** [comment]
Can you commit a PR to fix it?

**Comment by deung** [comment]
我试一下
