### ISSUE TITLE
seata-setup.sh脚本中JAVA_OPT判断代码还是有问题，https://github.com/apache/incubator-seata/blob/2.x/distribution/bin/seata-setup.sh 在mac 的14系统下还是报错

### ISSUE THREAD

**Issue by CodeXiaoHan** [apache/incubator-seata#6482]
这是原来提的问题
https://github.com/apache/incubator-seata/releases/download/v2.0.0/seata-server-2.0.0.zip

以下代码是有问题的代码

JAVA_MAJOR_VERSION=$($JAVACMD -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}' | awk -F '.' '{print $1}')
if [[ "$JAVA_MAJOR_VERSION" -eq "1" ]] ; then
JAVA_MAJOR_VERSION=$($JAVACMD -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}' | awk -F '.' '{print $2}')
fi
if [[ "$JAVA_MAJOR_VERSION" -ge "9" ]] ; then
JAVA_OPT="${JAVA_OPT} -Xlog:gc*:file=${LOG_HOME}/seata_gc.log:time,tags:filecount=10,filesize=102400"
elif [[ "$JAVA_MAJOR_VERSION" -ge "17" ]] ; then
JAVA_OPT="${JAVA_OPT} -Xlog:gc=trace:file=${LOG_HOME}/seata_gc.log:time,tags:filecount=10,filesize=10M"
else
JAVA_OPT="${JAVA_OPT} -Xloggc:${LOG_HOME}/seata_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC"
fi

这里很简单的问题，if 条件写的有问题。

换成下面这个在mac的14系统 英特尔芯片 还是报错
https://github.com/apache/incubator-seata/blob/2.x/distribution/bin/seata-setup.sh
下面这段是有问题的代码：
JAVA_MAJOR_VERSION=$($JAVACMD -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}' | awk -F '.' '{print $1}')
if [[ "$JAVA_MAJOR_VERSION" -eq "1" ]] ; then
  JAVA_MAJOR_VERSION=$($JAVACMD -version 2>&1 | sed '1!d' | sed -e 's/"//g' | awk '{print $3}' | awk -F '.' '{print $2}')
fi
if [[ "$JAVA_MAJOR_VERSION" -ge "9" ]] ; then
  JAVA_OPT="${JAVA_OPT} -Xlog:gc*:file=${LOG_HOME}/seata_gc.log:time,tags:filecount=10,filesize=10M"
else
  JAVA_OPT="${JAVA_OPT} -Xloggc:${LOG_HOME}/seata_gc.log -verbose:gc -XX:+PrintGCDetails  -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC"
fi

错误信息：
seata-setup.sh: line 143: [[: 142:: syntax error in expression (error token is ":")
seata-setup.sh: line 146: [[: 142:: syntax error in expression (error token is ":")
<img width="1560" alt="iShot_2024-04-17_16 30 09" src="https://github.com/apache/incubator-seata/assets/17893162/dfa19917-467e-432e-a261-8f3ad36b90f6">

**Comment by ptyin** [comment]
Can you insert the following line before lo.142 to debug it? I guess it is mishandling of unexpected java version.

```shell
JAVA_VERSION_OUTPUT=$($JAVACMD -version 2>&1)
echo "Java Version Output: $JAVA_VERSION_OUTPUT"
JAVA_MAJOR_VERSION=$(echo "$JAVA_VERSION_OUTPUT" | sed '1!d' | sed -e 's/"//g' | awk '{print $3}' | awk -F '.' '{print $1}')
echo "Parsed Java Major Version: $JAVA_MAJOR_VERSION"
```

**Comment by CodeXiaoHan** [comment]
> Can you insert the following line before lo.142 to debug it? I guess it is mishandling of unexpected java version.
> 
> ```shell
> JAVA_VERSION_OUTPUT=$($JAVACMD -version 2>&1)
> echo "Java Version Output: $JAVA_VERSION_OUTPUT"
> JAVA_MAJOR_VERSION=$(echo "$JAVA_VERSION_OUTPUT" | sed '1!d' | sed -e 's/"//g' | awk '{print $3}' | awk -F '.' '{print $1}')
> echo "Parsed Java Major Version: $JAVA_MAJOR_VERSION"
> ```
thank you,
shell debug :
Parsed Java Major Version: 144 .
<img width="929" alt="iShot_2024-04-17_20 51 32" src="https://github.com/apache/incubator-seata/assets/17893162/5b43f89b-4166-4d9b-a54e-e8b883c479d8">
but , run java -version :  1.8.0_401
<img width="895" alt="iShot_2024-04-17_20 53 59" src="https://github.com/apache/incubator-seata/assets/17893162/7a0f1716-fbe1-402d-a134-6b381636baac">

**Comment by CodeXiaoHan** [comment]
I know now, it's because I'm using the built-in JDK in Mac, which prevents this shell script from processing. Just replace it with your own JDK and it will be okay

**Comment by CodeXiaoHan** [comment]
I know now, it's because I'm using the built-in JDK in Mac, which prevents this shell script from processing. Just replace it with your own JDK and it will be okay。

**Comment by CodeXiaoHan** [comment]
I know now, it's because I'm using the built-in JDK in Mac, which prevents this shell script from processing. Just replace it with your own JDK and it will be okay

**Comment by CodeXiaoHan** [comment]
I know now, it's because I'm using the built-in JDK in Mac, which prevents this shell script from processing. Just replace it with your own JDK and it will be okay。

**Comment by ptyin** [comment]
> I know now, it's because I'm using the built-in JDK in Mac, which prevents this shell script from processing. Just replace it with your own JDK and it will be okay。

Nice to hear that ;)
