### ISSUE TITLE
seata-server 2.0， saga 模式下报错 Global lock wait timeout

### ISSUE THREAD

**Issue by fengshaokun** [apache/incubator-seata#6485]
### Cause: io.seata.rm.datasource.exec.LockWaitTimeoutException: Global lock wait timeout
; Global lock wait timeout] with root cause

io.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:172.17.4.71:8091:4747306011800780953, lockKeys:account:1

**Comment by ptyin** [comment]
Could you please show the related code or at least provide the state machine JSON.

**Comment by funky-eyes** [comment]
关闭数据源自动代理
