### ISSUE TITLE
如何使一个不需要seata介入的方法去掉异常：java.lang.RuntimeException: try to proceed invocation error

### ISSUE THREAD

**Issue by zsp419** [apache/incubator-seata#6488]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
对于一个没有添加@GlobalTransactional注解的GET方式的http后台接口，这个接口是不希望seata介入的，由于业务逻辑需要抛出自定义异常，但是每次都会被java.lang.RuntimeException: try to proceed invocation error这个异常覆盖，导致前端接收不到异常信息，请问如何去掉这个异常，只抛出我自定义的异常

**Comment by funky-eyes** [comment]
降级，这是2.0的一个bug导致的。
Try downgrade, it was caused by a bug in 2.0.

**Comment by zsp419** [comment]
我前段时间刚升级到2.0，又要降级吗。。那请问降到哪个版本合适

**Comment by zsp419** [comment]
有没有不降级的办法， 降级是个比较大的动作，怕出问题

**Comment by funky-eyes** [comment]
> 我前段时间刚升级到2.0，又要降级吗。。那请问降到哪个版本合适

1.8,或者等待2.1版本发布

**Comment by zsp419** [comment]
请问2.1大概什么时间发布，我看看能不能等一下，时间太长的话，就先降级了

**Comment by zsp419** [comment]
> > 我前段时间刚升级到2.0，又要降级吗。。那请问降到哪个版本合适
> 
> 1.8,或者等待2.1版本发布

请问2.1大概什么时间发布，我看看能不能等一下，时间太长的话，就先降级了

**Comment by funky-eyes** [comment]
最快可能在五月底，apache孵化器中的发布时间是不受控的，要看投票情况
As soon as the end of May, the release time in the apache incubator is uncontrolled, depending on the voting situation

**Comment by kcsap** [comment]
都2.0版本了,没有考虑这个问题吗?

**Comment by funky-eyes** [comment]
> 都2.0版本了,没有考虑这个问题吗?

已经修复了，就2.0有这个问题，其余版本都没有，并且不需要seata介入的方法自行查看globaltransaction注解上的事务传播配置

**Comment by KunBoy5240** [comment]
> > 我前段时间刚升级到2.0，又要降级吗。。那请问降到哪个版本合适
> 
> 1.8，或者等待2.1版本发布

1.8也是有这个问题的存在呢

**Comment by funky-eyes** [comment]
> > > 我前段时间刚升级到2.0，又要降级吗。。那请问降到哪个版本合适
> > 
> > 
> > 1.8，或者等待2.1版本发布
> 
> 1.8也是有这个问题的存在呢

1.8都没重构这块，不可能存在

**Comment by KunBoy5240** [comment]
> > > > 我前段时间刚升级到2.0，又要降级吗。。那请问降到哪个版本合适
> > > 
> > > 
> > > 1.8，或者等待2.1版本发布
> > 
> > 
> > 1.8也是有这个问题的存在呢
> 
> 1.8都没重构这块，不可能存在

![image](https://github.com/user-attachments/assets/623da301-5a33-4373-a31a-20fd28672fe3)

**Comment by funky-eyes** [comment]
说的是client 1.8，不是server1.8，错误发生在client，当然是client降级

**Comment by funky-eyes** [comment]
@KunBoy5240

**Comment by 601881076** [comment]
> > 都2.0版本了，没有考虑这个问题吗？
> 
> 已经修复了，就2.0有这个问题，其余版本都没有，而且不需要seata介入的方法自行查看globaltransaction注解上的事务传播配置

2025年了，现在maven中心仓库中最高也只有2.0版本，还是只能降级处理吗？

**Comment by funky-eyes** [comment]
> > > 都2.0版本了，没有考虑这个问题吗？
> > 
> > 
> > 已经修复了，就2.0有这个问题，其余版本都没有，而且不需要seata介入的方法自行查看globaltransaction注解上的事务传播配置
> 
> 2025年了，现在maven中心仓库中最高也只有2.0版本，还是只能降级处理吗？

2025年了，还不知道seata已经迁到apache下了吗？即便你搜索seata-all也会有groupId是org.apache.seata的seata-all这个依赖。

**Comment by 601881076** [comment]
> > > > 都2.0版本了，没有考虑这个问题吗？
> > > 
> > > 
> > > 已经修复了，就2.0有这个问题，其余版本都没有，而且不需要seata介入的方法自行查看globaltransaction注解上的事务传播配置
> > 
> > 
> > 2025年了，现在maven中心仓库中最高也只有2.0版本，还是只能降级处理吗？
> 
> 2025年了，还不知道seata已经迁到apache下了吗？即便你搜索seata-all也会有groupId是org.apache.seata的seata-all这个依赖。

OK，已改好。
