### ISSUE TITLE
XA模式下查询不到数据

### ISSUE THREAD

**Issue by wuchaococo** [apache/incubator-seata#6490]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Oracle数据库下，使用XA模式，对于写入的数据，再次查询（同一个事务内）回出现查询不到的问题。
但如果不适用SEATA，基于原生XA模式编程是可以查询到的，
目前不清楚问题在哪里

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
如何证明你的insert和select在一个本地事务下？
How to prove that your insert and select are in a local transaction?

**Comment by tanyaofei** [comment]
再开一个本地事务

**Comment by wuchaococo** [comment]
一个本地事务：
1 先写入一条数据
2 然后查询，没有查询出来
我发现写入操作和查询都记录了一下分支事务
日志中client报：phasetwo_commitfailed_XAER_NOTA_Retryable,
