### ISSUE TITLE
seata AT模式，事务回滚失效

### ISSUE THREAD

**Issue by anxietyFan** [apache/incubator-seata#6491]
seata 事务回滚失效，业务表数据并没有回滚，undo_log 中无任何日志信息，服务日志信息显示回滚已经成功。不知道是不是数据源代理问题。

**Comment by funky-eyes** [comment]
https://seata.apache.org/zh-cn/docs/overview/faq/#42

**Comment by anxietyFan** [comment]
并不是这个原因，有没有其他可能

**Comment by funky-eyes** [comment]
你确定你分析了？你确定你有branchid的日志输出？
Are you sure you analyzed it? Are you sure you have the log output of branchid?
