### ISSUE TITLE
task: Improve the test case coverage of [rocketmq] module to 70%

### ISSUE THREAD

**Issue by lightClouds917** [apache/incubator-seata#6506]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

The test case coverage of [rocketmq] module is 30.61%, We need to go up to 70% to improve the robustness and stability of our code.
[rocketmq]模块的测试用例覆盖率为30.61%，我们需要提高到70%，以提高代码的健壮性和稳定性。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information

You can get some help from:
https://seata.apache.org/docs/developers/contributor-guide/test-coverage-guide_dev
https://seata.apache.org/blog/how-to-write-unit-tests

**Comment by LPBruce** [comment]
please assign to me.

**Comment by kachida** [comment]
please assign it to me

**Comment by psxjoy** [comment]
@kachida Hi, have you already started working on this issue? If not, I’d be glad to take over and continue with this part.

**Comment by psxjoy** [comment]
@funky-eyes Hi, I really interested in and want to do this issue, can you assign it to me？

**Comment by xingfudeshi** [comment]
> @funky-eyes Hi, I really interested in and want to do this issue, can you assign it to me？

Look forward to your PR submission.
