### ISSUE TITLE
task: Improve the test case coverage of [integration-tx-api] module to 70%

### ISSUE THREAD

**Issue by lightClouds917** [apache/incubator-seata#6507]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

The test case coverage of [integration-tx-api] module is 18.33%, We need to go up to 70% to improve the robustness and stability of our code.
[integration-tx-api]模块的测试用例覆盖率为18.33%，我们需要提高到70%，以提高代码的健壮性和稳定性。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

## Other related information
You can get some help from:
https://seata.apache.org/docs/developers/contributor-guide/test-coverage-guide_dev
https://seata.apache.org/blog/how-to-write-unit-tests

**Comment by azatyamanaev** [comment]
Hello. Can you assign this issue to me?

**Comment by azatyamanaev** [comment]
I made a pull request for this issue. Can you review it?

**Comment by xingfudeshi** [comment]
> Hello. Can you assign this issue to me?

Hi.This issue has assigned to you.Thanks for your work.
