### ISSUE TITLE
XA事务模式下写入的查询不到数据

### ISSUE THREAD

**Issue by wuchaococo** [apache/incubator-seata#6510]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.
Oracle数据库下，使用XA模式，对于写入的数据，再次查询（同一个事务内）回出现查询不到的问题。
基本业务代码如下，一个本地事务：
1 先写入一条数据
2 然后查询，没有查询出来
目前发现写入操作和查询都记录了一下分支事务
日志中client报：phasetwo_commitfailed_XAER_NOTA_Retryable,

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):1.8
- Seata client/server version:   1.8.0
- Database version: oracle11g
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
说明你的读写不在一个本地事务下
Explain that your reading and writing are not under a local transaction

**Comment by wuchaococo** [comment]
不太明白，什么意思，这两个操作是同一个数据源

**Comment by funky-eyes** [comment]
不在一个本地事务中时，由于事务的隔离性，另一个connection是不可能查出来的。在读写场景都在一个服务下，没有跨服务时可以加@transactional注解解决

**Comment by wuchaococo** [comment]
那如果本地事务多个数据源怎么处理？
