### ISSUE TITLE
[druid 版本升级]请问下个版本大概多久发布，依赖的druid会升级到最新版本嘛?

### ISSUE THREAD

**Issue by God-Gan** [apache/incubator-seata#6522]
目前seata2.0.0使用的druid版本是1.2.7,但是这个版本的druid解析postgresql的 FETCH FIRST 1 rows only 语句会出现语法错误，druid社区已经在1.2.20+版本解决了这个问题：https://github.com/alibaba/druid/commit/e40032696e126e33b578203e382aed68de42f753
请问一下下一个seata版本大概多久升级，其中依赖的druid版本会升级到最新版本吗？

**Comment by funky-eyes** [comment]
你可以提交一个pr来解决这个问题吗？
Can you submit a PR to solve this problem?

**Comment by God-Gan** [comment]
请问是直接修改dependencies目录下pom.xml中druid的版本到1.2.22，然后提交pr就可以了么？

**Comment by funky-eyes** [comment]
> 请问是直接修改dependencies目录下pom.xml中druid的版本到1.2.22，然后提交pr就可以了么？

是的，然后我们来看下测试用例是否都正常通过，并且建议你升级后本地也进行一些测试
Yes, then let's see if the test cases pass normally, and it is recommended that you do some tests locally after the upgrade.

**Comment by slievrly** [comment]
@God-Gan Please fix the UT error.

**Comment by God-Gan** [comment]
好的，我会找时间尝试fix一下CI的问题 @slievrly

**Comment by God-Gan** [comment]
@funky-eyes 请问seata-all依赖内置的druid包是专门用来解析sql的么？这个包的版本也是跟着pom.xml的druid版本同步升级吗。

**Comment by funky-eyes** [comment]
> @funky-eyes 请问seata-all依赖内置的druid包是专门用来解析sql的么？这个包的版本也是跟着pom.xml的druid版本同步升级吗。

yes
