### ISSUE TITLE
seata 1.8版本 ，服务端部署在k8s上面，使用redis做注册中心，客户端服务启动连接获取注册列表时候因redis key过多超时无法启动问题

### ISSUE THREAD

**Issue by zhanhw** [apache/incubator-seata#6527]
使用redis做注册中心，因为1.5版本时候 redis的结构变了，改成String数据结构存储，这个时候客户端去获取注册列表的时候去扫描key前缀就特别慢，这个有什么办法解决吗？哪位大佬能帮解决下呢？
![image](https://github.com/apache/incubator-seata/assets/37291088/f3bc7b70-7dcb-46e0-965c-d5f7dbb31822)

**Comment by funky-eyes** [comment]
使用的api是scan，每次只扫10条也撑不住？每个key的ttl只有5s（server存活会一直续），你的server和client数量很多吗？导致请求放大了？
The API being used is "scan," which scans only 10 records per request. Each key has a TTL of only 5 seconds, with the server continuously renewing its existence. Are there a large number of servers and clients, causing request amplification?

**Comment by zhanhw** [comment]
> 使用的api是scan，每次只扫10条也撑不能？每个key的ttl只有5s（服务器至少会一直续），你的服务器和客户端数量很多吗？导致请求放大了？ 正在使用的API是“扫描”，每个请求仅扫描 10 条记录。每个密钥的 TTL 仅为 5 秒，服务器会不断更新其存在。是否存在大量服务器和客户端，导致请求放大？

我们目前生产客户端的配置是这样的 
![image](https://github.com/apache/incubator-seata/assets/37291088/2f0fb16c-b5c9-4eda-8ace-deac57de4464)
![image](https://github.com/apache/incubator-seata/assets/37291088/a4554764-e8d8-4098-b476-d964e0b86a34)

然后因为seata server的容器ip不是固定的，重启会变，这里去scan  key肯定是模糊去匹配的，然后客户端启动可能几分钟都扫描不到对应的key，就卡在那里了，我们生产环境的key比较多，然后scan起来就比较慢了 
![image](https://github.com/apache/incubator-seata/assets/37291088/7d3b977a-9842-41d0-b3e3-1a6d67dc54c7)

**Comment by zhanhw** [comment]
> 使用的api是scan，每次只扫10条也撑不能？每个键的ttl只有5s（服务器至少会一直续），你的服务器和客户端数量很多吗？导致请求放大了？ 正在使用的API是“扫描”，每个请求仅扫描10条记录。每个密钥的TTL 5秒，服务器会不断更新其存在。是否存在大量服务器和客户端，导致请求放大？

因为seata服务器的容器ip不是固定的，重启就会变，这里扫描键肯定是模糊去匹配的，然后客户端启动可能几分钟都扫描不到对应的键，就卡在那里了，我们的生产环境的key比较多，然后扫描起来就比较慢了 我们的这个注册中心和生产的redis公用的，服务器和客户端数量不多，其他的key比较多
![image](https://github.com/apache/incubator-seata/assets/37291088/b8e51d3a-8b27-4824-8621-f64894666053)

**Comment by zhanhw** [comment]
这种有什么别的解决方案吗？通过客户端指定注册列表，为啥redis改造成这样的结构呢？hash在seata节点过多时候获取map很慢吗？

**Comment by funky-eyes** [comment]
优雅下线时会触发主动删key，scan模糊匹配也是匹配到后才响应，这个过程你可以自行用redis-cli看下大概耗时多久吗？scan registry.redis.*
还有你为什么不切换一个redis db，key总体较少的给seata使用？

**Comment by zhanhw** [comment]
> 优雅下线时会触发主动删key，scan模糊匹配也是匹配到后才响应，这个过程你可以自行用redis-cli看下大概耗时多久吗？scan registry.redis.* 还有你为什么不切换一个redis db，key总体较少的给seata使用？

好的，感谢建议，我知道了

**Comment by funky-eyes** [comment]
> 这种有什么别的解决方案吗？通过客户端指定注册列表，为啥redis改造成这样的结构呢？hash在seata节点过多时候获取map很慢吗？

hash最大的问题是残留，在k8s下比如出现一些非优雅的下线，导致field残留无法过期，然后使用hgetall获取服务列表就会有很多无用地址。
The biggest issue with hashing is residue. For instance, under Kubernetes, if there are some non-graceful shutdowns leading to residual fields that don't expire, using hgetall to retrieve the service list may result in numerous unused addresses.

**Comment by zhanhw** [comment]
> > 这种有什么别的解决方案吗？通过客户端指定注册列表，为啥redis改造成这样的结构呢？hash在seata节点过多时候获取map很慢吗？
> 
> hash最大的问题是残留，在k8s下比如出现一些非优雅的下线，导致field残留无法过期，然后使用hgetall获取服务列表就会有很多无用地址。 The biggest issue with hashing is residue. For instance, under Kubernetes, if there are some non-graceful shutdowns leading to residual fields that don't expire, using hgetall to retrieve the service list may result in numerous unused addresses.

好的，理解了，感谢
