### ISSUE TITLE
seata 1.8版本 在全局事务回滚时候，在通过pkColumnValueList获取Field出现数组下表越界，因为undo log中联合主键中的某个字段会出现多次，麻烦哪位大佬看到了帮看下具体是什么原因？

### ISSUE THREAD

**Issue by zhanhw** [apache/incubator-seata#6535]
我们业务中的一张主表是联合主键的（ id，fk_cust_id,billing_date） ，在业务报错全局事务回滚的时候，我们发现undo log中的 镜像数据里面的filed里面 联合主键中的某一个字段 fk_cust_id 出现了两次，这个会导致 我下面截图中的这部分代码 通过pkColumnValueList获取Field 会出现数组下标越界 Index: 1, Size: 1，因为前面的rowSize 取的是第一个pkNameList的值，第一个pkName就是 fk_cust_id 它的size=2，而其它的size=1 所以会出现数组下标越界，我想问下，为什么这种情况写入的undo log中会出现两个fk_cust_id字段 都是主键类型？
![undoLog](https://github.com/apache/incubator-seata/assets/37291088/900f25af-b4ef-4264-8678-899e87e49c5e)
![源码](https://github.com/apache/incubator-seata/assets/37291088/f241e6f3-fd7f-4736-8710-1598080c4025)
![联合主键](https://github.com/apache/incubator-seata/assets/37291088/f5871e12-7912-41db-9199-8e9fbfe75b84)
![lock详情](https://github.com/apache/incubator-seata/assets/37291088/0a043ef1-0f6d-45fa-a469-0e0dd6eda1eb)
![数组下表越界异常](https://github.com/apache/incubator-seata/assets/37291088/59a74c5b-870e-44d5-9a4e-714cb4dc1510)

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/pull/6077

**Comment by zhanhw** [comment]
> #6077

2.1版本中可以修复是吗？发布版本的时间大概是什么时候呢？

**Comment by funky-eyes** [comment]
> > #6077
> 
> 2.1版本中可以修复是吗？发布版本的时间大概是什么时候呢？

可以，但是要等2.1的rc版本，快的话月底，慢的话得六月多
Yes, but you have to wait for the rc version 2.1. If it is fast, it will be at the end of the month, and if it is slow, it will take more than June.
