### ISSUE TITLE
bytebuddy is not compatible with Java 21 versions

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#6542]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

![image](https://github.com/apache/incubator-seata/assets/8758457/079dd699-2099-4c04-8d06-0b57699ef9e8)

https://github.com/apache/incubator-seata/actions/runs/9073086963/job/24929657372

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
https://github.com/raphw/byte-buddy/issues/1396
我们应该将其升级到1.14.3版本及以上
We should upgrade it to 1.14.3 version and above
