### ISSUE TITLE
可以升级一下MySQL的驱动版本吗

### ISSUE THREAD

**Issue by Self-revolution** [apache/incubator-seata#6556]
可以升级一下MySQL的驱动版本吗，好像当前版本才到8.0.27，现在MySQL8.4这个LTS版本都出来了

**Comment by funky-eyes** [comment]
mysql driver属于gpl license，seata无法直接依赖其driver，你可以自行手动引入替换都是可以的
The mysql driver belongs to the gpl license, and seata cannot directly dependency on its driver. You can manually introduce and replace it yourself.

**Comment by ashuai5061** [comment]
> mysql driver属于gpl license，seata无法直接依赖其driver，你可以自行手动引入替换都是可以的 The mysql driver belongs to the gpl license, and seata cannot directly dependency on its driver. You can manually introduce and replace it yourself.

大佬,请问如何自行替换driver
