### ISSUE TITLE
undo_log 不能删除的问题

### ISSUE THREAD

**Issue by Foreach1997** [apache/incubator-seata#6573]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
替换数据库连接后新开的全局事务undo_log 不能删除的问题。

### Ⅱ. Describe what happened
AT模式下当有一台业务服务是分布式部署的，比如这个业务服务有一个容器a和容器b，去替换业务服务的数据库连接配置完成后，在容器a已经启动完成，有新的请求进来并且创建了分布式事务，容器b还没有进行重启更新配置信息。seata server开始进行异步通知分支事务提交异步删除undo_log,seata server请求到容器b上没有进行undo_log删除。
  If there is an exception, please attach the exception trace:
  Failed to find resource for ********
```
Just paste your stack trace here!
```
![微信截图_20240523163400](https://github.com/apache/incubator-seata/assets/35162283/7eda7cfa-06a2-4e7e-bb3f-7a259ee5304e)

### Ⅲ. Describe what you expected to happen
1.全局事务不应该成功提交而是正常回滚

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):
   ```
private void dealWithGroupedContexts(String resourceId, List<Phase2Context> contexts) {
        DataSourceProxy dataSourceProxy = dataSourceManager.get(resourceId);
        if (dataSourceProxy == null) {
            LOGGER.warn("Failed to find resource for {}", resourceId);
            return;
        }

        Connection conn;
        try {
            conn = dataSourceProxy.getPlainConnection();
        } catch (SQLException sqle) {
            LOGGER.error("Failed to get connection for async committing on {}", resourceId, sqle);
            return;
        }

        UndoLogManager undoLogManager = UndoLogManagerFactory.getUndoLogManager(dataSourceProxy.getDbType());

        // split contexts into several lists, with each list contain no more element than limit size
        List<List<Phase2Context>> splitByLimit = Lists.partition(contexts, UNDOLOG_DELETE_LIMIT_SIZE);
        splitByLimit.forEach(partition -> deleteUndoLog(conn, undoLogManager, partition));
    }
```
### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  Seata client：1.4.2
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
AT模式一阶段已经提交了事务结果，二阶段只需要删除undolog就可以了，undolog删除失败并不影响事务结果，所以并不应该由于undolog删除失败（你替换了数据源，该节点下找不到datasource进行删除undolog），而将不影响业务的且已经决议提交的事务再次进行回滚。
In AT mode, the first phase has already submitted the transaction result, and the second phase only needs to delete the undolog. The failure to delete the undolog does not affect the transaction result. Therefore, the transaction, which has been decided and committed, should not be rolled back again just because the undolog deletion failed (you replaced the data source, and the datasource cannot be found under this node to delete the undolog)

**Comment by funky-eyes** [comment]
而且你的版本应该不是1.5.2及以上版本，因为1.5.2开始负载均衡由xid上的serverip所决定，而下发到了b节点而不是a节点，说明决议的server跟创建事务begin时的server不是同一个。
And your version is probably not 1.5.2 or above, because starting from 1.5.2, load balancing is determined by the server ip on the xid. Sending it to node B instead of node A indicates that the server responsible for resolution is not the same as the one when the transaction was created with begin

**Comment by Foreach1997** [comment]
> AT模式一阶段已经提交了事务结果，二阶段只需要删除undolog就可以了，undolog删除失败并不影响事务结果，所以并不应该由于undolog删除失败（你替换了数据源，该节点下找不到datasource进行删除undolog），而将不影响业务的且已经决议提交的事务再次进行回滚。 In AT mode, the first phase has already submitted the transaction result, and the second phase only needs to delete the undolog. The failure to delete the undolog does not affect the transaction result. Therefore, the transaction, which has been decided and committed, should not be rolled back again just because the undolog deletion failed (you replaced the data source, and the datasource cannot be found under this node to delete the undolog)

如果这样不就可能会导致不知道当前事务是否正确的进行提交了吗？

**Comment by Foreach1997** [comment]
> 而且你的版本应该不是1.5.2及以上版本，因为1.5.2开始负载均衡由xid上的serverip所决定，而下发到了b节点而不是a节点，说明决议的server跟创建事务begin时的server不是同一个。 And your version is probably not 1.5.2 or above, because starting from 1.5.2, load balancing is determined by the server ip on the xid. Sending it to node B instead of node A indicates that the server responsible for resolution is not the same as the one when the transaction was created with begin

1.5.2以上版本的话 ，容器a开启的全局事务最终会在容器a上进行提交吗

**Comment by funky-eyes** [comment]
> > AT模式一阶段已经提交了事务结果，二阶段只需要删除undolog就可以了，undolog删除失败并不影响事务结果，所以并不应该由于undolog删除失败（你替换了数据源，该节点下找不到datasource进行删除undolog），而将不影响业务的且已经决议提交的事务再次进行回滚。 In AT mode, the first phase has already submitted the transaction result, and the second phase only needs to delete the undolog. The failure to delete the undolog does not affect the transaction result. Therefore, the transaction, which has been decided and committed, should not be rolled back again just because the undolog deletion failed (you replaced the data source, and the datasource cannot be found under this node to delete the undolog)
> 
> 如果这样不就可能会导致不知道当前事务是否正确的进行提交了吗？

哪里导致了不知道是否正确的提交？一阶段已经提交了，二阶段只是删个undolog跟事务结果没有任何影响
Where does the uncertainty about whether the submission is correct arise from? The first phase has already been submitted, and the second phase is just deleting an undolog, which has no impact on the transaction result.

**Comment by funky-eyes** [comment]
> > 而且你的版本应该不是1.5.2及以上版本，因为1.5.2开始负载均衡由xid上的serverip所决定，而下发到了b节点而不是a节点，说明决议的server跟创建事务begin时的server不是同一个。 And your version is probably not 1.5.2 or above, because starting from 1.5.2, load balancing is determined by the server ip on the xid. Sending it to node B instead of node A indicates that the server responsible for resolution is not the same as the one when the transaction was created with begin
> 
> 1.5.2以上版本的话 ，容器a开启的全局事务最终会在容器a上进行提交吗

谁在一阶段注册的分支事务，谁进行二阶段处理，如果这个节点在二阶段时不存在才会选择其他节点
Who registers the branch transaction in the first phase, who performs the second phase processing, and only if this node does not exist during the second phase will another node be selected.
