### ISSUE TITLE
使用 2.0.0 版本并且使用root用户操作会无法启动的问题。

### ISSUE THREAD

**Issue by guyangxizhao** [apache/incubator-seata#6589]
使用centos系统，root用户，如果下载zip后，直接解压启动，可能会无法启动。大概原因是无法创建/root/logs/seata 目录。
这是个小问题，不知道是不是bug。

**Comment by xingfudeshi** [comment]
Hi,it's not a bug.
It seems to be a user permission issue. You can adjust the permissions of seata server.sh. For example
```
chmod 777 ./bin/seata-server.sh

```
then try to run it again.
