### ISSUE TITLE
v2.0.0版本，使用redis作为store时，无法连接redis

### ISSUE THREAD

**Issue by guyangxizhao** [apache/incubator-seata#6590]
使用 redis作为store时，会报错：
`ERROR --- [TxTimeoutCheck_1_1] [io.seata.server.storage.redis.lock.RedisDistributedLocker] [acquireLock] []: The 192.168.9.0:8091 acquired the TxTimeoutCheck distributed lock failed.
==>
redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.`

操作步骤：
1.直接下载https://github.com/apache/incubator-seata/releases/download/v2.0.0/seata-server-2.0.0.zip
2.解压后 修改 配置文件：
<pre>
store:
    # support: file 、 db 、 redis 、 raft
    mode: redis
    session:
      mode: redis
    lock:
      mode: redis
    redis:
      mode: single
      password: password
      .....省略

</pre>

3.启动：
`sh bin/seata-server.sh -m redis`
然后就会报错 `NOAUTH Authentication required`

4.redis密码和host都没问题
<pre>
127.0.0.1:6379> auth password
OK
</pre>

这个是不是bug，怎么解决

**Comment by guyangxizhao** [comment]
使用 tar.gz 不报错可以正常使用

**Comment by Leerecently** [comment]
怎么解决的？我docker-compose部署也遇到这个问题了，指定变量STORE_MODE=redis。容器启动就是会报和你一样的错误
