### ISSUE TITLE
请问 2.1.0 什么时候发啊 等的花都要谢了 端午节前还有希望么

### ISSUE THREAD

**Issue by JavaLionLi** [apache/incubator-seata#6594]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by liuqiufeng** [comment]
It is already in the voting process. You can subscribe to the developer mailing list to follow the relevant progress

**Comment by bobbyz007** [comment]
不用等啊，自己克隆下代码到本地，直接clean install就行了

**Comment by JavaLionLi** [comment]
居然还没发

**Comment by JavaLionLi** [comment]
> 不用等啊，自己克隆下代码到本地，直接clean install就行了

不是正式版本不敢用啊
