### ISSUE TITLE
seata 2.x是否支持数据库密码加密功能？

### ISSUE THREAD

**Issue by a8159236** [apache/incubator-seata#6595]
1、seata 2.x是否支持数据库密码加密功能（直接password配置明文密码可能不安全）
mode = "db"的时候，使用mysql数据库，有单独的配置加密的参数吗？还是可以通过openssl生成密钥对，password直接配置成公钥就行？官方文档没有找到相关内容。
2、有相关的配置介绍和配置方法吗？

**Comment by a8159236** [comment]
![image](https://github.com/apache/incubator-seata/assets/32159630/defae03c-1eae-4c73-893f-3a926e477039)
![image](https://github.com/apache/incubator-seata/assets/32159630/74c3b39b-5af6-439f-956f-299cbbfc45ef)

**Comment by xingfudeshi** [comment]
Hi,seata supports this feature,Please refer to @funky-eyes 's answer

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/issues/2665
