### ISSUE TITLE
对于Oracle数据库中含有Timestamp字段的数据表无法进行二段校验

### ISSUE THREAD

**Issue by 897584724** [apache/incubator-seata#6598]
在进行回滚时，会进行数据校验，然而对于含有Timestamp字段的数据表，写到Undo_log表里的时候，只会保存timestamp字段中的秒之前的值到Undo_log里面，例如timestamp的值是2024-05-30 18:51:50:148381，那保存到Undo_log里面的值只有2024-05-30 18:51:50.0，然后回滚前校验seata会拿2024-05-30 18:51:50.0和2024-05-30 18:51:50:148381进行校验，然后就会校验不通过，导致无法回滚。需要设置seata:  client:undo: dataValidation: false ，放弃二段校验才能进行回滚

 

- java8
-seata2.0
-spring-cloud-starter-alibaba-seata 2021.0.5.0或者2021.0.6.0
- oracle 12c
- windows spring tool 4
- seata:  client:    undo:  log-serialization: fastjson

**Comment by 897584724** [comment]
![企业微信截图_20240603170252](https://github.com/apache/incubator-seata/assets/153274149/32f00d20-1f31-4b86-b195-4748d4b5ab11)

**Comment by 897584724** [comment]
不进行回滚前校验感觉会有坑，所以是否能修复这个问题？

**Comment by funky-eyes** [comment]
https://seata.apache.org/zh-cn/docs/overview/faq#41
