### ISSUE TITLE
mybatis调用Oracle存储过程开启事务报错

### ISSUE THREAD

**Issue by 897584724** [apache/incubator-seata#6604]
### Ⅰ. Issue Description
mybatis调用Oracle
![Uploading 微信截图_20240607173320.png…]()
![Uploading 微信截图_20240607173407.png…]()
存储过程开启事务报错
 

-jdk8
- Seata 2.0   spring-cloud-starter-alibaba-seata 2021.0.5.0
- Database version:Oracle11g
- Linux

**Comment by funky-eyes** [comment]
不支持该功能
not support

**Comment by 897584724** [comment]
报错信息expect has not xid, but was:10.22.1.12:8091:6918058001194657137

**Comment by slievrly** [comment]
Stored procedures or triggers are not supported.
