### ISSUE TITLE
seata客户端引入GlobalTransactionScanner出现stackOverFlow

### ISSUE THREAD

**Issue by RAN268** [apache/incubator-seata#6630]
项目引入seata-all：1.3.0版本，实现GlobalTransactionScanner的bean
<img width="770" alt="截屏2024-06-25 11 20 16" src="https://github.com/apache/incubator-seata/assets/76766072/0ae91afe-094c-4b50-b493-388edd3fee13">

项目启动出现stackOverFlow的错误
<img width="1224" alt="截屏2024-06-25 11 21 47" src="https://github.com/apache/incubator-seata/assets/76766072/ae69ca5a-2e07-4b8f-a703-f67b844e92d2">
<img width="1288" alt="截屏2024-06-25 11 22 31" src="https://github.com/apache/incubator-seata/assets/76766072/0795aa68-01be-4d94-88f2-f153ce706276">

**Comment by funky-eyes** [comment]
栈深度导致该问题，请升级至1.4.2及以上版本
Stack depth causes this problem, please upgrade to 1.4.2 and above

**Comment by RAN268** [comment]
seata-all：2.0.0依然有栈溢出的问题

**Comment by RAN268** [comment]
seata-all：2.0.0依然是相同的问题
[
<img width="1238" alt="截屏2024-06-25 11 37 23" src="https://github.com/apache/incubator-seata/assets/76766072/2c2e4458-16f0-405d-80f2-a85517ddd1a2">
](url)

**Comment by RAN268** [comment]
seata-all：2.0.0依然有栈溢出的问题
<img width="1238" alt="截屏2024-06-25 11 37 23" src="https://github.com/apache/incubator-seata/assets/76766072/391b7a97-1a24-4928-9d72-df3c6ff0a839">
