### ISSUE TITLE
启动失败，但是找不到日志

### ISSUE THREAD

**Issue by eocoo** [apache/incubator-seata#6643]
怀疑启动失败了，但是这个提示的目录下并没有日志内容啊

```txt
xxx@Java:~/sys$ docker logs seata
/seata-server
apm-skywalking not enabled
JMX disabled
/usr/java/openjdk-17/bin/java  -Dlog.home=/root/logs/seata -server -Dloader.path=/seata-server/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xlog:gc*:file=/root/logs/seata/seata_gc.log:time,tags:filecount=10,filesize=102400 -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=7 -Dapp.home=/seata-server -Dbasedir=/seata-server  -Dspring.config.additional-location=/seata-server/conf/ -Dspring.config.location=/seata-server/conf/application.yml -Dlogging.config=/seata-server/conf/logback-spring.xml -jar /seata-server/target/seata-server.jar  >> /dev/null 2>&1 &
seata-server is starting, you can check the /root/logs/seata/ *.log
```

**Comment by funky-eyes** [comment]
`/usr/java/openjdk-17/bin/java  -Dlog.home=/root/logs/seata -server -Dloader.path=/seata-server/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xlog:gc*:file=/root/logs/seata/seata_gc.log:time,tags:filecount=10,filesize=102400 -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=7 -Dapp.home=/seata-server -Dbasedir=/seata-server  -Dspring.config.additional-location=/seata-server/conf/ -Dspring.config.location=/seata-server/conf/application.yml -Dlogging.config=/seata-server/conf/logback-spring.xml -jar /seata-server/target/seata-server.jar  
`
手动起一下看下错误日志
Start manually and check the error log

**Comment by eocoo** [comment]
是目录问题，现在到了下一个问题，org.postgresql.util.PSQLException: ERROR: relation "distributed_lock" does not exist 

而下载的建库脚本中没有这个表

**Comment by eocoo** [comment]
启动问题是好了，感谢

**Comment by funky-eyes** [comment]
> 是目录问题，现在到了下一个问题，org.postgresql.util.PSQLException: ERROR: relation "distributed_lock" does not exist
> 
> 而下载的建库脚本中没有这个表

https://github.com/apache/incubator-seata/blob/2.x/script/server/db/postgresql.sql
