### ISSUE TITLE
在Sharding-jdbc和Seata整合时，多个微服务间事务无法回滚

### ISSUE THREAD

**Issue by WXingSong** [apache/incubator-seata#6657]
## Why you need it?
在Sharding-jdbc和Seata整合时，多个微服务间事务无法回滚

## How it could be?
seata服务注册了多个shardingsphere的逻辑数据源

## Other related information
https://github.com/apache/shardingsphere/discussions/32012
https://github.com/apache/shardingsphere/discussions/32006

@funky-eyes

**Comment by linghengqian** [comment]
- I opened https://github.com/apache/shardingsphere/pull/32095 to fix this issue. Friends who follow the current issue can review it.
