### ISSUE TITLE
定时刷新TableMeta缓存的功能失效了

### ISSUE THREAD

**Issue by wuwen5** [apache/incubator-seata#6660]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
定时刷新TableMeta缓存的功能失效了，程序每900秒后会由业务调用主动查询一次tableMeta导致慢请求
1.7.0 版本之后没有定时任务发起`tableMetaRefreshEvent`事件,导致`tableMetaRefresh`会一直处于`tableMetaRefreshQueue.take()`状态。

在https://github.com/apache/incubator-seata/pull/4734/files 这次更新之后，原60秒刷新一次tablemeta缓存的功能失效了。

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
TableMetaCacheFactory#tableMetaRefreshEvent 
And 119 lines, the refresh task will be initiated actively after the refresh time is reached
```
            tableMetaRefreshExecutor.execute(() -> {
                while (true) {
                    // 1. check table meta
                    if (ENABLE_TABLE_META_CHECKER_ENABLE
                        && System.currentTimeMillis() - lastRefreshFinishTime > TABLE_META_CHECKER_INTERVAL) {
                        tableMetaRefreshEvent(dataSource.getResourceId());
                    }

```

**Comment by funky-eyes** [comment]
我明白你的意思了，由于这俩逻辑在同一个线程里，所以上面的刷新失效了
I see what you mean. Since these two logics are in the same thread, the above refresh is invalid.

**Comment by funky-eyes** [comment]
你可以提交一个pr来修复这个bug吗？
Can you commit a PR to fix this bug?
