### ISSUE TITLE
子任务没有回滚的动作

### ISSUE THREAD

**Issue by msDating** [apache/incubator-seata#6669]
![WX20240713-132742@
![WX20240713-132703@2x](https://github.com/user-attachments/assets/3e73f48b-7f64-4044-aa57-f0b23452a15e)
![WX20240713-132613@2x](https://github.com/user-attachments/assets/541b0cc1-f744-4690-b532-37fd0f95d817)
![WX20240713-132126@2x](https://github.com/user-attachments/assets/809e03cc-dc25-4c7d-9233-c1598f08d673)
![WX20240713-132048@2x](https://github.com/user-attachments/assets/4579178e-4de2-450f-85b0-e10c8a0757b6)
![WX20240713-132034@2x](https://github.com/user-attachments/assets/6a2fd847-8bd8-4e48-a264-043579169601)
![WX20240713-131840@2x](https://github.com/user-attachments/assets/57062ec0-efdc-4b22-8626-80c3f3c6407d)
2x](https://github.com/user-attachments/assets/457e13db-d00e-499a-bfde-6af0d7ab86b5)
![WX20240713-132727@2x](https://github.com/user-attachments/assets/02b3f51a-e586-4b26-b512-abe89891ba47)
两个服务通过fegin 调用 a->b b执行成功了 后面在执行a的操作 报错 测试a全局回滚 b的RootContext.getXID() 是和a的是一致 但是数据b 还是没有回滚 提交了

**Comment by msDating** [comment]
![WX20240713-132703@2x](https://github.com/user-attachments/assets/d245c1c3-9745-4391-9585-64eec8924e41)
![WX20240713-132613@2x](https://github.com/user-attachments/assets/136d2a68-7825-4a70-a1b2-3010669b3fe3)
![WX20240713-132126@2x](https://github.com/user-attachments/assets/25b1ebba-8a16-4325-bd1c-70c76d0b23dd)
![WX20240713-132048@2x](https://github.com/user-attachments/assets/eac6b521-8457-46e9-875c-bbd6cff1c65e)
![WX20240713-132034@2x](https://github.com/user-attachments/assets/215a5ccd-4b53-4fbd-8727-65160acccddd)
![WX20240713-131840@2x](https://github.com/user-attachments/assets/30676c8a-5b76-448e-a1ea-9a5ecd116cb3)

**Comment by funky-eyes** [comment]
https://seata.apache.org/zh-cn/docs/overview/faq/#42
