### ISSUE TITLE
AT模式下 为什么我两个服务的XID不一致（seat1.7.0）

### ISSUE THREAD

**Issue by yekai0827** [apache/incubator-seata#6680]
AT模式下 为什么我两个服务的XID不一致（seat1.7.0）

**Comment by funky-eyes** [comment]
xid可能没有传递或者接收成功，所以各自独立创建了新的全局事务
Xid may not be passed or received successfully, so each creates a new global transaction independently

**Comment by tanyaofei** [comment]
参考官网 FAQ，是否有引入 `spring-cloud-starter-alibaba-seata` 或者自行实现 XID 的传递
