### ISSUE TITLE
1.4版本 AT模式  

### ISSUE THREAD

**Issue by askalv** [apache/incubator-seata#6689]
有什么办法可以在不加全局事务注解的前提下，就可以判断我当前要操作的数据是否被其他全局事务所持有

**Comment by funky-eyes** [comment]
目前不支持直接使用api查询相关锁,只允许通过@GlobalLock注解加上使用被seata所代理的数据源进行对数据update等操作时,如果数据被锁定会抛异常提示. 
At present, it is not supported to directly use the api to query related locks. Only when updating the data through the @GlobalLock annotation and using the data source proxied by seata, an exception will be thrown if the data is locked.
