### ISSUE TITLE
node-sass build error on macOS

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#6690]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

node-sass build error on macOS

npm ERR! Binary has a problem: Error: dlopen(/Users/runner/work/incubator-seata/incubator-seata/console/src/main/resources/static/console-fe/node_modules/node-sass/vendor/darwin-arm64-111/binding.node, 0x0001): tried: '/Users/runner/work/incubator-seata/incubator-seata/console/src/main/resources/static/console-fe/node_modules/node-sass/vendor/darwin-arm64-111/binding.node' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/incubator-seata/incubator-seata/console/src/main/resources/static/console-fe/node_modules/node-sass/vendor/darwin-arm64-111/binding.node' (no such file), '/Users/runner/work/incubator-seata/incubator-seata/console/src/main/resources/static/console-fe/node_modules/node-sass/vendor/darwin-arm64-111/binding.node' (not a mach-o file)

https://github.com/apache/incubator-seata/actions/runs/10021674473/job/27700609487

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
fix https://github.com/apache/incubator-seata/pull/6692
