### ISSUE TITLE
集成了达梦数据库，数据的前镜像中有个字段是dm.jdbc.driver.DmdbTimestamp，但是在回滚反序列化时报错了

### ISSUE THREAD

**Issue by caishaodong** [apache/incubator-seata#6701]
报错信息如下：
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `dm.jdbc.driver.DmdbTimestamp` (although at least one Creator exists): no long/Long-argument constructor/factory method to deserialize from Number value (1721985847000)

**Comment by caishaodong** [comment]
镜像中的字段信息是这样的
{
"@class": "io.seata.rm.datasource.sql.struct.Field",
"name": "MODIFY_TIME",
"keyType": "NULL",
"type": 93,
"value": [
"dm.jdbc.driver.DmdbTimestamp",
1721985847000
]
},

**Comment by funky-eyes** [comment]
可能与oracle的Timestamp有类似问题,你可以尝试切换成kryo作为undolog的序列化方式看下结果吗?
There may be similar problems with Oracle's Timestamp. Can you try switching to kryo as the serialization method of undolog to see the result?

**Comment by funky-eyes** [comment]
我建议将这个问题反馈给达梦官方，我对比了pg的构造方法，它是含有long类型的入参的构造函数，而dm是没有的
I suggest this problem feedback to Dameng official, I compared the construction method of pg, which is a construction function with imported parameters of type long, but dm is not
![image](https://github.com/user-attachments/assets/3f7d40d9-3b4c-491c-9770-074948381fa4)

**Comment by caishaodong** [comment]
DmdbTimestamp有一个无参构造，但是是私有的，我通过本地替换的方式，把构造改为public后成功了

**Comment by funky-eyes** [comment]
> DmdbTimestamp有一个无参构造，但是是私有的，我通过本地替换的方式，把构造改为public后成功了

是的，我认为你应该反馈给dameng数据库，他们这个设计导致于jackson不兼容了
Yes, I think you should give feedback to the dameng database, their design makes it incompatible with jackson.

**Comment by funky-eyes** [comment]
当然我们也可以实现一个jackson的序列化器来解决这个问题
Of course, we can also implement a jackson serializer to solve this problem

**Comment by lyl2008dsg** [comment]
I would like to claim this task

**Comment by funky-eyes** [comment]
> I would like to claim this task

Looking forward to your pull request.
