### ISSUE TITLE
Unable to access jarfile /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar

### ISSUE THREAD

**Issue by basketballboy** [apache/incubator-seata#6703]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
这个异常只不过是不小心打到了release包中,具体日志通过start脚本启动后,看对应输出的日志目录中的即可
This exception is just accidentally hit the release package. After the specific log is started through the start script, you can see the log directory corresponding to the output.

**Comment by leizhiyuan** [comment]
If you still have questions, you can open the issue again
