### ISSUE TITLE
启动失败，但是找不到日志

### ISSUE THREAD

**Issue by basketballboy** [apache/incubator-seata#6705]
apm-skywalking not enabled
JMX disabled
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-1.el7.x86_64/bin/java  -Dlog.home=/root/logs/seata -server -Dloader.path=/u01/seata/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xloggc:/root/logs/seata/seata_gc.log -verbose:gc -XX:+PrintGCDetails  -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=127095 -Dapp.home=/u01/seata -Dbasedir=/u01/seata  -Dspring.config.additional-location=/u01/seata/conf/ -Dspring.config.location=/u01/seata/conf/application.yml -Dlogging.config=/u01/seata/conf/logback-spring.xml -jar /u01/seata/target/seata-server.jar  >> /dev/null 2>&1 &
seata-server is starting, you can check the /root/logs/seata/ *.log

**Comment by basketballboy** [comment]
![image](https://github.com/user-attachments/assets/663b7fe8-b566-4553-8209-5701660eba39)

**Comment by funky-eyes** [comment]
如果在/root/logs/seata/ 中没有任何日志,你可以尝试用以下命令手动启动查看错误,一般这种配置与jvm配置或日志目录权限等有关
If there is no log in/root/logs/seata/, you can try to start it manually with the following command to check the error. Generally, this configuration is related to jvm configuration or log directory permissions.
`/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-1.el7.x86_64/bin/java -Dlog.home=/root/logs/seata -server -Dloader.path=/u01/seata/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xloggc:/root/logs/seata/seata_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=127095 -Dapp.home=/u01/seata -Dbasedir=/u01/seata -Dspring.config.additional-location=/u01/seata/conf/ -Dspring.config.location=/u01/seata/conf/application.yml -Dlogging.config=/u01/seata/conf/logback-spring.xml -jar /u01/seata/target/seata-server.jar`

**Comment by hmj776521114** [comment]
看看有没有这个目录` /root/logs/seata`     没有的话自己手动新建下

**Comment by qiuz0415** [comment]
mac上测试也遇到相同问题，日志文件找不到，日志保存的文件夹也没有。需要手动建一下文件夹，再启动就好了
