### ISSUE TITLE
Centos7.6 JDK21 启动服务报错

### ISSUE THREAD

**Issue by hu-liwei** [apache/incubator-seata#6723]
### Centos7.6  jdk21  seata-server 启动服务报错

- 启动命令以及返回如下：

[root@iZuf638srmcgojynkwge6uZ bin]# ./seata-server.sh start 
apm-skywalking not enabled
JMX disabled
/usr/java/jdk-21.0.4/bin/java  -Dlog.home=/root/logs/seata -server -Dloader.path=/usr/seata/seata/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xlog:gc*:file=/root/logs/seata/seata_gc.log:time,tags:filecount=10,filesize=102400 -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=19059 -Dapp.home=/usr/seata/seata -Dbasedir=/usr/seata/seata  -Dspring.config.additional-location=/usr/seata/seata/conf/ -Dspring.config.location=/usr/seata/seata/conf/application.yml -Dlogging.config=/usr/seata/seata/conf/logback-spring.xml -jar /usr/seata/seata/target/seata-server.jar  >> /dev/null 2>&1 &
seata-server is starting, you can check the /root/logs/seata/ *.log

- /root/logs/seata/ 目录的日志文件如下：

[root@iZuf638srmcgojynkwge6uZ seata]# pwd
/root/logs/seata
[root@iZuf638srmcgojynkwge6uZ seata]# tail -f seata_gc.log
[2024-08-02T19:54:24.770+0800][gc,init] CardTable entry size: 512
[2024-08-02T19:54:24.770+0800][gc     ] Using G1

- start.out日志如下：
[root@iZuf638srmcgojynkwge6uZ logs]# tail -f start.out 
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java  -server -Dloader.path=../lib -Xmx2048m -Xms2048m -Xmn1024m -Xss512k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/min.ji/Git/github/seata/distribution/logs/java_heapdump.hprof -XX:+DisableExplicitGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=75 -Xloggc:/Users/min.ji/Git/github/seata/distribution/logs/seata_gc.log -verbose:gc -XX:+PrintGCDetails  -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=68288 -Dapp.home=/Users/min.ji/Git/github/seata/distribution -Dbasedir=/Users/min.ji/Git/github/seata/distribution -Dspring.config.location=/Users/min.ji/Git/github/seata/distribution/conf/application.yml -Dlogging.config=/Users/min.ji/Git/github/seata/distribution/conf/logback-spring.xml -jar /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar 
Error: Unable to access jarfile /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar

### seata 其余配置
application.yml中已配置
 seata.config 是nacos  
 seata.registry 是 nacos
 seata.store是db

### 服务器的其余配置
2c/4G /60GB 的阿里云服务器

**Comment by funky-eyes** [comment]
这个日志是打release包不小心打进去的，你应该关注/root/logs/seata/ 路径下的日志。
或者你直接使用打印出来的启动脚本，手动启动看下异常原因
This log was accidentally entered by the release package. You should pay attention to the log in the/root/logs/seata/path.
Or you can directly use the printed startup script and start it manually to see the cause of the exception.
`/usr/java/jdk-21.0.4/bin/java -Dlog.home=/root/logs/seata -server -Dloader.path=/usr/seata/seata/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xlog:gc*:file=/root/logs/seata/seata_gc.log:time,tags:filecount=10,filesize=102400 -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=19059 -Dapp.home=/usr/seata/seata -Dbasedir=/usr/seata/seata -Dspring.config.additional-location=/usr/seata/seata/conf/ -Dspring.config.location=/usr/seata/seata/conf/application.yml -Dlogging.config=/usr/seata/seata/conf/logback-spring.xml -jar /usr/seata/seata/target/seata-server.jar`

**Comment by leizhiyuan** [comment]
any update? @hu-liwei

**Comment by Lakers32** [comment]
虽然说八竿子打不着，但我的确是按照这个解决的https://blog.csdn.net/weixin_44502237/article/details/129934350

**Comment by vicoolee** [comment]
这个日志可以直接删除。服务没起来，是因为 没有提前创建这个文件夹/root/logs
