### ISSUE TITLE
this request cannot acquire global lock

### ISSUE THREAD

**Issue by chao6118** [apache/incubator-seata#6734]
1.开启分布式事务

2、本地事务代码
bind(xid)
try{
 org.apache.ibatis.session.SqlSessionFactory sqlSessionFactory = DataSourceUtil.getSession(dsKey);
 org.apache.ibatis.session.SqlSession session = sqlSessionFactory.openSession(false);

 session.commit();
}catch(Exception e){
	session.close();
}

3.如果正常进行分布式事务提交；如果有异常 分布式进行回滚

 1、2、3都是在不同请求接口中，也就是不同的Controller接口中。
现在出现了
 [ServerHandlerThread_1_18_500] [io.seata.core.exception.AbstractExceptionHandler] [exceptionHandleTemplate] [192.168.114.215:8091:207686808706734598]: this request cannot acquire global lock, you can let Seata retry by setting config [client.rm.lock.retryPolicyBranchRollbackOnConflict] = false or manually retry by yourself. request: BranchRegisterRequest{xid='192.168.114.215:8091:207686808706734598', branchType=AT, resourceId='jdbc:mysql://192.168.114.227:3306/master_cms', lockKey='flow_flownode_inputs_mapping:144201,144202,144203,144204,144205,144206,144207,144208,144209,144210,144211', applicationData='{"autoCommit":false}'}

**Comment by funky-eyes** [comment]
没看懂你想表达的问题和想要得到的技术支持是什么
I don't understand the problem you want to express and the Technical Support you want to get.
