### ISSUE TITLE
强烈要求support properties  file configuration

### ISSUE THREAD

**Issue by 891877295** [apache/incubator-seata#6735]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
你说的应该是支持spring的application.yml/properties，如果有这方面需求请引入seata-spring-boot-starter依赖，配合springboot进行构建项目，而properties早就已经支持读取了，只不过这个properties跟你所认为的spring的properties并不是一个配置文件。
What you're talking about should be supported by the application.yml/application.properties. If you have such requirements, please include the seata-spring-boot-starter dependency and build your project with Spring Boot. Properties files have long been supported, but this properties file is not the same as what you typically think of as Spring's properties configuration file.
https://github.com/apache/incubator-seata/tree/2.x/config/seata-config-core/src/main/java/org/apache/seata/config/processor
