### ISSUE TITLE
nacos作为注册中心时回滚失败

### ISSUE THREAD

**Issue by zsp419** [apache/incubator-seata#6758]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

 seata版本1.6.1，注册中心是nacos，nacos版本：2.4.0
我有两个服务A和B，A和B都成功在seata-server注册，A调用B之后，A侧报错，A正常回滚，B没有回滚。
奇怪的是：之前我用默认的file模式测试时，A和B都能够正常回滚，请问我应该如何去排查问题

seata-server注册成功日志：
![image](https://github.com/user-attachments/assets/f24d5cb9-bea6-4644-a6dd-f389910acda9)

**Comment by zsp419** [comment]
![image](https://github.com/user-attachments/assets/a6e7056e-4808-4274-82a9-391baaf49f0e)

**Comment by funky-eyes** [comment]
nacos只是用来做服务发现，回滚失败跟nacos基本上没什么关系，除非你的B节点没有注册到A节点所连接的tc上
Nacos is only used for service discovery. Rollback failure has basically nothing to do with nacos, unless your B node is not registered on the tc connected by A node

**Comment by funky-eyes** [comment]
参考官网faq不回滚的排查方法，排查下你为什么没有回滚，你截图的日志根本没有rm注册的日志
Refer to the troubleshooting method of faq not rolling back on the official website to check why you didn't roll back. The log you screenshot has no log registered by rm at all.

**Comment by zsp419** [comment]
![image](https://github.com/user-attachments/assets/5303b86b-7e1a-482e-9ebb-9a37c4c02db5)
截错了，这里是有rm注册日志的

**Comment by zsp419** [comment]
好了，多谢
