### ISSUE TITLE
The Docker Image for `apache/seata-server` is missing the self-description text

### ISSUE THREAD

**Issue by linghengqian** [apache/incubator-seata#6767]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

- The Docker Image for `apache/seata-server` is missing the self-description text. See https://hub.docker.com/r/apache/seata-server .
- ![image](https://github.com/user-attachments/assets/cf207030-213f-417b-83e5-c3860ba7dbc0)
- It would be nice if there was a text description on how to start the Docker Image like https://hub.docker.com/r/seataio/seata-server .
- ![image](https://github.com/user-attachments/assets/9b8640e3-72c5-4bf6-bf96-019950e47a70)

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

- I know that the ASF Infra team has limited each project to have only 2 members associated with the ASF organization on Docker Hub. But https://infra.apache.org/docker-hub-policy.html does not indicate how to check which PMC members are associated with the ASF organization on Docker hub. I am afraid I really don't know how to help.

## Other related information

- Null.

**Comment by funky-eyes** [comment]
Thank you for your feedback. I believe we need to modify the content in seataio/seata-server and then migrate it to apache/seata-server.

**Comment by funky-eyes** [comment]
As for how to migrate, I think we should seek help on Apache JIRA.

**Comment by slievrly** [comment]
@linghengqian thanks for your feedback. I have added the description of the `seata-server` repo.

https://hub.docker.com/repository/docker/apache/seata-server/general

**Comment by linghengqian** [comment]
> @linghengqian thanks for your feedback. I have added the description of the `seata-server` repo.
> 
> https://hub.docker.com/repository/docker/apache/seata-server/general

- Can I close this issue now since it has been resolved?

**Comment by slievrly** [comment]
> > @linghengqian thanks for your feedback. I have added the description of the `seata-server` repo.
> > https://hub.docker.com/repository/docker/apache/seata-server/general
> 
> * Can I close this issue now since it has been resolved?

 Yes. Whenever you want.
