### ISSUE TITLE
Optimize: unified use of "org.apache.seata.common.ConfigurationKeys"

### ISSUE THREAD

**Issue by yangli-stu** [apache/incubator-seata#6771]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

在core与config模块中，都有一个@Deprecated注解标识的“ConfigurationKeys”配置类，而该类都是继承于“org.apache.seata.common.ConfigurationKeys”类，且无其它任何额外作用。从可维护性上看，可以考虑移除core与config模块中的“ConfigurationKeys”类，改为统一使用“org.apache.seata.common.ConfigurationKeys”。
![image](https://github.com/user-attachments/assets/d2d1ed63-b612-4aeb-bf75-cca4976607ca)
![image](https://github.com/user-attachments/assets/4bd6e3a4-96d1-4704-b1a8-7af4dd77dc08)

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

移除core与config模块中过期的“ConfigurationKeys”类，全局替换下改为统一使用“org.apache.seata.common.ConfigurationKeys”。

**Comment by funky-eyes** [comment]
全局替换主要考虑到可能有其它人的pr与这个全局改动的pr有代码冲突，所以现在的原则是通过review时避免pr使用旧版的ConfigurationKeys，和提交pr时，比如修改到了A类，顺便将其修正。
When performing a global replacement, it's important to consider that other people's pull requests (PRs) might conflict with the global change. Therefore, the current principle is to avoid using the old ConfigurationKeys in PRs during the review process, and to make the necessary corrections when submitting a PR, such as modifying class A and making the required updates.

**Comment by yangli-stu** [comment]
好的，那我把这个issue关闭掉～


> 全局替换主要考虑到可能有其它人的pr与这个全局改动的pr有代码冲突，所以现在的原则是通过review时避免pr使用旧版的ConfigurationKeys，和提交pr时，比如修改到了A类，顺便将其修正。 When performing a global replacement, it's important to consider that other people's pull requests (PRs) might conflict with the global change. Therefore, the current principle is to avoid using the old ConfigurationKeys in PRs during the review process, and to make the necessary corrections when submitting a PR, such as modifying class A and making the required updates.
