### ISSUE TITLE
Connect to nodejs.org:443

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6782]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-npm (install node and npm) on project seata-console: Could not downloa
d Node.js: Could not download https://nodejs.org/dist/v19.5.0/node-v19.5.0-win-x64.zip: Connect to nodejs.org:443 [nodejs.org/104.20.22.46, nodejs.org/104.20.23.46] failed: Connection timed out: connect -> [Help 1]
```
建议与npm源一样都改为国内源,如下
It is recommended to change to domestic sources like npm sources, as follows
`<nodeDownloadRoot>https://mirrors.aliyun.com/nodejs-release/</nodeDownloadRoot>`

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by slievrly** [comment]
It is not recommended to change the original address here, it is recommended to replace the variable with an environment variable or a compiled file, similar to GOPROXY.

**Comment by heliang666s** [comment]
please assign to me.I want to solve it.

**Comment by jsbxyyx** [comment]
```
echo 'registry=https://registry.npmmirror.com' >> ~/.npmrc
source ~/.npmrc
```
