### ISSUE TITLE
removeOfflineAddressesIfNecessary method may cause the service list to be empty when switching clusters

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6790]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
removeOfflineAddressesIfNecessary method may cause the service list to be empty when switching clusters.
![dce87acf96ae52599a79df177ed88579](https://github.com/user-attachments/assets/5ab87194-ef78-4e98-a1cd-049234c51137)
我认为这里应该防推空,如果没有交集就不做任何处理,这样就可以解决问题了
I think it should be anti-empty here. If there is no intersection, we will not do any processing, so that the problem can be solved

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
