### ISSUE TITLE
upgrade com.google.protobuf:protoc:exe dependency

### ISSUE THREAD

**Issue by slievrly** [apache/incubator-seata#6798]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Update the version of the com.google.protobuf:protoc:exe dependency. Currently, the Maven packaging commands used for x86 and aarch64 architectures are not consistent.

For x86: ./mvnw clean package -DskipTests=true

For aarch64: ./mvnw clean package -DskipTests=true -Parrch64

The goal is to have a unified packaging command across different OS platforms, ideally:

./mvnw clean package -DskipTests=true

It's crucial to ensure compatibility with protobuf.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by heliang666s** [comment]
please assign to me.I want to solve it.

**Comment by slievrly** [comment]
@heliang666s Looking forward to your submitted fix PR.
