### ISSUE TITLE
Why did Redis switch from using Java and Jedis (pipeline, mulit) from the beginning to using Lua scripts?

### ISSUE THREAD

**Issue by chaixuqing** [apache/incubator-seata#6799]
I have just started learning Seata and think it is a very good github project, but I have encountered a few problems in the learning process. If someone answers my questions, I will buy them a cup of coffee.

Under the separation of calculation and storage in Seata, Redis has become the hot transaction storage mode of Seata. However, in this mode, it uses Java + Jedis (pipeline, mulit) processing. If the server is powered off or down, multiple network I/O and calculations may not be completely guaranteed to be atomic, resulting in the global lock remaining. This will affect the processing of some data in the AT mode. Instead, when using a Lua script, a series of calculations and storage can be handed over to Redis, ensuring the atomicity of the TC stored data and the contention for the global lock, and ensuring the high availability and consistency of the Redis transaction storage mode.

My questions are:

1. Under what circumstances does Seata AT mode require multiple Redis commands to be bound together to ensure atomicity? Which Redis commands need to be bound together?
2. What are the detailed circumstances that will cause the global lock to be left behind?
3. Apart from the global lock being left behind, what other bad things can happen?
4. When Seata is in AT mode and a global transaction is ready to be committed, does the TC first send the Redis modification command or does the TC first send a response to RM?
5. What does the TC Redis store mainly in Seata?
6. What happens after the TC server restarts? Will RM keep retrying to report the transaction status? If the global lock still exists in Redis, will the TC server release the global lock again after committing the transaction globally?

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/blob/2.x/server/src/main/java/org/apache/seata/server/storage/redis/lock/RedisLocker.java
https://github.com/apache/incubator-seata/blob/2.x/server/src/main/java/org/apache/seata/server/storage/redis/store/RedisTransactionStoreManager.java

You can read the above code for yourself to understand
