### ISSUE TITLE
tc server report: Duplicate entry ' jdbc:oracle:thin:@dm/TODO^^^todo_list^^^1' for key 'PRIMARY' '

### ISSUE THREAD

**Issue by aliuql** [apache/incubator-seata#6810]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
AT mode, I have three services A、B、C，and A request B and then C。A start a global transaction, B and C start a branch Transaction。B and C have db operation，and B and C will operate the same record of table todo_list, which primary key is id
B's sql is :   insert into TODO_LIST (id, hide) values ('1', 'N');    (the table name is upper case TODO_LIST）
C's sql is :   update todo_list set hide = 'Y' where id = '1';       (the table name is lower case todo_list）

![image](https://github.com/user-attachments/assets/15aeb898-2926-42d9-963f-71ae70238c49)

### Ⅱ. Describe what happened
when service C invoke TC, TC response: Duplicate entry ' jdbc:oracle:thin:@dm/TODO^^^todo_list^^^1' for key 'PRIMARY' '

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
the version of seata is 1.4.2.
i have location the code of seata client OracleUpdateRecognizer.getTableName(), when create TableMeta cache the first time access a table, the table name is get from sql, this depend on the user's sql。
when two branch of a global transaction lock the same record, TC server will throw the exception.

please make evaluate the code below, upper case the table name when get OracleUpdateRecognizer.getTableName() return

OracleUpdateRecognizer.getTableName()
return sb.toString().toUpperCase();

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
Please upgrade to version 2.1.0 and check if there are still any case sensitivity issues

**Comment by aliuql** [comment]
already solved in seata 2.2.0
