### ISSUE TITLE
seata-spring-boot-starter compatible with file.conf and registry.conf configurations

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6811]
## Why you need it?
 Is your feature request related to a problem? Please describe in details
可以参考以下pr进行兼容适配
You can refer to the following PR for compatibility adaptation.
https://github.com/apache/incubator-seata/pull/5717

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by lyl2008dsg** [comment]
I would like to claim this task
