### ISSUE TITLE
NacosMockTest.getConfig:77 expected: <null> but was: <VALUE>

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6832]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
```
Error:  Failures: 
Error:    NacosMockTest.getConfig:77 expected: <null> but was: <VALUE>
Error:    NacosMockTest.removeConfig:149 expected: <true> but was: <false>
[INFO] 
Error:  Tests run: 8, Failures: 2, Errors: 0, Skipped: 0
```
https://github.com/apache/incubator-seata/actions/runs/10764848855/job/29848248173?pr=6819

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by yangli-stu** [comment]
I would like to fix it. Could you please assign it to me?

**Comment by funky-eyes** [comment]
> I would like to fix it. Could you please assign it to me?

Could you first tell me how you plan to fix this issue? I hope our communication can help resolve the problem as quickly as possible.

**Comment by yangli-stu** [comment]
本地ut没有复现出异常，不知道是否是环境有差异。
对于“Error:    NacosMockTest.getConfig:77 expected: <null> but was: <VALUE>”：
是不是可以在ut执行前使用：configService.removeConfig(SUB_NACOS_DATAID, NACOS_GROUP)，来保证干净的配置.

对于“Error:    NacosMockTest.removeConfig:149 expected: <true> but was: <false>”:
这个同样没有复现出来，期望得到一些提示～

**Comment by funky-eyes** [comment]
这个实际上是因为jdk8和jdk21的ci同时并发跑导致的，因为他们都使用了公网上给用户演示的nacos
我建议你可以直接在ci上拉取一个nacos的镜像跑起来，让每个ci都拥有自己独立的nacos，这样就不会冲突
https://github.com/apache/incubator-seata/blob/2.x/.github/workflows/build.yml
你可以参考着上面拉取redis镜像的做法
