### ISSUE TITLE
Improve test coverage 

### ISSUE THREAD

**Issue by lovepoem** [apache/incubator-seata#6837]
Improve test coverage

**Comment by YvCeung** [comment]
@lovepoem 
Hello, I think I can write unit tests to participate in the community and be familiar with the source code. Can I do this task? Can you tell me about some specific modules that need to improve the unit test coverage?
你好，我认为编写单元测试不仅能参与社区而且还能熟悉源码，我可以做这项任务吗，可以说一些具体的模块需要提高单测覆盖率的吗
