### ISSUE TITLE
seata服务器升级到2.1.0，springboot客户端依赖是什么，最新文档还是2.0.0

### ISSUE THREAD

**Issue by 465722253** [apache/incubator-seata#6846]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

seata服务器升级到2.1.0，springboot客户端依赖是什么，还是用2.0.0.吗，目前最新文档还是2.0.0，maven仓库2.1.0的依赖好像没有

**Comment by funky-eyes** [comment]
org.apache.seata

**Comment by 465722253** [comment]
api 'io.seata:seata-spring-boot-starter:2.0.0'  gradle原先2.0.0的依赖升级到2.1.0的依赖应该怎么写  谢谢  maven仓库并没有找到。谢谢  希望能尽快更新2.1.0文档

**Comment by funky-eyes** [comment]
org.apache.seata:seata-spring-boot-starter:2.1.0

**Comment by funky-eyes** [comment]
https://mvnrepository.com/artifact/org.apache.seata/seata-spring-boot-starter
