### ISSUE TITLE
seata支持业务外键回滚吗

### ISSUE THREAD

**Issue by 465722253** [apache/incubator-seata#6854]
ERROR org.apache.seata.rm.datasource.DataSourceManager - branchRollback failed. branchType:[AT], xid:[10.244.1.180:8091:5648078290911009109], branchId:[5648078290911009159], resourceId:[jdbc:postgresql://10.10.0.70:30811/plat], applicationData:[{"autoCommit":false}]. reason:[Branch session rollback failed and try again later xid = 10.244.1.180:8091:5648078290911009109 branchId = 5648078290911009159 ERROR: update or delete on table "act_ru_execution" violates foreign key constraint "act_fk_exe_parent" on table "act_ru_execution"
  详细：Key (id_)=(ec6c2771-7247-11ef-bafe-005056bda8b6) is still referenced from table "act_ru_execution".]

seata与activiti的act_ru_execution表，因为外键的约束无法进行回滚

**Comment by funky-eyes** [comment]
nonsupport

**Comment by MolyXl** [comment]
当前2.5版本支持外键了吗
