### ISSUE TITLE
seata的AT模式为什么不先获取全局锁再执行本地事务呢？

### ISSUE THREAD

**Issue by Lychengit** [apache/incubator-seata#6870]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by funky-eyes** [comment]
1.某些sql必须先执行，才能拿到主键，拿到主键后才能获取全局锁。
2.某些sql可能执行失败，这种情况下拿全局锁只会增加额外开销
3.全局锁与本地锁是一个交换关系，先拿本地锁，然后拿全局锁，释放本地锁，这样这个事务持有了全局锁后，即便后面的事务拿到本地锁也无法提交本地事务，只能重试，可以保证拿到全局锁的事务安心提交本地事务。
Some SQL statements must be executed first to obtain the primary key, which is needed to acquire the global lock.

Some SQL statements may fail; in such cases, acquiring the global lock would only add extra overhead.

The global lock and local lock have an exchange relationship: first, acquire the local lock, then the global lock, and release the local lock. This way, once the transaction holds the global lock, even if subsequent transactions acquire the local lock, they cannot commit their local transactions and must retry, ensuring that the transaction with the global lock can safely commit its local transaction.

**Comment by Lychengit** [comment]
哦，第一点确实是很关键。我还有一个问题，现在AT模式只支持本地多数据源吗，不支持经过RPC的分布式事务吗

**Comment by funky-eyes** [comment]
支持
