### ISSUE TITLE
`org.apache.seata:seata-mock-server` depends on the non-existent `org.apache.seata:seata-server`

### ISSUE THREAD

**Issue by linghengqian** [apache/incubator-seata#6882]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

- `org.apache.seata:seata-mock-server` depends on the non-existent `org.apache.seata:seata-server`. See https://mvnrepository.com/artifact/org.apache.seata/seata-mock-server/2.1.0 .

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

- This is an extension of surveys #6686 and #6860 . If `org.apache.seata:seata-mock-server` must depend on the non-existent `org.apache.seata:seata-server`, how can we use `org.apache.seata.mockserver.MockServer`?

```shell
Could not find artifact org.apache.seata:seata-server:pom:2.1.0 in central (https://repo.maven.apache.org/maven2)
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Open https://mvnrepository.com/artifact/org.apache.seata/seata-mock-server/2.1.0 .

Minimal yet complete reproducer code (or URL to code):

- This doesn't seem to need any example.

### Ⅴ. Anything else we need to know?

- No.

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 

```shell
openjdk version "22.0.2" 2024-07-16
OpenJDK Runtime Environment GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01, mixed mode, sharing)
```

- Seata client/server version:  `2.1.0`
- Database version: `postgres:16.3-bookworm`
- OS(e.g. `uname -a`): `Linux DESKTOP-2OCN434 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Others: Null

**Comment by funky-eyes** [comment]
@slievrly Should we deploy the seata-server like we did before?

**Comment by slievrly** [comment]
@linghengqian What are the scenarios for using the org.apache.seata:seata-mock-server dependency? The org.apache.seata:seata-mock-server was originally designed to facilitate testing the full transaction process on the SDK side for the Seata project itself. Does ShardingSphere also require such mock functionality?

**Comment by linghengqian** [comment]
> @linghengqian What are the scenarios for using the org.apache.seata:seata-mock-server dependency? The org.apache.seata:seata-mock-server was originally designed to facilitate testing the full transaction process on the SDK side for the Seata project itself. Does ShardingSphere also require such mock functionality?

@slievrly 
- I'm guessing I made a further inference wrong about https://github.com/apache/incubator-seata/issues/5343#issuecomment-1432368918 ? I thought Seata Server would expose a startup class for Seata Server used for testing, just like the `org.apache.curator.test.TestingServer` located at https://github.com/apache/curator/blob/apache-curator-5.7.1/curator-test/src/main/java/org/apache/curator/test/TestingServer.java .
- The core reason why ShardingSphere actively simulates Seata Server is that ShardingSphere only uses Docker Engine in integration testing, e2e and nativeTest. Any normal unit testing with the default Maven Profile is designed not to use Docker Engine. That's why `org.apache.shardingsphere.transaction.base.seata.at.fixture.MockSeataServer` in https://github.com/apache/shardingsphere/blob/95c98e0b72746a3520ffb81efc9160ab6522d8bd/kernel/transaction/type/base/seata-at/src/test/java/org/apache/shardingsphere/transaction/base/seata/at/fixture/MockSeataServer.java exists.

**Comment by funky-eyes** [comment]
The current seata-mock-server is only provided for testing Seata clients and multi-version protocol interoperability. When the mock-server was designed, there wasn't any consideration to make it available externally, but it seems that this can be considered now. @slievrly @Bughue

**Comment by slievrly** [comment]
@linghengqian @funky-eyes Thank you very much for your feedback. We will consider implementing this capability in version 2.3.0.
