### ISSUE TITLE
The documentation for Seata 2.1.0 should point to the Docker Image of `apache/seata-server`

### ISSUE THREAD

**Issue by linghengqian** [apache/incubator-seata#6887]
## Why you need it?
 Is your feature request related to a problem? Please describe in details

- The documentation for Seata 2.1.0 should point to the Docker Image of `apache/seata-server`. See https://hub.docker.com/r/apache/seata-server and https://github.com/apache/incubator-seata/pull/6349 .
- Both https://seata.apache.org/docs/ops/deploy-by-docker and https://seata.apache.org/docs/ops/deploy-by-docker-compose point to the outdated `seataio/seata-server` and https://hub.docker.com/r/seataio/seata-server/tags .
- ![image](https://github.com/user-attachments/assets/6a3de29e-cb35-49eb-93f1-96328057e860)

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

- I'm not sure if the current issue should be moved to https://github.com/apache/incubator-seata-website ?

## Other related information

- An early investigation is at https://github.com/apache/shardingsphere/pull/33030 and https://github.com/apache/shardingsphere/pull/31934 .

**Comment by slievrly** [comment]
@linghengqian thanks for your feedback.
