### ISSUE TITLE
XA 模式 @GlobalTransactional+@Transactional  （Propagation.REQUIRES_NEW ） 异常问题

### ISSUE THREAD

**Issue by wjdxw** [apache/incubator-seata#6897]
XA 模式下
@GlobalTransactional  内部使用@Transactional  （Propagation.REQUIRES_NEW ）  时，如果外部事物有异常，内部事务正常，此时整体都会被回滚，独立的事物并没有被隔离

@GlobalTransactional(rollbackFor = Exception.class)
methodA{

//A 数据insert 

//B数据insert
methodB();

throw new Exception("");

}
@Transactional(rollbackFor = Exception.class,propagation = Propagation.REQUIRES_NEW)
methodB(){

}

methodB 在执行完之后，事物并没有提交，最终外部抛出异常，导致数据A 并没有insert
把@Transactional 换成GlobalTransactional 之后，在执行完methodB 方法之后，事物就会提交
我想问下这种情况是正常的嘛？

**Comment by funky-eyes** [comment]
`@transactional` 是属于spring的。`@GlobalTransactional` 属于seata，自行查看`@GlobalTransactional`注解上的内容
`@transactional`  belongs to spring. `@GlobalTransactional` belongs to seata, check the content on the `@GlobalTransactional` annotation by yourself
