### ISSUE TITLE
关于seata部署的问题请教

### ISSUE THREAD

**Issue by wxrqforever** [apache/incubator-seata#6908]
背景：
目前部门内使用的注册中心和配置中心的组件均为自研，不在seata的支持范围内。在部署seata的时候(使用nacos作为配置中心和注册中心)。相关疑问如下：

关于配置：
https://github.com/apache/incubator-seata/blob/develop/script/config-center/config.txt
这个配置文件中的配置同时包含了client和server的配置，我目前是将这个配置文件里的所有内容刷到了nacos中，然后客户端应用的这段配置：
seata.config.type=nacos
seata.config.nacos.server-addr=xxxx
seata.config.nacos.group=SEATA_GROUP
seata.config.nacos.namespace=
seata.config.nacos.data-id=seataServer.properties
这里我理解客户端接入nacos(配置这块)目的应该是只是为了读取其中的client配置部分。考虑到不同的应用程序对于客户端的配置可能会有不同的需求，因此这里实际是不是可以只向nacos刷server相关的配置，然后client的配置部分，在我的场景里可以放到自研的配置中心的，每个应用维护自己的配置。否则看起来，我就需要在nacos上按应用进行分组，分别拷贝client的配置。

以上我简单实践了一下，未见异常，想请教一下理论上是否正常，会有隐藏风险吗？

关于注册：
按部署文档，我在客户端使用了如下配置：
seata.registry.type=nacos
seata.registry.nacos.application=seata-server
seata.registry.nacos.server-addr=xxxxx
seata.registry.nacos.group=SEATA_GROUP
seata.registry.nacos.namespace=
seata.registry.nacos.username=
seata.registry.nacos.password=
seata.registry.nacos.contextPath=
seata.registry.nacos.clientApplication=${spring.application.name}
我在nacos上观察，并未观察到业务应用被注册到nacos上，seata-server正常注册，这里注册的目的是否只是为了让客户端发现seata-server？有让seata-server反向找到业务应用的需求吗？比如如果某个业务应用实例在执行全局事务期间挂了，不知seata-server是如何找到其他还在正常执行的实例，进行回滚的？

以上期待您的回复，感谢。

**Comment by slievrly** [comment]
> 背景： 目前部门内使用的注册中心和配置中心的组件均为自研，不在seata的支持范围内。在部署seata的时候(使用nacos作为配置中心和注册中心)。相关疑问如下：
> 
> 关于配置： https://github.com/apache/incubator-seata/blob/develop/script/config-center/config.txt 这个配置文件中的配置同时包含了client和server的配置，我目前是将这个配置文件里的所有内容刷到了nacos中，然后客户端应用的这段配置： seata.config.type=nacos seata.config.nacos.server-addr=xxxx seata.config.nacos.group=SEATA_GROUP seata.config.nacos.namespace= seata.config.nacos.data-id=seataServer.properties 这里我理解客户端接入nacos(配置这块)目的应该是只是为了读取其中的client配置部分。考虑到不同的应用程序对于客户端的配置可能会有不同的需求，因此这里实际是不是可以只向nacos刷server相关的配置，然后client的配置部分，在我的场景里可以放到自研的配置中心的，每个应用维护自己的配置。否则看起来，我就需要在nacos上按应用进行分组，分别拷贝client的配置。

Do you support self-developed configuration center in the code through SPI extension?

That is OK. In this case, you need to keep the same configuration of the client and server or use the default value without the configuration value.



> 以上我简单实践了一下，未见异常，想请教一下理论上是否正常，会有隐藏风险吗？
> 
> 关于注册： 按部署文档，我在客户端使用了如下配置： seata.registry.type=nacos seata.registry.nacos.application=seata-server seata.registry.nacos.server-addr=xxxxx seata.registry.nacos.group=SEATA_GROUP seata.registry.nacos.namespace= seata.registry.nacos.username= seata.registry.nacos.password= seata.registry.nacos.contextPath= seata.registry.nacos.clientApplication=${spring.application.name} 我在nacos上观察，并未观察到业务应用被注册到nacos上，seata-server正常注册，这里注册的目的是否只是为了让客户端发现seata-server？有让seata-server反向找到业务应用的需求吗？比如如果某个业务应用实例在执行全局事务期间挂了，不知seata-server是如何找到其他还在正常执行的实例，进行回滚的？
> 
> 以上期待您的回复，感谢。

The registry of seata and the registry of business services are completely separate.
In the second phase of the transaction, it is required for the seata-server to find the seata-client in reverse, but this does not occur through a registration center. Instead, reverse communication takes place through a long connection channel established between the seata-client and the seata-server. When one node of the seata-client goes down, the seata-server can find other peer seata-client nodes to communicate with based on the resourceId, achieving high availability.
