### ISSUE TITLE
In the Raft model a follower's crash may lead to the continued use of expired tokens.

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6917]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

In the Raft model a follower's crash may lead to the continued use of expired tokens.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. raft模式下，下线一台follower
2. 恰好此时client侧token过期，进行刷新
3. 恰好刷新的请求到了离线的follower中，导致请求失败
4. 由于请求之前将时间戳进行了更新，导致过期的token被视为可用

a. In the Raft model, a follower goes offline.
b. At this moment, the token on the client side expires and needs to be refreshed.
c. The refresh request happens to reach the offline follower, resulting in a failed request.
d. Because the timestamp was updated prior to the request, the expired token is mistakenly considered valid.

Minimal yet complete reproducer code (or URL to code):
RaftRegistryServiceImpl#refreshToken中先更新了tokenTimeStamp，才发出获取token的请求，而且并没有判断httpstatus是否正常。
In RaftRegistryServiceImpl#refreshToken, the tokenTimeStamp is updated before the request to obtain the token is sent, and there is no check for whether the HTTP status is normal.
```
    private static void refreshToken(String tcAddress) throws RetryableException {
        // if username and password is not in config , return
        if (StringUtils.isBlank(USERNAME) || StringUtils.isBlank(PASSWORD)) {
            return;
        }
        // get token and set it in cache
        Map<String, String> param = new HashMap<>();
        param.put(PRO_USERNAME_KEY, USERNAME);
        param.put(PRO_PASSWORD_KEY, PASSWORD);
        Map<String, String> header = new HashMap<>();
        header.put(HTTP.CONTENT_TYPE, ContentType.APPLICATION_JSON.getMimeType());
        String response = null;
        tokenTimeStamp = System.currentTimeMillis();
        try (CloseableHttpResponse httpResponse =
            HttpClientUtil.doPost("http://" + tcAddress + "/api/v1/auth/login", param, header, 1000)) {
            if (httpResponse != null) {
                if (httpResponse.getStatusLine().getStatusCode() == HttpStatus.SC_OK) {
                    response = EntityUtils.toString(httpResponse.getEntity(), StandardCharsets.UTF_8);
                    JsonNode jsonNode = OBJECT_MAPPER.readTree(response);
                    String codeStatus = jsonNode.get("code").asText();
                    if (!StringUtils.equals(codeStatus, "200")) {
                        //authorized failed,throw exception to kill process
                        throw new AuthenticationFailedException("Authentication failed! you should configure the correct username and password.");
                    }
                    jwtToken = jsonNode.get("data").asText();
                } else {
                    //authorized failed,throw exception to kill process
                    throw new AuthenticationFailedException("Authentication failed! you should configure the correct username and password.");
                }
            }
        } catch (IOException e) {
            throw new RetryableException(e.getMessage(), e);
        }
    }
```

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by yougecn** [comment]
follower 服务端日志
2024-10-12 15:56:29.076  WARN --- [http-nio-7095-exec-9] [org.apache.seata.console.utils.JwtTokenUtils] [validateToken] []: Expired JWT token.
2024-10-12 15:56:29.077 ERROR --- [http-nio-7095-exec-9] [org.apache.seata.console.security.JwtAuthenticationEntryPoint] [commence] []: Responding with unauthorized error. Message - Full authentication is required to access this resource

client端日志
2024-10-12 15:40:13.164 ERROR 23697 --- [refreshMetadata_1_1] o.a.s.d.r.raft.RaftRegistryServiceImpl  [199] [traceid:][pspanid:][spanid:][XID:][XBID:] : Authentication failed!
org.apache.seata.common.exception.RetryableException: Authentication failed!
        at org.apache.seata.discovery.registry.raft.RaftRegistryServiceImpl.acquireClusterMetaData(RaftRegistryServiceImpl.java:384) ~[seata-all-2.2.0.jar!/:2.2.0]
        at org.apache.seata.discovery.registry.raft.RaftRegistryServiceImpl.lambda$startQueryMetadata$0(RaftRegistryServiceImpl.java:183) ~[seata-all-2.2.0.jar!/:2.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_341]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_341]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar!/:4.1.101.Final]
        at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_341]

**Comment by lixingjia77** [comment]
If this task only requires fixing the timing of updating the tokenTimeStamp, I'd like to complete it.

**Comment by o-jimin** [comment]
Can I fix this?

**Comment by funky-eyes** [comment]
> If this task only requires fixing the timing of updating the tokenTimeStamp, I'd like to complete it.

Of course, I look forward to your PR.
