### ISSUE TITLE
Error reading version.json during the compilation of the console module

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6921]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
打包的时候明确了版本指向revision这个变量，而这个变量在打包日志里可以看到是生效的，但是对于version.js来说是无效的。
During packaging, the version is explicitly pointed to the revision variable, which can be seen as effective in the packaging logs. However, it is ineffective for version.js.
![image](https://github.com/user-attachments/assets/e7c80617-71df-473c-aa0f-a6ec35695a63)
![image](https://github.com/user-attachments/assets/607a1f18-6ce4-4618-b558-9c8bf389f26d)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by psxjoy** [comment]
Hi, could you share the specific build steps?
I tried running `mvn compile -DskipTests=true`. 
The `version.json` for the 2.2.0 branch shows `{"version":"2.2.0"}`, and for the 2.x branch, it shows `{"version":"2.3.0-SNAPSHOT"}`. 
That looks normal. 

My build environment includes Node.js v20.17.0, npm 10.8.2, and Maven 3.9.9 on Windows 11 amd64.

Hi,您能提供一下具体的构建步骤吗？我尝试  `mvn compile  -DskipTests=true` 命令构建。
 2.2.0 分支的version.json 显示`{"version":"2.2.0"}`;2.x 分支的version.json 显示`{"version":"2.3.0-SNAPSHOT"}`。似乎是正常的？    
我的编译环境：Node.js v20.17.0 & npm 10.8.2 & Maven 3.9.9 on Windows11 amd64.

**Comment by slievrly** [comment]
@psxjoy Is in the current branch to generate version number file, then switch branches to execute mvn command is not cleaned up cause, you can try it.

**Comment by psxjoy** [comment]
> @psxjoy Is in the current branch to generate version number file, then switch branches to execute mvn command is not cleaned up cause, you can try it.

Exactly. I think @funky-eyes  didn’t run `mvn clean` when switching branches, which caused the issue. 
I couldn’t replicate the problem he described.

**Comment by funky-eyes** [comment]
> > @psxjoy Is in the current branch to generate version number file, then switch branches to execute mvn command is not cleaned up cause, you can try it.
> 
> Exactly. I think @funky-eyes didn’t run `mvn clean` when switching branches, which caused the issue. I couldn’t replicate the problem he described.

我确定我使用了mvn clean，我认为你应该先进行一次编译，然后切到其他版本分支再进行一次编译对比结果
I'm sure I used mvn clean, I think you should compile it first, then switch to another version branch and compile it again to compare the results.

**Comment by funky-eyes** [comment]
原因是以前打包过，除非再执行npm，否则光靠mvn clean是无法清除的，并且存在即便不打包前端资源由于以前执行过，就被自动拷过来
The reason is that it has been packaged before, unless npm is executed again, it cannot be cleared by mvn clean alone, and the front-end resources that are not packaged are automatically copied because they have been executed before.
