### ISSUE TITLE
Same maven name with two modules

### ISSUE THREAD

**Issue by psxjoy** [apache/incubator-seata#6939]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
When I run `mvn install -DskipTests`, I get two same maven name modules:
尝试构建代码，发现有两个模块的maven的name属性一样：
![image](https://github.com/user-attachments/assets/66df8028-3abf-4b78-a441-46f706baf8bf)

I check these two module's pom.xml and found `seata-http-jakarta` module info as same as the 'seata-http' module.
我看了对应的pom.xml文件，发现 `seata-http-jakarta`和 `seata-http` 两个模块的name 和 description 描述一致。
![image](https://github.com/user-attachments/assets/4374e71a-701a-464a-9c87-8edf419ec992)

Is this the correct maven name or not?
请问这是故意设置的，还是这是个问题？

### Ⅱ. Describe what happened
Same maven name with two modules

### Ⅲ. Describe what you expected to happen
Different modules should have their own maven-name.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
Not applicable

### Ⅴ. Anything else we need to know?
If there is a bug or typo, I like to fix it. Feel free assign it to me anytime:)

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):17
- Seata client/server version:  2.2.0
- Database version:Not applicable
- OS(e.g. `uname -a`):Win 11
- Others:

**Comment by slievrly** [comment]
@psxjoy The advanced version of Spring MVC uses Jakarta HTTP (and its underlying Servlet API) to handle HTTP. Here the description can add a distinction, welcome fix.

**Comment by psxjoy** [comment]
@slievrly Thanks for your infomation. 
I'm willing to  fix it. Feel free assign it to me anytime:)
