### ISSUE TITLE
linux下，解压后，执行启动命令./bin/seata-server.sh，报错Error: Unable to access jarfile /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar

### ISSUE THREAD

**Issue by hggCode** [apache/incubator-seata#6955]
[root@iZwz99ft69kuwh014ttynyZ seata]# ./bin/seata-server.sh
apm-skywalking not enabled
Affected JVM parameters: -Dlog.home=/root/logs/seata -server -Dloader.path=/usr/local/projects/seata/seata/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xlog:gc*:file=/root/logs/seata/seata_gc.log:time,tags:filecount=10,filesize=102400 -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=2791821 -Dapp.home=/usr/local/projects/seata/seata -Dbasedir=/usr/local/projects/seata/seata -Dspring.config.additional-location=/usr/local/projects/seata/seata/conf/ -Dspring.config.location=/usr/local/projects/seata/seata/conf/application.yml -Dlogging.config=/usr/local/projects/seata/seata/conf/logback-spring.xml -jar /usr/local/projects/seata/seata/target/seata-server.jar
/usr/local/java/jdk-17/bin/java  -Dlog.home=/root/logs/seata -server -Dloader.path=/usr/local/projects/seata/seata/lib -Xmx2048m -Xms2048m -Xss640k -XX:SurvivorRatio=10 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=1024m -XX:-OmitStackTraceInFastThrow -XX:-UseAdaptiveSizePolicy -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/logs/seata/java_heapdump.hprof -XX:+DisableExplicitGC -Xlog:gc*:file=/root/logs/seata/seata_gc.log:time,tags:filecount=10,filesize=102400 -Dio.netty.leakDetectionLevel=advanced -Dapp.name=seata-server -Dapp.pid=2791821 -Dapp.home=/usr/local/projects/seata/seata -Dbasedir=/usr/local/projects/seata/seata -Dspring.config.additional-location=/usr/local/projects/seata/seata/conf/ -Dspring.config.location=/usr/local/projects/seata/seata/conf/application.yml -Dlogging.config=/usr/local/projects/seata/seata/conf/logback-spring.xml -jar /usr/local/projects/seata/seata/target/seata-server.jar  >> /dev/null 2>&1 &
seata-server is starting, you can check the /root/logs/seata/ *.log

后续查看日志报错：
Error: Unable to access jarfile /Users/min.ji/Git/github/seata/distribution/target/seata-server.jar

我的目录应该是/usr/local/projects/seata/seata/target

**Comment by funky-eyes** [comment]
/root/logs/seata/ *.log 请到这里查看日志
Please go here to view the log.

**Comment by slievrly** [comment]
It seems that the past version mistakenly packaged my local log file into the binary package. If the process can start normally, this file can be deleted without affecting the use of it. In the meantime, you are advised to upgrade to the next version.
