### ISSUE TITLE
【问题】ConfigurationFactory 加载的打印信息有问题

### ISSUE THREAD

**Issue by noear** [apache/incubator-seata#6956]
"org.apache.seata.config.ConfigurationFactory" load 方法

```java
extConfiguration = EnhancedServiceLoader.load(ExtConfigurationProvider.class).provide(configuration);
if (LOGGER.isInfoEnabled()) {
    LOGGER.info("load Configuration from :{}",
        extConfiguration == null ? configuration.getClass().getSimpleName() : "Spring Configuration");
}
```

当 java spi 加载到 ExtConfigurationProvider 时，会打印："Spring Configuration"。。。

改为 extConfiguration.getClass().getSimpleName() 更合理。

---

比如，我在适配 seata-solon-plugin 时，java spi 配置的是 SolonConfigurationProvider，会被打印成了 "Spring Configuration"

**Comment by noear** [comment]
适配两个（或以上）类似 spring 的框架。对解耦会有更好的帮助。

比如适配 solon，就发现一些潜藏的问题

**Comment by funky-eyes** [comment]
这个问题可以提个pr来修改为中性含义的描述
This question can be changed to a description with neutral meaning by asking a pr.

**Comment by linghengqian** [comment]
Fixed by https://github.com/apache/incubator-seata/pull/7040 ?
