### ISSUE TITLE
update join语句，seata生成更新前镜像时会把数据库中自动更新（ON UPDATE）的字段查出来，但没有加别名，导致字段不明确而报错'Column 'updateTime' in field list is ambiguous'

### ISSUE THREAD

**Issue by gitHubYi** [apache/incubator-seata#6963]
原sql：
update repay_calc_interest_add rcia 
 inner join repay_plan_detail rpd
	set rcia.enable= 'N',
			rcia.updateUser='removeAddInterest'
	where rcia.enable = 'Y'
		and rcia.calcEarlyFeeInfo is null
		and rcia.insCode = rpd.insCode
		and rcia.planNo = rpd.planNo
		and rcia.period = rpd.period
		and rcia.calcDate > rpd.endDate

repay_calc_interest_add 表和repay_plan_detail  都有 updateTime字段，且是自动更新。

seata生成的更新前查询字段和语句
![image](https://github.com/user-attachments/assets/907c96fe-71b5-43a9-9189-32b3660f41ca)
![image](https://github.com/user-attachments/assets/b2545d96-a76a-44ba-b83a-7cb750029e10)

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:  1.8/1.8
- Database version: mysql5.7

请问除了把updateTime字段改为不自动更新外，是否还有其他解决办法

**Comment by funky-eyes** [comment]
如果不对updateTime进行查询，那么当数据回滚后，updateTime的字段就会变动，这将导致数据不一致，没有完全回滚。请帮忙确认2.2版本是否依然有该问题存在
If you do not query updateTime, the field of updateTime will change when the data is rolled back, which will cause data inconsistencies and not a complete rollback. Please help confirm whether the problem still exists in version 2.2.

**Comment by gitHubYi** [comment]
只要升级客户端是吗

**Comment by funky-eyes** [comment]
> 只要升级客户端是吗

是的

**Comment by gitHubYi** [comment]
> 如果不对updateTime进行查询，那么当数据回滚后，updateTime的字段就会变动，这将导致数据不一致，没有完全回滚。请帮忙确认2.2版本是否依然有该问题存在 If you do not query updateTime, the field of updateTime will change when the data is rolled back, which will cause data inconsistencies and not a complete rollback. Please help confirm whether the problem still exists in version 2.2.

2.2版本没有这个问题，对自动更新的字段加了别名

**Comment by gitHubYi** [comment]
我在项目中新建同名类，通过覆盖的方式暂时解决这个问题，issue关闭了
