### ISSUE TITLE
使用seata分布式事务报错

### ISSUE THREAD

**Issue by 465722253** [apache/incubator-seata#6967]
org.apache.seata.core.exception.RmTransactionException: branch register failed, xid: 10.244.1.180:8091:5648078290911588357, errMsg: TransactionException[Could not found global transaction xid = 10.244.1.180:8091:5648078290911588357, may be has finished.]

**Comment by funky-eyes** [comment]
https://seata.apache.org/zh-cn/docs/next/overview/faq/#26
