### ISSUE TITLE
How to participate in contributing to Seata?

### ISSUE THREAD

**Issue by TherChenYang** [apache/incubator-seata#6969]
Hello, members of the community.

I am very interested in the Seata project and would like to ask where I can find out what the community is working on and how I can participate.I really hope to make my own contribution to the Seata community.

Hope to get your guidance ！

**Comment by Bughue** [comment]
en: https://seata.apache.org/docs/developers/contributor-guide/new-contributor-guide_dev
cn: https://seata.apache.org/zh-cn/docs/developers/contributor-guide/new-contributor-guide_dev/

**Comment by TherChenYang** [comment]
@Bughue Thank you very much. Where should I go to find updates on the project's progress and some required features?

**Comment by lightClouds917** [comment]
Welcome to contributing to Seata. 
We encourage you to start with simple issues.
for example, https://github.com/apache/incubator-seata/issues to find "task:help-wanted", which means we need someone to fix this issue. 
![image](https://github.com/user-attachments/assets/2e1b9db4-f21b-4d97-8f02-4c11ae04d8d4)

Adding unit tests is always welcome.

**Comment by Bughue** [comment]
> @Bughue Thank you very much. Where should I go to find updates on the project's progress and some required features?

try https://github.com/apache/incubator-seata/labels/good%20first%20issue

**Comment by TherChenYang** [comment]
@lightClouds917 @Bughue thank you very much for your help！
