### ISSUE TITLE
获取全局锁失败，配置文件中更改配置也不好使

### ISSUE THREAD

**Issue by 465722253** [apache/incubator-seata#6970]
org.apache.seata.rm.datasource.exec.LockConflictException: get global lock fail, xid:10.244.1.180:8091:5648078290911593687, lockKeys:tbl_jira:56172;tbl_jira:59390
![截屏2024-11-01 16 51 35](https://github.com/user-attachments/assets/a1d3322a-5f06-4691-9470-911b510323dd)
![截屏2024-11-01 16 52 02](https://github.com/user-attachments/assets/8af40128-42b5-4937-bbec-fb45901259cd)

**Comment by funky-eyes** [comment]
请通过server日志排查锁被谁持有了，可以尝试通过globaltransactional注解上的lock相关的配置增加重试次数和间隔来调优
Please check the server logs to identify who is holding the lock. You can try adjusting the retry count and interval related to the lock configuration in the `@GlobalTransactional` annotation to optimize it.

**Comment by 465722253** [comment]
![截屏2024-11-01 17 07 00](https://github.com/user-attachments/assets/fc934356-5ad0-46da-be8a-a4655d687d27)
jia'l
加了这个配置还是报错

**Comment by 465722253** [comment]
用的是2.0.1的版本  springboot3  jdk17  pgsql  hibernate

**Comment by funky-eyes** [comment]
请通过server日志排查锁被谁持有了

**Comment by funky-eyes** [comment]
实在无法提供这些细节让社区协助的话，你可以换xa模式
If you really can't provide these details for the community to assist, you can change to the xa mode.
