### ISSUE TITLE
update没有更新任何数据，prepareUndoLog时报错”images can not be null“

### ISSUE THREAD

**Issue by gitHubYi** [apache/incubator-seata#6976]
请问如果我去掉这个校验是否会有其他影响？我现在使用的是1.8版本，项目上线，改下sql来不及了
![image](https://github.com/user-attachments/assets/12c25ffa-e69c-4e21-9486-64b9f62f54f2)

- JDK version(e.g. `java -version`):1.8
- Seata client/server version:  1.8/1.8
- Database version: mysql5.7

**Comment by funky-eyes** [comment]
你这个是多语句更新？比如update....;update....;delete....
https://github.com/apache/incubator-seata/blob/v1.8.0/rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
```
    protected void prepareUndoLog(TableRecords beforeImage, TableRecords afterImage) throws SQLException {
        if (beforeImage.getRows().isEmpty() && afterImage.getRows().isEmpty()) {
            return;
        }
        if (SQLType.UPDATE == sqlRecognizer.getSQLType()) {
            if (beforeImage.getRows().size() != afterImage.getRows().size()) {
                throw new ShouldNeverHappenException("Before image size is not equaled to after image size, probably because you updated the primary keys.");
            }
        }
        ConnectionProxy connectionProxy = statementProxy.getConnectionProxy();

        TableRecords lockKeyRecords = sqlRecognizer.getSQLType() == SQLType.DELETE ? beforeImage : afterImage;
        String lockKeys = buildLockKey(lockKeyRecords);
        if (null != lockKeys) {
            connectionProxy.appendLockKey(lockKeys);

            SQLUndoLog sqlUndoLog = buildUndoItem(beforeImage, afterImage);
            connectionProxy.appendUndoLog(sqlUndoLog);
        }
    }
```

**Comment by funky-eyes** [comment]
理论上直接return，保持跟BaseTransactionalExecutor#prepareUndoLog相同逻辑没什么问题
In theory, return directly, keep the same logic as BaseTransactionalExecutor #prepareUndoLog, no problem

**Comment by gitHubYi** [comment]
> 你这个是多语句更新？比如update....;update....;delete.... https://github.com/apache/incubator-seata/blob/v1.8.0/rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
> 
> ```
>     protected void prepareUndoLog(TableRecords beforeImage, TableRecords afterImage) throws SQLException {
>         if (beforeImage.getRows().isEmpty() && afterImage.getRows().isEmpty()) {
>             return;
>         }
>         if (SQLType.UPDATE == sqlRecognizer.getSQLType()) {
>             if (beforeImage.getRows().size() != afterImage.getRows().size()) {
>                 throw new ShouldNeverHappenException("Before image size is not equaled to after image size, probably because you updated the primary keys.");
>             }
>         }
>         ConnectionProxy connectionProxy = statementProxy.getConnectionProxy();
> 
>         TableRecords lockKeyRecords = sqlRecognizer.getSQLType() == SQLType.DELETE ? beforeImage : afterImage;
>         String lockKeys = buildLockKey(lockKeyRecords);
>         if (null != lockKeys) {
>             connectionProxy.appendLockKey(lockKeys);
> 
>             SQLUndoLog sqlUndoLog = buildUndoItem(beforeImage, afterImage);
>             connectionProxy.appendUndoLog(sqlUndoLog);
>         }
>     }
> ```

是update join语句
![image](https://github.com/user-attachments/assets/eeddb2d6-2dd1-45b3-9a3c-06c53ddde495)
![image](https://github.com/user-attachments/assets/dfde9b47-5c93-4a35-9933-ce2d62e2981a)

**Comment by funky-eyes** [comment]
一样的，可以改为如果都为空就return
