### ISSUE TITLE
docker-compose部署，配置SEATA_IP无效

### ISSUE THREAD

**Issue by 320187240** [apache/incubator-seata#6985]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ.  docker-compose部署时，配置SEATA_IP无效

  seata-server:
    image: seataio/seata-server:1.8.0.1
    container_name: seata-server
    environment:
      - seata_ip=192.168.1.110
      - seata_port=8091
      - seata_store_mode=db
      - seata_config_name=file:/seata/config/registry.conf

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

  seata-server:
    image: seataio/seata-server:1.8.0.1
    container_name: seata-server
    environment:
      - seata_ip=192.168.1.110
      - seata_port=8091
      - seata_store_mode=db
      - seata_config_name=file:/seata/config/registry.conf
    networks:
      - my_network
networks:
  my_network:
    driver: bridge

### Ⅴ. Anything else we need to know?

我怀疑networks覆盖了seata_ip配置，其他Issue提到过docker run 命令启动方式seata_ip是生效的，经测试在不连接容器网络前提下是有效的，但是会导致无法通过域名方式访问其他容器

### Ⅵ. Environment:

- JDK version(1.8):
- Seata client/server version:  seataio/seata-server:1.8.0.1
- Database version: mysql8
- OS(e.g. `uname -a`):win10

**Comment by funky-eyes** [comment]
seata_ip -> SEATA_IP

**Comment by 320187240** [comment]
> seata_ip -> SEATA_IP

实测有用，谢谢
