### ISSUE TITLE
redis不支持cluster吗

### ISSUE THREAD

**Issue by icodegarden** [apache/incubator-seata#6989]
v2.2.0，store使用redis，我的redis是cluster集群，发现seata-server有报错。
是否不支持redis cluster呢？

![image](https://github.com/user-attachments/assets/d187efaa-6fcc-48de-a101-d2c1f74a76fe)

**Comment by funky-eyes** [comment]
不支持，并且2.0开始默认都会切换为lua，pippline和lua，包括tx在redis-cluster上都无法支持
Not supported, and since 2.0, it will be switched to lua, pippline and lua by default, including tx, which cannot be supported in redis-cluster.

**Comment by icodegarden** [comment]
后续能否支持cluster的呢

Redis Sentinel
原理与特点
基于主从复制的单点监控。
监控Redis实例的状态，当主节点不可用时，自动选取一个从节点晋升为新的主节点。
配置相对简单，适合快速部署。
优势
提供了简单的故障检测和自动故障转移机制。
适用于中小型应用，为这些应用提供了简单而有效的高可用性方案。
不足
主要是基于主从复制的模式，扩展性有限。
在处理大规模数据和请求时可能显得力不从心。

**Comment by funky-eyes** [comment]
如果你对主从模式有性能担忧，可以选择dragonfly这类支持多线程及支持redis协议的替代品
If you have performance concerns about the leader/follower model, you can choose alternatives like dragonfly that support multithreding and redis protocols
