### ISSUE TITLE
子服务的XID为空

### ISSUE THREAD

**Issue by zhiguangji2008** [apache/incubator-seata#7003]
seata xa模式，服务器使用nacos注册中心，file为配置中心，mysql数据库。
seata客户端 也是nacos注册中心，file为配置中心，使用xa-sample官方示例做测试， business调用stroage服务时，storge打印XID为空。不知道什么原因，怎么排查

**Comment by funky-eyes** [comment]
https://seata.apache.org/zh-cn/docs/next/overview/faq/#24

**Comment by zhiguangji2008** [comment]
> https://seata.apache.org/zh-cn/docs/next/overview/faq/#24

去掉这个
     <dependency>
            <groupId>org.apache.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>2.1.0</version>
        </dependency>
增加这个
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2023.0.1.3</version>
        </dependency>

如果不行再增加一个TransactionPropagationInterceptor拦截器，是这样吧

**Comment by funky-eyes** [comment]
是的，某个版本后貌似这个自动注册拦截器的功能突然不行了，貌似是兼容Jakarta后，所以需要手动注册一下
Yes, it seems that after a certain version, the automatic registration interceptor feature stopped working, likely due to the compatibility with Jakarta. Therefore, it is necessary to register it manually.

**Comment by zhiguangji2008** [comment]
现在启动报java版本错误，FAQ-34，说明是支持JDK8的呢
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.alibaba.cloud.seata.feign.SeataFeignClientAutoConfiguration] for bean with name 'com.alibaba.cloud.seata.feign.SeataFeignClientAutoConfiguration': problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: com/alibaba/cloud/seata/feign/SeataFeignClientAutoConfiguration has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0



Q: 34.Seata的JDK版本要求？
A:

目前 Seata 支持的 JDK 版本为 JDK8、11。其余版本不确保 100%兼容

**Comment by funky-eyes** [comment]
这个跟seata无关，是SeataFeignClientAutoConfiguration 这个类用了jdk17进行了release，应该是spring-cloud-alibaba社区适配了springboot3及对应的springcloud版本，所以肯定是要求你再jdk17下运行
This is unrelated to Seata. The class SeataFeignClientAutoConfiguration was released with JDK 17, and it seems that the Spring Cloud Alibaba community has adapted it to support Spring Boot 3 and the corresponding Spring Cloud version. Therefore, it definitely requires you to run it under JDK 17.

**Comment by zhiguangji2008** [comment]
🙏感谢，测试过了，问题解决了

**Comment by funky-eyes** [comment]
还有什么问题的话后面欢迎提新的issue沟通哈
If you have any further questions, feel free to raise new issues for communication
