### ISSUE TITLE
seata 1.6.1版本，通过nacos配置，修改TM服务的nacos配置文件，在不重启TM服务的情况下，获取xid失败

### ISSUE THREAD

**Issue by hugohong999** [apache/incubator-seata#7026]
seata 1.6.1版本，通过nacos配置，修改TM服务的nacos配置文件，在不重启TM服务的情况下，获取xid失败；
能否在修改nacos配置文件时不需要重启服务？

**Comment by hugohong999** [comment]
问题已经定位到，@RefreshScope 注解造成影响，去掉该注解全局事务正常

**Comment by slievrly** [comment]
Is @RefreshScope marked on the business method? What does this have to do with Seata's configuration?

**Comment by hugohong999** [comment]
> Is @RefreshScope marked on the business method? What does this have to do with Seata's configuration?

与seata's configuration没关系，主要原因是服务的配置跟seata 配置是在同一个nacos配置文件里面，修改nacos配置文件任何配置时为了不重启服务的情况下立即生效所以用了@RefreshScope刷新配置，该注解会刷新bean，实现事务的类正好使用了该注解，导致每次修改nacos配置，都会刷新该类的bean,从而导致事务失效；正确的做法应该是单独用一个配置类引用@RefreshScope注解来刷新配置即可解决该问题；
