### ISSUE TITLE
Seata2.2 + RocketMQ5.0   测试 rocketMQ异常情况，发送半消息失败，回滚全局事务失败

### ISSUE THREAD

**Issue by tinet-lijian** [apache/incubator-seata#7034]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
 测试  Seata2.2 + RocketMQ5.0 异常情况，发送半消息失败，回滚全局事务失败
 
<img width="1367" alt="image" src="https://github.com/user-attachments/assets/e94b4041-fef6-4bbb-abec-14d1637ff537">

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

两个RM ，A RM（mysql），B RM(RocketMQ)，
1、执行A RM，
2、在执行B RM 发送half消息之前把broker kill掉。
3、然后再执行发送半消息。

运行结果：未回滚，抛出NPE

Minimal yet complete reproducer code (or URL to code):
1、prepare 中发送半消息时抛异常
      params.put(ROCKET_SEND_RESULT_KEY, sendResult); 未执行到此断代码。 
2、在rollback时 ，sendResult.getOffsetMsgId()此代码就会NPE
![image](https://github.com/user-attachments/assets/8e789f4b-b529-46e7-bd9e-bcbecde61470)
![image](https://github.com/user-attachments/assets/6ba02b09-0651-4ba8-a45d-2341dab608d5)

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 8
- Seata client/server version:   2.2
- Database version: mysql 8
- OS(e.g. `uname -a`):  mac
- Others:

**Comment by funky-eyes** [comment]
```
params.put(ROCKET_SEND_RESULT_KEY, sendResult); 未执行到此断代码。
2、在rollback时 ，sendResult.getOffsetMsgId()此代码就会NPE
```
未执行到此，如果没有进行report，sendResult是null的，不会执行endTransaction，为什么会运行到endTransaction？

**Comment by funky-eyes** [comment]
确实有此问题，我们处理下
There is indeed this problem, we will deal with it.

**Comment by funky-eyes** [comment]
该问题有2个可能性
1.提前回滚，如timeout，或tc timeout rollback，而分支才进行到注册分支，还没report，此时就下发会有该异常，但是会通过重试回滚解决，对业务无影响
2.producer侧挂了，发出了半消息，但是没有report就关闭了，这个问题通过了TransactionListener解决了
该异常并不影响业务正确性

**Comment by tinet-lijian** [comment]
> 该问题有2个可能性 1.提前回滚，如timeout，或tc timeout rollback，而分支才进行到注册分支，还没report，此时就下发会有该异常，但是会通过重试回滚解决，对业务无影响 2.producer侧挂了，发出了半消息，但是没有report就关闭了，这个问题通过了TransactionListener解决了 该异常并不影响业务正确性

你说第1个可能性，和我的理解有些出入（我的理解rocketmq 事务消息分支注册应该是在发半消息之前进行注册。如理解不对，能否提供相关文档我研究下）。我的这个场景下，发送半消息失败后，运行的日志显示一直在重试回滚，始终是 SendResult 的npe。全局锁一直在，没被释放。最终导致数据库中已经修改的数据没有回滚。
（如果在网络波动的情况下，TC、RM和RocketMQ之间的通信不稳定，就很容易出现此问题：发送半消息失败，则抛异常，SendResult则为null,  捕获到此异常后则进行全局回滚。走到rocketmq 的 rollback逻辑，就会出现NPE）
第二个可能性，应该不会出现此问题问题，半消息发送成功，SendResult不会为null。 不会出现此问题。就算report异常，可以通过回查机制进行rollback或者commit。
<img width="722" alt="image" src="https://github.com/user-attachments/assets/b8ca632c-abf5-4f61-96e8-ef20f1883b12">
这段代码，我好奇的是rollback 方法中如果SendResult为null时 为什么还要走endTransaction ,因为endTransction要取SendResult里的属性。

**Comment by funky-eyes** [comment]
1.因为npe了，所以一直无限重试，由于你其中存在at分支，而server默认是串行回滚，导致了这个分支阻塞了其他分支的回滚行为，你可以考虑开启并行回滚，这就会隔离开不同的resourceid进行回滚。
2.是的，这个问题我们将直接视为其回滚成功即可，应该在上面if内增加return即可，然后通过TransactionListener解决与rocketmq一致性的问题。

**Comment by tinet-lijian** [comment]
> 分支
这个并行回滚，我抽时间试试。
但并行的情况下，回滚失败的resourceid 会不会一直不停的重试回滚了?  重试的机制什么？像我这种场景，针对rocketmq 半消息发送失败，不应该对此resourceid进行重试回滚（是无效回滚重试操作）。
