### ISSUE TITLE
使用2.2.0源码直接运行报错VersionInfo未找到

### ISSUE THREAD

**Issue by jianleiyu** [apache/incubator-seata#7035]
报错信息：
java: 找不到符号
  符号:   变量 VersionInfo
  位置: 类 org.apache.seata.core.protocol.Version

对应文件为 package org.apache.seata.core.protocol;
public class Version {
 private static final String CURRENT = VersionInfo.VERSION;

**Comment by LegGasai** [comment]
重新mvn clean install试试
