### ISSUE TITLE
获取全局锁失败，报错信息：io.seata.rm.datasource.exec.LockConflictException：get global lock fail

### ISSUE THREAD

**Issue by aa13211062762** [apache/incubator-seata#7050]
操作某条记录时会一直报这个错误：io.seata.rm.datasource.exec.LockConflictException：get global lock fail
经查询seata的这两个表(global_table和lock_table)都有这条记录，发现这条记录在global_table的状态字段(status)为5，需要手动删除这些记录后才能恢复正常，请问这个问题如何解决

**Comment by slievrly** [comment]
Please check whether the other branch transactions included in this xid have been automatically rollbacked.

**Comment by funky-eyes** [comment]
When the status is 5, a rollback will be automatically performed, and no manual intervention is required. If you encounter a situation where a data record cannot acquire a lock, you should provide the server logs corresponding to that specific time point, along with a description of the operations you performed.

**Comment by aa13211062762** [comment]
@slievrly @funky-eyes 业务场景是同一个接口被触发多次，这个接口是会抛出异常的，并发情况的其中一次请求就会一直处于RollbackRetrying状态，global_table表上status字段值为5，timeout为60000，这条记录会一直挂着，不会自动执行回滚。其它接口对这条记录操作时就出现io.seata.rm.datasource.exec.LockConflictException：get global lock fail的报错，这个问题我们已经复现了

**Comment by aa13211062762** [comment]
seata的版本是1.1.0

**Comment by funky-eyes** [comment]
Then you should consider upgrading the version

**Comment by aa13211062762** [comment]
@funky-eyes Is this a bug in the lower version of Seata? This abnormal interface has nested transactions

**Comment by funky-eyes** [comment]
I'm not sure, and I won't go back to review the code of earlier versions to help troubleshoot this issue. Even if I find the problem, it doesn't mean the latest version has the same issue. Moreover, to my knowledge, at least the last three versions do not have this problem. If you're interested, you can check the Seata changelog to see what changes have occurred between each version.
