### ISSUE TITLE
When the channel is empty, the request will be blocked

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#7057]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
![image](https://github.com/user-attachments/assets/ef2de664-2b45-4b4a-91cd-702f0d3ee09a)
![image](https://github.com/user-attachments/assets/d51cf434-71dc-40a3-8ad7-fff2429c2819)

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by lyl2008dsg** [comment]
I would like to claim this task
