### ISSUE TITLE
请教关于distributed_lock中的数据

### ISSUE THREAD

**Issue by wxrqforever** [apache/incubator-seata#7078]
目前已完成seata-server的部署，和多个应用以nacos的方式接入seata-server。目前没有实际的全局事务在运行，但是发现server的distributed_lock表里时不时就会有一些数据然后又立马消失，想了解下这个数据的用途是什么？某一时刻的数据如下

lock_key                  lock_value           expire
AsyncCommitting    xx.x.x.x:8091   1735199112933
RetryCommitting      xx.x.x.x:8091   1735199112933
RetryRollbacking
TxTimeoutCheck     xx.x.x.x:8091   1735199112934
UndologDelete

lock_value的值看起来是ip端口对，但这些ip也不是客户端的ip。这些数据是正常的吗？会对使用有影响吗？

**Comment by funky-eyes** [comment]
为了防止同一时间多个tc同时进行补偿动作，比如重试提交/回滚。
To prevent multiple TCs from performing compensation actions (such as retrying submit/rollback) at the same time.

**Comment by wxrqforever** [comment]
> 为了防止同一时间多个tc同时进行补偿动作，比如重试提交/回滚。
> To prevent multiple TCs from performing compensation actions (such as retrying submit/rollback) at the same time.

但是现在应用只是接入了，并没有实际在使用全局事务，这个机制也会不断运行吗？并没有需要重试提交/回滚的全局事务、或者分支事务。

**Comment by funky-eyes** [comment]
> > 为了防止同一时间多个tc同时进行补偿动作，比如重试提交/回滚。
> > To prevent multiple TCs from performing compensation actions (such as retrying submit/rollback) at the same time.
> 
> 但是现在应用只是接入了，并没有实际在使用全局事务，这个机制也会不断运行吗？并没有需要重试提交/回滚的全局事务、或者分支事务。

因为是定时任务，执行前先拿到锁再执行任务，对业务没影响的。
Because it is a scheduled task, get the lock before executing the task, which has no impact on the business.

**Comment by wxrqforever** [comment]
> > > 为了防止同一时间多个tc同时进行补偿动作，比如重试提交/回滚。
> > > To prevent multiple TCs from performing compensation actions (such as retrying submit/rollback) at the same time.
> > 
> > 
> > 但是现在应用只是接入了，并没有实际在使用全局事务，这个机制也会不断运行吗？并没有需要重试提交/回滚的全局事务、或者分支事务。
> 
> 因为是定时任务，执行前先拿到锁再执行任务，对业务没影响的。 Because it is a scheduled task, get the lock before executing the task, which has no impact on the business.
明白了 多谢
