### ISSUE TITLE
Integrate Seata and ShardingSphere

### ISSUE THREAD

**Issue by terrymanu** [apache/incubator-seata#983]
[ShardingSphere](https://github.com/apache/incubator-shardingsphere) is an open-source ecosystem consisted of a set of distributed database middleware solutions, including 2 independent products, Sharding-JDBC, Sharding-Proxy. 

They all provide functions of data sharding, distributed transaction and database orchestration, applicable in a variety of situations such as Java isomorphism, heterogeneous language and cloud native.

`ShardingSphere` are very glad to integrate `Seata` as a kind of distributed transaction implementation.

It has already create [issue](https://github.com/apache/incubator-shardingsphere/issues/2335) to discuss more details, we can discuss how to integration them better.

**Comment by zhangthen** [comment]
Lock forward to it.

**Comment by LingCoder** [comment]
Great work!!!Look forward

**Comment by cherrylzhao** [comment]
hi, all 
we have implemented `SeataATShardingTransactionManager` in this way.
![image](https://user-images.githubusercontent.com/8317649/57828370-df56db80-77dd-11e9-9c86-103787cb5f56.png)

you can get more details from our [example](https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/transaction-example/transaction-base-seata-example).

During integration, I have found some issues that need to be done in seata side.

1. binding xid when creating ConnectionProxy
    this can avoid to passing thread local context in multi-threads scenario. 
    for shardingsphere, we also create connection & statement in main thread, execute statement in   multi-thread.
2. reset initialized flag  & instance when destroy RpcClient.
3. batch remove undo_log SQL is wrong
    it have been resolved in develop branch.
4. consider about adding a SPI for SQL-Recovery to avoid parsing SQL twice between Seata and ShardingSphere.

I prefer to contribute PRs that.

**Comment by wuzunqian** [comment]
integrate seata and shardingsphere seems just need to config datasource wrapper by io.seata.rm.datasource.DataSourceProxy in sharding's config file, and it's flexible to change Distributed Transaction Framework

**Comment by cherrylzhao** [comment]
@wuzunqian ShardingSphere have provided transaction api for integrating other transaction, transaction type can changed dynamically in runtime, also you can config DataSourceProxy directly in your application.

**Comment by jyizheng** [comment]
I am interested in this issue. What it the status of it?

**Comment by terrymanu** [comment]
This issue is finished, and ShardingSphere has already provide a example. Please try to use in your application if somebody interested.

FYI: https://github.com/apache/incubator-shardingsphere-example/tree/dev/sharding-jdbc-example/transaction-example/transaction-base-seata-raw-jdbc-example

I will close this issue if test enough.

**Comment by linghengqian** [comment]
- Once https://github.com/apache/shardingsphere/pull/32095 is merged, the Seata AT mode integration failure between multiple ShardingSphere JDBC DataSources in multiple microservices should be resolved, but the integration test for the corresponding PR is temporarily outside the master branch. I think the integration test needs to wait for https://github.com/apache/incubator-seata/issues/6614 to be resolved.
